Repository OCA/management-system, pull requests merged in 2018-10, with the labels that each got.

#215 [11.0][MIG] mgmtsystem manual
  mgmtsystem_manual/README.rst
  mgmtsystem_manual/__init__.py
  mgmtsystem_manual/__manifest__.py
  mgmtsystem_manual/data/mgmtsystem_manual.xml
  mgmtsystem_manual/i18n/de.po
  mgmtsystem_manual/i18n/es.po
  mgmtsystem_manual/i18n/fr.po
  mgmtsystem_manual/i18n/hr_HR.po
  mgmtsystem_manual/i18n/lv.po
  mgmtsystem_manual/i18n/mgmtsystem_manuals.pot
  mgmtsystem_manual/i18n/nb.po
  mgmtsystem_manual/i18n/nl_NL.po
  mgmtsystem_manual/i18n/nn.po
  mgmtsystem_manual/i18n/pt_BR.po
  mgmtsystem_manual/i18n/sl.po
  mgmtsystem_manual/i18n/sv.po
  mgmtsystem_manual/i18n/th.po
  mgmtsystem_manual/i18n/vi.po
  mgmtsystem_manual/models/__init__.py
  mgmtsystem_manual/models/mgmtsystem_manual.py
  mgmtsystem_manual/static/description/icon.png
  mgmtsystem_manual/views/document_page.xml
  mgmtsystem_manual/views/mgmtsystem_manual.xml
  oca_dependencies.txt
Labels: needs review

#235 [11.0] mgmtsystem configuration page
  mgmtsystem/migrations/6.1.1.0/openupgrade_analysis.txt
  mgmtsystem/models/mgmtsystem_system.py
  mgmtsystem/models/res_config.py
  mgmtsystem/views/res_config.xml
Labels: needs review

#214 [11.0][MIG] document page procedure
  document_page_procedure/README.rst
  document_page_procedure/__init__.py
  document_page_procedure/__manifest__.py
  document_page_procedure/data/document_page_procedure.xml
  document_page_procedure/demo/document_page_procedure.xml
  document_page_procedure/i18n/de.po
  document_page_procedure/i18n/document_page_procedure.pot
  document_page_procedure/i18n/es.po
  document_page_procedure/i18n/es_CO.po
  document_page_procedure/i18n/fr.po
  document_page_procedure/i18n/hr.po
  document_page_procedure/i18n/hr_HR.po
  document_page_procedure/i18n/hu.po
  document_page_procedure/i18n/nb.po
  document_page_procedure/i18n/nl_NL.po
  document_page_procedure/i18n/pt.po
  document_page_procedure/i18n/pt_BR.po
  document_page_procedure/i18n/sl.po
  document_page_procedure/i18n/sv.po
  document_page_procedure/i18n/vi.po
  document_page_procedure/static/description/icon.png
  document_page_procedure/views/document_page_procedure.xml
Labels: needs fixing

#216 [11.0][MIG] document page quality manual
  document_page_quality_manual/README.rst
  document_page_quality_manual/__init__.py
  document_page_quality_manual/__manifest__.py
  document_page_quality_manual/data/document_page.xml
  document_page_quality_manual/i18n/ar.po
  document_page_quality_manual/i18n/bg.po
  document_page_quality_manual/i18n/ca.po
  document_page_quality_manual/i18n/cs.po
  document_page_quality_manual/i18n/da.po
  document_page_quality_manual/i18n/de.po
  document_page_quality_manual/i18n/document_page_quality_manual.pot
  document_page_quality_manual/i18n/es.po
  document_page_quality_manual/i18n/es_CR.po
  document_page_quality_manual/i18n/es_MX.po
  document_page_quality_manual/i18n/es_VE.po
  document_page_quality_manual/i18n/fi.po
  document_page_quality_manual/i18n/fr.po
  document_page_quality_manual/i18n/gl.po
  document_page_quality_manual/i18n/hr.po
  document_page_quality_manual/i18n/hu.po
  document_page_quality_manual/i18n/it.po
  document_page_quality_manual/i18n/ja.po
  document_page_quality_manual/i18n/lv.po
  document_page_quality_manual/i18n/mn.po
  document_page_quality_manual/i18n/nb.po
  document_page_quality_manual/i18n/nl.po
  document_page_quality_manual/i18n/oc.po
  document_page_quality_manual/i18n/pt.po
  document_page_quality_manual/i18n/pt_BR.po
  document_page_quality_manual/i18n/ro.po
  document_page_quality_manual/i18n/ru.po
  document_page_quality_manual/i18n/sk.po
  document_page_quality_manual/i18n/sl.po
  document_page_quality_manual/i18n/sr@latin.po
  document_page_quality_manual/i18n/sv.po
  document_page_quality_manual/i18n/tr.po
  document_page_quality_manual/i18n/vi.po
  document_page_quality_manual/i18n/zh_CN.po
  document_page_quality_manual/images/wiki_pages_quality_manual.jpeg
  document_page_quality_manual/static/description/icon.png
Labels: needs fixing

#236 [IMP] mgmtsystem_action
  mgmtsystem_action/README.rst
  mgmtsystem_action/__manifest__.py
  mgmtsystem_action/data/automated_reminder.xml
  mgmtsystem_action/data/email_template.xml
  mgmtsystem_action/data/mgmtsystem_action_stage.xml
  mgmtsystem_action/migrations/6.1.1.0/openupgrade_analysis.txt
  mgmtsystem_action/migrations/7.0.1.0/post-migration.py
  mgmtsystem_action/migrations/7.0.1.0/pre-migration.py
  mgmtsystem_action/models/__init__.py
  mgmtsystem_action/models/mgmtsystem_action.py
  mgmtsystem_action/models/mgmtsystem_action_stage.py
  mgmtsystem_action/models/mgmtsystem_action_tag.py
  mgmtsystem_action/reports/mgmtsystem_action_report.py
  mgmtsystem_action/security/ir.model.access.csv
  mgmtsystem_action/tests/test_create_action.py
  mgmtsystem_action/views/menus.xml
  mgmtsystem_action/views/mgmtsystem_action.xml
  mgmtsystem_action/views/mgmtsystem_action_stage.xml
  mgmtsystem_action/views/mgmtsystem_action_tag.xml
Labels: bug, needs review
