Repository OCA/management-system, pull requests merged in 2019-06, with the labels that each got.

#249 [MIG][12.0] mgmtsystem_survey
  mgmtsystem_survey/README.rst
  mgmtsystem_survey/__init__.py
  mgmtsystem_survey/__manifest__.py
  mgmtsystem_survey/data/survey_stage.xml
  mgmtsystem_survey/i18n/de.po
  mgmtsystem_survey/i18n/es.po
  mgmtsystem_survey/i18n/es_CO.po
  mgmtsystem_survey/i18n/fi.po
  mgmtsystem_survey/i18n/fr.po
  mgmtsystem_survey/i18n/hr_HR.po
  mgmtsystem_survey/i18n/hu.po
  mgmtsystem_survey/i18n/it.po
  mgmtsystem_survey/i18n/lv.po
  mgmtsystem_survey/i18n/mgmtsystem_survey.pot
  mgmtsystem_survey/i18n/nb.po
  mgmtsystem_survey/i18n/nn.po
  mgmtsystem_survey/i18n/pt.po
  mgmtsystem_survey/i18n/pt_BR.po
  mgmtsystem_survey/i18n/sl.po
  mgmtsystem_survey/i18n/sv.po
  mgmtsystem_survey/i18n/th.po
  mgmtsystem_survey/i18n/tr.po
  mgmtsystem_survey/i18n/vi.po
  mgmtsystem_survey/readme/CONFIGURE.rst
  mgmtsystem_survey/readme/CONTRIBUTORS.rst
  mgmtsystem_survey/readme/DESCRIPTION.rst
  mgmtsystem_survey/readme/USAGE.rst
  mgmtsystem_survey/static/description/icon.png
  mgmtsystem_survey/static/description/index.html
  mgmtsystem_survey/views/survey_survey.xml
Labels: approved

#246 [MIG] [12.0] mgmtsystem manual
  mgmtsystem_manual/README.rst
  mgmtsystem_manual/__init__.py
  mgmtsystem_manual/__manifest__.py
  mgmtsystem_manual/data/mgmtsystem_manual.xml
  mgmtsystem_manual/i18n/de.po
  mgmtsystem_manual/i18n/es.po
  mgmtsystem_manual/i18n/fr.po
  mgmtsystem_manual/i18n/hr_HR.po
  mgmtsystem_manual/i18n/it.po
  mgmtsystem_manual/i18n/lv.po
  mgmtsystem_manual/i18n/nb.po
  mgmtsystem_manual/i18n/nl_NL.po
  mgmtsystem_manual/i18n/nn.po
  mgmtsystem_manual/i18n/pt_BR.po
  mgmtsystem_manual/i18n/sl.po
  mgmtsystem_manual/i18n/sv.po
  mgmtsystem_manual/i18n/th.po
  mgmtsystem_manual/i18n/vi.po
  mgmtsystem_manual/models/__init__.py
  mgmtsystem_manual/models/mgmtsystem_manual.py
  mgmtsystem_manual/readme/CONFIGURE.rst
  mgmtsystem_manual/readme/CONTRIBUTORS.rst
  mgmtsystem_manual/readme/DESCRIPTION.rst
  mgmtsystem_manual/readme/HISTORY.rst
  mgmtsystem_manual/readme/INSTALL.rst
  mgmtsystem_manual/readme/USAGE.rst
  mgmtsystem_manual/static/description/icon.png
  mgmtsystem_manual/static/description/index.html
  mgmtsystem_manual/views/document_page.xml
  mgmtsystem_manual/views/mgmtsystem_manual.xml
Labels: approved, ready to merge

#248 [MIG] 12.0 - document page work instruction
  document_page_work_instruction/README.rst
  document_page_work_instruction/__init__.py
  document_page_work_instruction/__manifest__.py
  document_page_work_instruction/data/document_page.xml
  document_page_work_instruction/i18n/de.po
  document_page_work_instruction/i18n/es.po
  document_page_work_instruction/i18n/es_CO.po
  document_page_work_instruction/i18n/fr.po
  document_page_work_instruction/i18n/hr_HR.po
  document_page_work_instruction/i18n/it.po
  document_page_work_instruction/i18n/nb.po
  document_page_work_instruction/i18n/nl_NL.po
  document_page_work_instruction/i18n/nn.po
  document_page_work_instruction/i18n/no.po
  document_page_work_instruction/i18n/pt_BR.po
  document_page_work_instruction/i18n/sl.po
  document_page_work_instruction/i18n/vi.po
  document_page_work_instruction/readme/CONFIGURE.rst
  document_page_work_instruction/readme/CONTRIBUTORS.rst
  document_page_work_instruction/readme/DESCRIPTION.rst
  document_page_work_instruction/static/description/icon.png
  document_page_work_instruction/static/description/index.html
  document_page_work_instruction/views/document_page_work_instructions.xml
Labels: approved, needs review

#245 [MIG][12.0] mgmtsystem_action
  mgmtsystem_action/README.rst
  mgmtsystem_action/__init__.py
  mgmtsystem_action/__manifest__.py
  mgmtsystem_action/data/action_sequence.xml
  mgmtsystem_action/data/automated_reminder.xml
  mgmtsystem_action/data/email_template.xml
  mgmtsystem_action/data/mgmtsystem_action_stage.xml
  mgmtsystem_action/demo/mgmtsystem_action.xml
  mgmtsystem_action/i18n/am.po
  mgmtsystem_action/i18n/ca.po
  mgmtsystem_action/i18n/de.po
  mgmtsystem_action/i18n/el_GR.po
  mgmtsystem_action/i18n/es.po
  mgmtsystem_action/i18n/es_CO.po
  mgmtsystem_action/i18n/es_ES.po
  mgmtsystem_action/i18n/fi.po
  mgmtsystem_action/i18n/fr.po
  mgmtsystem_action/i18n/gl.po
  mgmtsystem_action/i18n/hr_HR.po
  mgmtsystem_action/i18n/hu.po
  mgmtsystem_action/i18n/it.po
  mgmtsystem_action/i18n/lv.po
  mgmtsystem_action/i18n/mgmtsystem_action.pot
  mgmtsystem_action/i18n/nb.po
  mgmtsystem_action/i18n/nl.po
  mgmtsystem_action/i18n/nl_NL.po
  mgmtsystem_action/i18n/nn.po
  mgmtsystem_action/i18n/pt.po
  mgmtsystem_action/i18n/pt_BR.po
  mgmtsystem_action/i18n/pt_PT.po
  mgmtsystem_action/i18n/sl.po
  mgmtsystem_action/i18n/sv.po
  mgmtsystem_action/i18n/th.po
  mgmtsystem_action/i18n/tr.po
  mgmtsystem_action/i18n/vi.po
  mgmtsystem_action/models/__init__.py
  mgmtsystem_action/models/mgmtsystem_action.py
  mgmtsystem_action/models/mgmtsystem_action_stage.py
  mgmtsystem_action/models/mgmtsystem_action_tag.py
  mgmtsystem_action/readme/CONFIGURE.rst
  mgmtsystem_action/readme/CONTRIBUTORS.rst
  mgmtsystem_action/readme/DESCRIPTION.rst
  mgmtsystem_action/readme/INSTALL.rst
  mgmtsystem_action/readme/USAGE.rst
  mgmtsystem_action/reports/__init__.py
  mgmtsystem_action/reports/mgmtsystem_action_report.py
  mgmtsystem_action/reports/mgmtsystem_action_report.xml
  mgmtsystem_action/security/ir.model.access.csv
  mgmtsystem_action/security/mgmtsystem_action_security.xml
  mgmtsystem_action/static/description/icon.png
  mgmtsystem_action/static/description/index.html
  mgmtsystem_action/tests/__init__.py
  mgmtsystem_action/tests/test_create_action.py
  mgmtsystem_action/views/menus.xml
  mgmtsystem_action/views/mgmtsystem_action.xml
  mgmtsystem_action/views/mgmtsystem_action_kanban.xml
  mgmtsystem_action/views/mgmtsystem_action_stage.xml
  mgmtsystem_action/views/mgmtsystem_action_tag.xml
Labels: approved

#250 [12.0] [MIG] document page procedure
  document_page_procedure/README.rst
  document_page_procedure/__init__.py
  document_page_procedure/__manifest__.py
  document_page_procedure/data/document_page_procedure.xml
  document_page_procedure/demo/document_page_procedure.xml
  document_page_procedure/i18n/de.po
  document_page_procedure/i18n/es.po
  document_page_procedure/i18n/es_CO.po
  document_page_procedure/i18n/fr.po
  document_page_procedure/i18n/hr.po
  document_page_procedure/i18n/hr_HR.po
  document_page_procedure/i18n/hu.po
  document_page_procedure/i18n/it.po
  document_page_procedure/i18n/nb.po
  document_page_procedure/i18n/nl_NL.po
  document_page_procedure/i18n/pt.po
  document_page_procedure/i18n/pt_BR.po
  document_page_procedure/i18n/sl.po
  document_page_procedure/i18n/sv.po
  document_page_procedure/i18n/vi.po
  document_page_procedure/readme/CONFIGURE.rst
  document_page_procedure/readme/CONTRIBUTORS.rst
  document_page_procedure/readme/DESCRIPTION.rst
  document_page_procedure/static/description/icon.png
  document_page_procedure/static/description/index.html
  document_page_procedure/views/document_page_procedure.xml
Labels: approved

#253 [MIG] [12.0] document page quality manual
  document_page_quality_manual/README.rst
  document_page_quality_manual/__init__.py
  document_page_quality_manual/__manifest__.py
  document_page_quality_manual/data/document_page.xml
  document_page_quality_manual/i18n/ar.po
  document_page_quality_manual/i18n/bg.po
  document_page_quality_manual/i18n/ca.po
  document_page_quality_manual/i18n/cs.po
  document_page_quality_manual/i18n/da.po
  document_page_quality_manual/i18n/de.po
  document_page_quality_manual/i18n/es.po
  document_page_quality_manual/i18n/es_CR.po
  document_page_quality_manual/i18n/es_MX.po
  document_page_quality_manual/i18n/es_VE.po
  document_page_quality_manual/i18n/fi.po
  document_page_quality_manual/i18n/fr.po
  document_page_quality_manual/i18n/gl.po
  document_page_quality_manual/i18n/hr.po
  document_page_quality_manual/i18n/hu.po
  document_page_quality_manual/i18n/it.po
  document_page_quality_manual/i18n/ja.po
  document_page_quality_manual/i18n/lv.po
  document_page_quality_manual/i18n/mn.po
  document_page_quality_manual/i18n/nb.po
  document_page_quality_manual/i18n/nl.po
  document_page_quality_manual/i18n/oc.po
  document_page_quality_manual/i18n/pt.po
  document_page_quality_manual/i18n/pt_BR.po
  document_page_quality_manual/i18n/ro.po
  document_page_quality_manual/i18n/ru.po
  document_page_quality_manual/i18n/sk.po
  document_page_quality_manual/i18n/sl.po
  document_page_quality_manual/i18n/sr@latin.po
  document_page_quality_manual/i18n/sv.po
  document_page_quality_manual/i18n/tr.po
  document_page_quality_manual/i18n/vi.po
  document_page_quality_manual/i18n/zh_CN.po
  document_page_quality_manual/images/wiki_pages_quality_manual.jpeg
  document_page_quality_manual/readme/CONFIGURE.rst
  document_page_quality_manual/readme/CONTRIBUTORS.rst
  document_page_quality_manual/readme/DESCRIPTION.rst
  document_page_quality_manual/readme/USAGE.rst
  document_page_quality_manual/static/description/icon.png
  document_page_quality_manual/static/description/index.html
Labels: approved
