Repository OCA/management-system, pull requests merged in 2020-04, with the labels that each got.

#318 [FIX] missing compute
  mgmtsystem_nonconformity/models/mgmtsystem_nonconformity.py
Labels: approved, bot is merging ⏳, ready to merge

#316 FIX mgmtsystem: Applying multicompany style
  mgmtsystem/models/mgmtsystem_system.py
  mgmtsystem/tests/test_create_mgmtsystem.py
Labels: approved, bot is merging ⏳, ready to merge

#312 FIX mgmtsystem_nonconformity: Applying multicompany style
  mgmtsystem_nonconformity/models/mgmtsystem_nonconformity.py
  mgmtsystem_nonconformity/security/mgmtsystem_nonconformity_security.xml
Labels: approved, bot is merging ⏳

#311 FIX mgmtsystem_audit: Multicompany style
  mgmtsystem_audit/models/mgmtsystem_audit.py
  mgmtsystem_audit/models/mgmtsystem_verification_line.py
  mgmtsystem_audit/security/mgmtsystem_audit_security.xml
Labels: approved, bot is merging ⏳

#310 Fix mgmtsystem_action: Applying multicompany style
  mgmtsystem_action/models/mgmtsystem_action.py
  mgmtsystem_action/security/mgmtsystem_action_security.xml
Labels: approved, bot is merging ⏳

#265 [11.0] [ADD] new module mgmsystem_nonconformity_hr
  mgmtsystem_nonconformity_hr/README.rst
  mgmtsystem_nonconformity_hr/__init__.py
  mgmtsystem_nonconformity_hr/__manifest__.py
  mgmtsystem_nonconformity_hr/i18n/it.po
  mgmtsystem_nonconformity_hr/i18n/mgmtsystem_extended_hr.pot
  mgmtsystem_nonconformity_hr/models/__init__.py
  mgmtsystem_nonconformity_hr/models/mgmtsystem_nonconformity_hr.py
  mgmtsystem_nonconformity_hr/readme/CONFIGURE.rst
  mgmtsystem_nonconformity_hr/readme/CONTRIBUTORS.rst
  mgmtsystem_nonconformity_hr/readme/DESCRIPTION.rst
  mgmtsystem_nonconformity_hr/readme/HISTORY.rst
  mgmtsystem_nonconformity_hr/readme/INSTALL.rst
  mgmtsystem_nonconformity_hr/readme/ROADMAP.rst
  mgmtsystem_nonconformity_hr/readme/USAGE.rst
  mgmtsystem_nonconformity_hr/static/description/icon.png
  mgmtsystem_nonconformity_hr/static/description/index.html
  mgmtsystem_nonconformity_hr/views/mgmtsystem_nonconformity_views.xml
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#296 [13.0][MIG] mgmtsystem_quality
  mgmtsystem_quality/README.rst
  mgmtsystem_quality/__init__.py
  mgmtsystem_quality/__manifest__.py
  mgmtsystem_quality/data/mgmtsystem_system.xml
  mgmtsystem_quality/i18n/de.po
  mgmtsystem_quality/i18n/fr.po
  mgmtsystem_quality/i18n/mgmtsystem_quality.pot
  mgmtsystem_quality/i18n/nb.po
  mgmtsystem_quality/i18n/pt_BR.po
  mgmtsystem_quality/i18n/sv.po
  mgmtsystem_quality/i18n/vi.po
  mgmtsystem_quality/readme/CONFIGURE.rst
  mgmtsystem_quality/readme/CONTRIBUTORS.rst
  mgmtsystem_quality/readme/DESCRIPTION.rst
  mgmtsystem_quality/readme/ROADMAP.rst
  mgmtsystem_quality/readme/USAGE.rst
  mgmtsystem_quality/static/description/icon.png
  mgmtsystem_quality/static/description/index.html
Labels: approved, bot is merging ⏳, migration, needs review

#319 [13.0][MIG] document_page_environmental_aspect
  document_page_environmental_aspect/README.rst
  document_page_environmental_aspect/__init__.py
  document_page_environmental_aspect/__manifest__.py
  document_page_environmental_aspect/data/document_page.xml
  document_page_environmental_aspect/i18n/de.po
  document_page_environmental_aspect/i18n/document_page_environmental_aspect.pot
  document_page_environmental_aspect/i18n/es_CL.po
  document_page_environmental_aspect/i18n/fr.po
  document_page_environmental_aspect/i18n/nb.po
  document_page_environmental_aspect/i18n/pt_BR.po
  document_page_environmental_aspect/i18n/sl.po
  document_page_environmental_aspect/i18n/sv.po
  document_page_environmental_aspect/i18n/vi.po
  document_page_environmental_aspect/readme/CONFIGURE.rst
  document_page_environmental_aspect/readme/CONTRIBUTORS.rst
  document_page_environmental_aspect/readme/DESCRIPTION.rst
  document_page_environmental_aspect/readme/USAGE.rst
  document_page_environmental_aspect/security/environmental_aspect_security.xml
  document_page_environmental_aspect/static/description/icon.png
  document_page_environmental_aspect/views/document_page.xml
Labels: approved, bot is merging ⏳, ready to merge

#322 [13.0] [FIX] missing compute for mgmtsystem_nonconformity
  mgmtsystem_nonconformity/models/mgmtsystem_nonconformity.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#327 [11.0] [FIX] fields related should be readonly True
  mgmtsystem_nonconformity/models/mgmtsystem_nonconformity.py
Labels: bot is merging ⏳

#328 [FIX] mgmtsystem: Changed label of model field name
  mgmtsystem/i18n/es.po
  mgmtsystem/models/res_config.py
Labels: approved, bot is merging ⏳
