Repository OCA/management-system, pull requests merged in 2020-06, with the labels that each got.

#333 [WIP][FIX] mgmtsystem_audit get_lines_by_procedure
  mgmtsystem_audit/models/mgmtsystem_audit.py
Labels: bot is merging ⏳

#266 [11.0] [ADD] new module mgmsystem_nonconformity_mrp
  mgmtsystem_nonconformity_mrp/README.rst
  mgmtsystem_nonconformity_mrp/__init__.py
  mgmtsystem_nonconformity_mrp/__manifest__.py
  mgmtsystem_nonconformity_mrp/i18n/it.po
  mgmtsystem_nonconformity_mrp/i18n/mgmtsystem_extended_mrp.pot
  mgmtsystem_nonconformity_mrp/models/__init__.py
  mgmtsystem_nonconformity_mrp/models/mgmtsystem_nonconformity_mrp.py
  mgmtsystem_nonconformity_mrp/readme/CONFIGURE.rst
  mgmtsystem_nonconformity_mrp/readme/CONTRIBUTORS.rst
  mgmtsystem_nonconformity_mrp/readme/DESCRIPTION.rst
  mgmtsystem_nonconformity_mrp/readme/HISTORY.rst
  mgmtsystem_nonconformity_mrp/readme/INSTALL.rst
  mgmtsystem_nonconformity_mrp/readme/ROADMAP.rst
  mgmtsystem_nonconformity_mrp/readme/USAGE.rst
  mgmtsystem_nonconformity_mrp/static/description/icon.png
  mgmtsystem_nonconformity_mrp/static/description/index.html
  mgmtsystem_nonconformity_mrp/views/mgmtsystem_nonconformity_views.xml
Labels: approved, bot is merging ⏳, enhancement, needs review

#320 FIX Add model access to hazard
  mgmtsystem_hazard/security/ir.model.access.csv
Labels: approved, bot is merging ⏳, needs review, ready to merge

#325 [12.0] [MIG] mgmtsystem nonconformity hr
  mgmtsystem_nonconformity_hr/README.rst
  mgmtsystem_nonconformity_hr/__init__.py
  mgmtsystem_nonconformity_hr/__manifest__.py
  mgmtsystem_nonconformity_hr/i18n/it.po
  mgmtsystem_nonconformity_hr/i18n/mgmtsystem_extended_hr.pot
  mgmtsystem_nonconformity_hr/i18n/mgmtsystem_nonconformity_hr.pot
  mgmtsystem_nonconformity_hr/models/__init__.py
  mgmtsystem_nonconformity_hr/models/mgmtsystem_nonconformity_hr.py
  mgmtsystem_nonconformity_hr/readme/CONTRIBUTORS.rst
  mgmtsystem_nonconformity_hr/readme/DESCRIPTION.rst
  mgmtsystem_nonconformity_hr/readme/HISTORY.rst
  mgmtsystem_nonconformity_hr/readme/ROADMAP.rst
  mgmtsystem_nonconformity_hr/readme/USAGE.rst
  mgmtsystem_nonconformity_hr/static/description/icon.png
  mgmtsystem_nonconformity_hr/static/description/index.html
  mgmtsystem_nonconformity_hr/views/mgmtsystem_nonconformity_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#267 [11.0] [ADD] new module mgmsystem_nonconformity_product
  mgmtsystem_nonconformity_product/README.rst
  mgmtsystem_nonconformity_product/__init__.py
  mgmtsystem_nonconformity_product/__manifest__.py
  mgmtsystem_nonconformity_product/i18n/it.po
  mgmtsystem_nonconformity_product/i18n/mgmtsystem_extended_product.pot
  mgmtsystem_nonconformity_product/models/__init__.py
  mgmtsystem_nonconformity_product/models/mgmtsystem_nonconformity_product.py
  mgmtsystem_nonconformity_product/readme/CONFIGURE.rst
  mgmtsystem_nonconformity_product/readme/CONTRIBUTORS.rst
  mgmtsystem_nonconformity_product/readme/DESCRIPTION.rst
  mgmtsystem_nonconformity_product/readme/HISTORY.rst
  mgmtsystem_nonconformity_product/readme/INSTALL.rst
  mgmtsystem_nonconformity_product/readme/ROADMAP.rst
  mgmtsystem_nonconformity_product/readme/USAGE.rst
  mgmtsystem_nonconformity_product/static/description/icon.png
  mgmtsystem_nonconformity_product/static/description/index.html
  mgmtsystem_nonconformity_product/views/mgmtsystem_nonconformity_views.xml
Labels: approved, bot is merging ⏳, enhancement, needs review

#326 [13.0] [MIG] mgmtsystem nonconformity hr
  mgmtsystem_nonconformity_hr/README.rst
  mgmtsystem_nonconformity_hr/__init__.py
  mgmtsystem_nonconformity_hr/__manifest__.py
  mgmtsystem_nonconformity_hr/i18n/it.po
  mgmtsystem_nonconformity_hr/i18n/mgmtsystem_extended_hr.pot
  mgmtsystem_nonconformity_hr/i18n/mgmtsystem_nonconformity_hr.pot
  mgmtsystem_nonconformity_hr/models/__init__.py
  mgmtsystem_nonconformity_hr/models/mgmtsystem_nonconformity_hr.py
  mgmtsystem_nonconformity_hr/readme/CONTRIBUTORS.rst
  mgmtsystem_nonconformity_hr/readme/DESCRIPTION.rst
  mgmtsystem_nonconformity_hr/readme/HISTORY.rst
  mgmtsystem_nonconformity_hr/readme/USAGE.rst
  mgmtsystem_nonconformity_hr/static/description/icon.png
  mgmtsystem_nonconformity_hr/static/description/index.html
  mgmtsystem_nonconformity_hr/views/mgmtsystem_nonconformity_views.xml
Labels: approved, bot is merging ⏳, ready to merge
