Repository OCA/management-system, pull requests merged in 2020-12, with the labels that each got.

#361 [IMP] mgmtsystem_nonconformity: active field to origins
  mgmtsystem_nonconformity/models/mgmtsystem_nonconformity_origin.py
  mgmtsystem_nonconformity/views/mgmtsystem_origin.xml
Labels: approved, bot is merging ⏳, ready to merge

#323 [13.0][MIG] mgmtsystem_info_security_manual
  mgmtsystem_info_security_manual/README.rst
  mgmtsystem_info_security_manual/__init__.py
  mgmtsystem_info_security_manual/__manifest__.py
  mgmtsystem_info_security_manual/data/information_security_manual.xml
  mgmtsystem_info_security_manual/readme/CONTRIBUTORS.rst
  mgmtsystem_info_security_manual/readme/DESCRIPTION.rst
  mgmtsystem_info_security_manual/readme/USAGE.rst
  mgmtsystem_info_security_manual/static/description/icon.png
  requirements.txt
Labels: bot is merging ⏳

#299 [MIG] [13.0] document page health safety manual
  document_page_health_safety_manual/README.rst
  document_page_health_safety_manual/__init__.py
  document_page_health_safety_manual/__manifest__.py
  document_page_health_safety_manual/data/document_page.xml
  document_page_health_safety_manual/readme/CONTRIBUTORS.rst
  document_page_health_safety_manual/readme/DESCRIPTION.rst
  document_page_health_safety_manual/readme/ROADMAP.rst
  document_page_health_safety_manual/readme/USAGE.rst
  document_page_health_safety_manual/static/description/icon.png
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#362 [IMP] mgmtsystem_nonconformity: active field to origins
  mgmtsystem_nonconformity/models/mgmtsystem_nonconformity_origin.py
  mgmtsystem_nonconformity/views/mgmtsystem_origin.xml
Labels: approved, bot is merging ⏳
