Repository OCA/management-system, pull requests merged in 2020-07, with the labels that each got.

#338 [FIX] Fix for properly showing content of the template
  document_page_environment_manual/data/document_page_environment_manual.xml
Labels: approved, bot is merging ⏳, ready to merge

#340 [FIX] Changes to common display of forms
  mgmtsystem_manual/views/mgmtsystem_manual.xml
Labels: approved, bot is merging ⏳, ready to merge

#337 [FIX] Fix security, forms and template
  document_page_environmental_aspect/__manifest__.py
  document_page_environmental_aspect/data/document_page.xml
  document_page_environmental_aspect/security/environmental_aspect_security.xml
  document_page_environmental_aspect/views/document_page.xml
Labels: approved, bot is merging ⏳, ready to merge

#336 [12.0] [MIG] mgmtsystem_nonconformity_product
  mgmtsystem_nonconformity_product/README.rst
  mgmtsystem_nonconformity_product/__init__.py
  mgmtsystem_nonconformity_product/__manifest__.py
  mgmtsystem_nonconformity_product/i18n/it.po
  mgmtsystem_nonconformity_product/i18n/mgmtsystem_nonconformity_product.pot
  mgmtsystem_nonconformity_product/models/__init__.py
  mgmtsystem_nonconformity_product/models/mgmtsystem_nonconformity_product.py
  mgmtsystem_nonconformity_product/readme/CONTRIBUTORS.rst
  mgmtsystem_nonconformity_product/readme/DESCRIPTION.rst
  mgmtsystem_nonconformity_product/readme/HISTORY.rst
  mgmtsystem_nonconformity_product/readme/USAGE.rst
  mgmtsystem_nonconformity_product/static/description/icon.png
  mgmtsystem_nonconformity_product/static/description/index.html
  mgmtsystem_nonconformity_product/views/mgmtsystem_nonconformity_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#341 [FIX] Fix the automatic un/install and status display
  mgmtsystem/models/res_config.py
  mgmtsystem/views/res_config.xml
Labels: approved, bot is merging ⏳, ready to merge

#347 [13.0][UPD] Add addons table on README.rst
  README.md
Labels: bot is merging ⏳

#346 [12.0][UPD] Add addons table on README.rst
  README.md
Labels: bot is merging ⏳

#339 [FIX] Fix automatic install of work instruction template
  mgmtsystem/models/res_config.py
  mgmtsystem/views/res_config.xml
Labels: approved, bot is merging ⏳

#314 [13.0][MIG] mgmtsystem_claim
  mgmtsystem_claim/README.rst
  mgmtsystem_claim/__init__.py
  mgmtsystem_claim/__manifest__.py
  mgmtsystem_claim/data/automated_reminder.xml
  mgmtsystem_claim/data/claim_sequence.xml
  mgmtsystem_claim/data/email_template.xml
  mgmtsystem_claim/data/mgmtsystem_claim_stage.xml
  mgmtsystem_claim/i18n/de.po
  mgmtsystem_claim/i18n/es.po
  mgmtsystem_claim/i18n/fr.po
  mgmtsystem_claim/i18n/nb.po
  mgmtsystem_claim/i18n/pt_BR.po
  mgmtsystem_claim/i18n/sl.po
  mgmtsystem_claim/i18n/sv.po
  mgmtsystem_claim/i18n/vi.po
  mgmtsystem_claim/models/__init__.py
  mgmtsystem_claim/models/mgmtsystem_claim.py
  mgmtsystem_claim/models/mgmtsystem_claim_stage.py
  mgmtsystem_claim/models/res_partner.py
  mgmtsystem_claim/readme/CONFIGURE.rst
  mgmtsystem_claim/readme/CONTRIBUTORS.rst
  mgmtsystem_claim/readme/DESCRIPTION.rst
  mgmtsystem_claim/readme/USAGE.rst
  mgmtsystem_claim/security/ir.model.access.csv
  mgmtsystem_claim/security/mgmtsystem_claim_security.xml
  mgmtsystem_claim/static/description/icon.png
  mgmtsystem_claim/tests/__init__.py
  mgmtsystem_claim/tests/test_create_claim.py
  mgmtsystem_claim/views/menus.xml
  mgmtsystem_claim/views/mgmtsystem_claim.xml
  mgmtsystem_claim/views/mgmtsystem_claim_stage.xml
  mgmtsystem_claim/views/res_partner_views.xml
  oca_dependencies.txt
Labels: approved, bot is merging ⏳

#345 [12.0][ADD] Add Non-Conformity Report
  mgmtsystem_nonconformity/README.rst
  mgmtsystem_nonconformity/__manifest__.py
  mgmtsystem_nonconformity/readme/CONTRIBUTORS.rst
  mgmtsystem_nonconformity/readme/CREDITS.rst
  mgmtsystem_nonconformity/readme/HISTORY.rst
  mgmtsystem_nonconformity/views/report_mgmtsystem_nonconformity.xml
Labels: approved, bot is merging ⏳, ready to merge

#352 Fix odoo warning with duplicate field string
  mgmtsystem/models/res_config.py
Labels: bot is merging ⏳
