Repository OCA/management-system, pull requests merged in 2020-03, with the labels that each got.

#292 [MIG] [13.0] mgmtsystem_audit
  mgmtsystem_audit/README.rst
  mgmtsystem_audit/__init__.py
  mgmtsystem_audit/__manifest__.py
  mgmtsystem_audit/data/audit_automated_actions.xml
  mgmtsystem_audit/data/audit_sequence.xml
  mgmtsystem_audit/demo/demo_audit.xml
  mgmtsystem_audit/i18n/am.po
  mgmtsystem_audit/i18n/ca.po
  mgmtsystem_audit/i18n/de.po
  mgmtsystem_audit/i18n/el_GR.po
  mgmtsystem_audit/i18n/es.po
  mgmtsystem_audit/i18n/es_CO.po
  mgmtsystem_audit/i18n/es_ES.po
  mgmtsystem_audit/i18n/fi.po
  mgmtsystem_audit/i18n/fr.po
  mgmtsystem_audit/i18n/gl.po
  mgmtsystem_audit/i18n/hr_HR.po
  mgmtsystem_audit/i18n/hu.po
  mgmtsystem_audit/i18n/it.po
  mgmtsystem_audit/i18n/lv.po
  mgmtsystem_audit/i18n/mgmtsystem_audit.pot
  mgmtsystem_audit/i18n/nb.po
  mgmtsystem_audit/i18n/nl.po
  mgmtsystem_audit/i18n/nl_NL.po
  mgmtsystem_audit/i18n/nn.po
  mgmtsystem_audit/i18n/pt.po
  mgmtsystem_audit/i18n/pt_BR.po
  mgmtsystem_audit/i18n/pt_PT.po
  mgmtsystem_audit/i18n/sl.po
  mgmtsystem_audit/i18n/sv.po
  mgmtsystem_audit/i18n/tr.po
  mgmtsystem_audit/i18n/vi.po
  mgmtsystem_audit/models/__init__.py
  mgmtsystem_audit/models/mgmtsystem_audit.py
  mgmtsystem_audit/models/mgmtsystem_nonconformity.py
  mgmtsystem_audit/models/mgmtsystem_verification_line.py
  mgmtsystem_audit/readme/CONFIGURE.rst
  mgmtsystem_audit/readme/CONTRIBUTORS.rst
  mgmtsystem_audit/readme/DESCRIPTION.rst
  mgmtsystem_audit/readme/USAGE.rst
  mgmtsystem_audit/report/audit.xml
  mgmtsystem_audit/report/mgmtsystem_audit_pivot.xml
  mgmtsystem_audit/report/report.xml
  mgmtsystem_audit/report/verification.xml
  mgmtsystem_audit/security/ir.model.access.csv
  mgmtsystem_audit/security/mgmtsystem_audit_security.xml
  mgmtsystem_audit/static/description/icon.png
  mgmtsystem_audit/static/description/index.html
  mgmtsystem_audit/tests/__init__.py
  mgmtsystem_audit/tests/test_audit.py
  mgmtsystem_audit/tests/test_copy_verification_lines.py
  mgmtsystem_audit/views/mgmtsystem_audit.xml
  mgmtsystem_audit/views/res_users.xml
  mgmtsystem_audit/wizard/__init__.py
  mgmtsystem_audit/wizard/copy_verification_lines.py
  mgmtsystem_audit/wizard/copy_verification_lines.xml
Labels: approved, migration, needs review, ready to merge

#306 mgmtsystem: Fix follow multicompany guide
  mgmtsystem/security/mgmtsystem_security.xml
Labels: approved

#307 [FIX] mgmtsystem_audit: number_of_nonconformities
  mgmtsystem_audit/models/mgmtsystem_audit.py
Labels: approved, bug, needs review

#308 [FIX] mgmtsystem_audit: number_of_nonconformities
  mgmtsystem_audit/models/mgmtsystem_audit.py
Labels: approved, bug, needs review
