Repository OCA/management-system, pull requests merged in 2021-05, with the labels that each got.

#375 [13.0][FIX] pre-commit mirrors-pylint dependencies error
  .pre-commit-config.yaml
Labels: approved, bot is merging ⏳, ready to merge

#351 [12.0] [ADD] new module mgmtsystem_extend_action_template
  mgmtsystem_action_template/README.rst
  mgmtsystem_action_template/__init__.py
  mgmtsystem_action_template/__manifest__.py
  mgmtsystem_action_template/i18n/it.po
  mgmtsystem_action_template/i18n/mgmtsystem_action_template.pot
  mgmtsystem_action_template/models/__init__.py
  mgmtsystem_action_template/models/mgmtsystem_action.py
  mgmtsystem_action_template/models/mgmtsystem_action_template.py
  mgmtsystem_action_template/readme/CONTRIBUTORS.rst
  mgmtsystem_action_template/readme/DESCRIPTION.rst
  mgmtsystem_action_template/readme/HISTORY.rst
  mgmtsystem_action_template/readme/USAGE.rst
  mgmtsystem_action_template/security/ir.model.access.csv
  mgmtsystem_action_template/static/description/icon.png
  mgmtsystem_action_template/static/description/index.html
  mgmtsystem_action_template/tests/__init__.py
  mgmtsystem_action_template/tests/test_action_template.py
  mgmtsystem_action_template/views/mgmtsystem_action_template.xml
  mgmtsystem_action_template/views/mgmtsystem_action_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#283 [11.0] [ADD] new module mgmtsystem_action_efficacy
  mgmtsystem_action_efficacy/README.rst
  mgmtsystem_action_efficacy/__init__.py
  mgmtsystem_action_efficacy/__manifest__.py
  mgmtsystem_action_efficacy/i18n/it.po
  mgmtsystem_action_efficacy/i18n/mgmtsystem_action_efficacy.pot
  mgmtsystem_action_efficacy/models/__init__.py
  mgmtsystem_action_efficacy/models/mgmtsystem_action_efficacy.py
  mgmtsystem_action_efficacy/readme/CONFIGURE.rst
  mgmtsystem_action_efficacy/readme/CONTRIBUTORS.rst
  mgmtsystem_action_efficacy/readme/DESCRIPTION.rst
  mgmtsystem_action_efficacy/readme/HISTORY.rst
  mgmtsystem_action_efficacy/readme/INSTALL.rst
  mgmtsystem_action_efficacy/readme/ROADMAP.rst
  mgmtsystem_action_efficacy/readme/USAGE.rst
  mgmtsystem_action_efficacy/static/description/icon.png
  mgmtsystem_action_efficacy/static/description/index.html
  mgmtsystem_action_efficacy/tests/__init__.py
  mgmtsystem_action_efficacy/tests/test_action_efficacy.py
  mgmtsystem_action_efficacy/views/mgmtsystem_action_views.xml
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#376 [ADD] Add chatter to mgmtsystem.review
  mgmtsystem_review/models/mgmtsystem_review.py
  mgmtsystem_review/views/mgmtsystem_review.xml
Labels: approved, bot is merging ⏳
