Repository OCA/management-system, pull requests merged in 2022-01, with the labels that each got.

#397 [FIX] mgmtsystem_hazard: XML attribute 'group' to 'groups'
  mgmtsystem_hazard/views/mgmtsystem_hazard.xml
Labels: approved, bot is merging ⏳

#393 [MIG][14.0] mgmtsystem_audit
  mgmtsystem_audit/README.rst
  mgmtsystem_audit/__init__.py
  mgmtsystem_audit/__manifest__.py
  mgmtsystem_audit/data/audit_automated_actions.xml
  mgmtsystem_audit/data/audit_sequence.xml
  mgmtsystem_audit/demo/demo_audit.xml
  mgmtsystem_audit/i18n/am.po
  mgmtsystem_audit/i18n/ca.po
  mgmtsystem_audit/i18n/de.po
  mgmtsystem_audit/i18n/el_GR.po
  mgmtsystem_audit/i18n/es.po
  mgmtsystem_audit/i18n/es_CO.po
  mgmtsystem_audit/i18n/es_ES.po
  mgmtsystem_audit/i18n/fi.po
  mgmtsystem_audit/i18n/fr.po
  mgmtsystem_audit/i18n/gl.po
  mgmtsystem_audit/i18n/hr_HR.po
  mgmtsystem_audit/i18n/hu.po
  mgmtsystem_audit/i18n/it.po
  mgmtsystem_audit/i18n/lv.po
  mgmtsystem_audit/i18n/mgmtsystem_audit.pot
  mgmtsystem_audit/i18n/nb.po
  mgmtsystem_audit/i18n/nl.po
  mgmtsystem_audit/i18n/nl_NL.po
  mgmtsystem_audit/i18n/nn.po
  mgmtsystem_audit/i18n/pt.po
  mgmtsystem_audit/i18n/pt_BR.po
  mgmtsystem_audit/i18n/pt_PT.po
  mgmtsystem_audit/i18n/sl.po
  mgmtsystem_audit/i18n/sv.po
  mgmtsystem_audit/i18n/tr.po
  mgmtsystem_audit/i18n/vi.po
  mgmtsystem_audit/models/__init__.py
  mgmtsystem_audit/models/mgmtsystem_audit.py
  mgmtsystem_audit/models/mgmtsystem_nonconformity.py
  mgmtsystem_audit/models/mgmtsystem_verification_line.py
  mgmtsystem_audit/readme/CONFIGURE.rst
  mgmtsystem_audit/readme/CONTRIBUTORS.rst
  mgmtsystem_audit/readme/DESCRIPTION.rst
  mgmtsystem_audit/readme/USAGE.rst
  mgmtsystem_audit/report/audit.xml
  mgmtsystem_audit/report/mgmtsystem_audit_pivot.xml
  mgmtsystem_audit/report/report.xml
  mgmtsystem_audit/report/verification.xml
  mgmtsystem_audit/security/ir.model.access.csv
  mgmtsystem_audit/security/mgmtsystem_audit_security.xml
  mgmtsystem_audit/static/description/icon.png
  mgmtsystem_audit/static/description/index.html
  mgmtsystem_audit/tests/__init__.py
  mgmtsystem_audit/tests/test_audit.py
  mgmtsystem_audit/tests/test_copy_verification_lines.py
  mgmtsystem_audit/views/mgmtsystem_audit.xml
  mgmtsystem_audit/views/res_users.xml
  mgmtsystem_audit/wizard/__init__.py
  mgmtsystem_audit/wizard/copy_verification_lines.py
  mgmtsystem_audit/wizard/copy_verification_lines.xml
  setup/mgmtsystem_audit/odoo/addons/mgmtsystem_audit
  setup/mgmtsystem_audit/setup.py
Labels: approved, bot is merging ⏳

#392 [MIG][14.0] document_page_environmental_aspect
  document_page_environmental_aspect/README.rst
  document_page_environmental_aspect/__init__.py
  document_page_environmental_aspect/__manifest__.py
  document_page_environmental_aspect/data/document_page.xml
  document_page_environmental_aspect/i18n/de.po
  document_page_environmental_aspect/i18n/document_page_environmental_aspect.pot
  document_page_environmental_aspect/i18n/es_CL.po
  document_page_environmental_aspect/i18n/fr.po
  document_page_environmental_aspect/i18n/nb.po
  document_page_environmental_aspect/i18n/pt.po
  document_page_environmental_aspect/i18n/pt_BR.po
  document_page_environmental_aspect/i18n/sl.po
  document_page_environmental_aspect/i18n/sv.po
  document_page_environmental_aspect/i18n/vi.po
  document_page_environmental_aspect/readme/CONFIGURE.rst
  document_page_environmental_aspect/readme/CONTRIBUTORS.rst
  document_page_environmental_aspect/readme/DESCRIPTION.rst
  document_page_environmental_aspect/readme/USAGE.rst
  document_page_environmental_aspect/static/description/icon.png
  document_page_environmental_aspect/static/description/index.html
  document_page_environmental_aspect/views/document_page.xml
  setup/document_page_environmental_aspect/odoo/addons/document_page_environmental_aspect
  setup/document_page_environmental_aspect/setup.py
Labels: approved, bot is merging ⏳

#390 [MIG] mgmtsystem_nonconformity_hr: Migration to 14.0
  mgmtsystem_nonconformity_hr/README.rst
  mgmtsystem_nonconformity_hr/__init__.py
  mgmtsystem_nonconformity_hr/__manifest__.py
  mgmtsystem_nonconformity_hr/i18n/it.po
  mgmtsystem_nonconformity_hr/i18n/mgmtsystem_extended_hr.pot
  mgmtsystem_nonconformity_hr/i18n/mgmtsystem_nonconformity_hr.pot
  mgmtsystem_nonconformity_hr/i18n/pt.po
  mgmtsystem_nonconformity_hr/models/__init__.py
  mgmtsystem_nonconformity_hr/models/mgmtsystem_nonconformity_hr.py
  mgmtsystem_nonconformity_hr/readme/CONTRIBUTORS.rst
  mgmtsystem_nonconformity_hr/readme/DESCRIPTION.rst
  mgmtsystem_nonconformity_hr/readme/HISTORY.rst
  mgmtsystem_nonconformity_hr/readme/USAGE.rst
  mgmtsystem_nonconformity_hr/static/description/icon.png
  mgmtsystem_nonconformity_hr/static/description/index.html
  mgmtsystem_nonconformity_hr/views/mgmtsystem_nonconformity_views.xml
  setup/mgmtsystem_nonconformity_hr/odoo/addons/mgmtsystem_nonconformity_hr
  setup/mgmtsystem_nonconformity_hr/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#395 [MIG][14.0] mgmtsystem_hazard_risk
  mgmtsystem_hazard_risk/README.rst
  mgmtsystem_hazard_risk/__init__.py
  mgmtsystem_hazard_risk/__manifest__.py
  mgmtsystem_hazard_risk/data/mgmtsystem_hazard_risk_computation.xml
  mgmtsystem_hazard_risk/data/mgmtsystem_hazard_risk_type.xml
  mgmtsystem_hazard_risk/i18n/de.po
  mgmtsystem_hazard_risk/i18n/es.po
  mgmtsystem_hazard_risk/i18n/fr.po
  mgmtsystem_hazard_risk/i18n/hr.po
  mgmtsystem_hazard_risk/i18n/id.po
  mgmtsystem_hazard_risk/i18n/mgmtsystem_hazard_risk.pot
  mgmtsystem_hazard_risk/i18n/nb.po
  mgmtsystem_hazard_risk/i18n/pt_BR.po
  mgmtsystem_hazard_risk/i18n/sl.po
  mgmtsystem_hazard_risk/i18n/vi.po
  mgmtsystem_hazard_risk/models/__init__.py
  mgmtsystem_hazard_risk/models/common.py
  mgmtsystem_hazard_risk/models/mgmtsystem_hazard.py
  mgmtsystem_hazard_risk/models/mgmtsystem_hazard_residual_risk.py
  mgmtsystem_hazard_risk/models/mgmtsystem_hazard_risk_computation.py
  mgmtsystem_hazard_risk/models/mgmtsystem_hazard_risk_type.py
  mgmtsystem_hazard_risk/models/res_company.py
  mgmtsystem_hazard_risk/models/res_config_settings.py
  mgmtsystem_hazard_risk/readme/CONFIGURE.rst
  mgmtsystem_hazard_risk/readme/CONTRIBUTORS.rst
  mgmtsystem_hazard_risk/readme/DESCRIPTION.rst
  mgmtsystem_hazard_risk/security/ir.model.access.csv
  mgmtsystem_hazard_risk/security/mgmtsystem_hazard_security.xml
  mgmtsystem_hazard_risk/static/description/icon.png
  mgmtsystem_hazard_risk/static/description/index.html
  mgmtsystem_hazard_risk/tests/__init__.py
  mgmtsystem_hazard_risk/tests/test_mgmtsystem_hazard.py
  mgmtsystem_hazard_risk/views/mgmtsystem_hazard.xml
  mgmtsystem_hazard_risk/views/mgmtsystem_hazard_residual_risk.xml
  mgmtsystem_hazard_risk/views/mgmtsystem_hazard_risk_computation.xml
  mgmtsystem_hazard_risk/views/mgmtsystem_hazard_risk_type.xml
  mgmtsystem_hazard_risk/views/res_config_settings_views.xml
  setup/mgmtsystem_hazard_risk/odoo/addons/mgmtsystem_hazard_risk
  setup/mgmtsystem_hazard_risk/setup.py
Labels: approved, bot is merging ⏳

#396 [MIG][14.0] mgmtsystem_claim
  mgmtsystem_claim/README.rst
  mgmtsystem_claim/__init__.py
  mgmtsystem_claim/__manifest__.py
  mgmtsystem_claim/data/automated_reminder.xml
  mgmtsystem_claim/data/claim_sequence.xml
  mgmtsystem_claim/data/email_template.xml
  mgmtsystem_claim/data/mgmtsystem_claim_stage.xml
  mgmtsystem_claim/i18n/de.po
  mgmtsystem_claim/i18n/es.po
  mgmtsystem_claim/i18n/fr.po
  mgmtsystem_claim/i18n/mgmtsystem_claim.pot
  mgmtsystem_claim/i18n/nb.po
  mgmtsystem_claim/i18n/pt_BR.po
  mgmtsystem_claim/i18n/sl.po
  mgmtsystem_claim/i18n/sv.po
  mgmtsystem_claim/i18n/vi.po
  mgmtsystem_claim/models/__init__.py
  mgmtsystem_claim/models/mgmtsystem_claim.py
  mgmtsystem_claim/models/mgmtsystem_claim_stage.py
  mgmtsystem_claim/models/res_partner.py
  mgmtsystem_claim/readme/CONFIGURE.rst
  mgmtsystem_claim/readme/CONTRIBUTORS.rst
  mgmtsystem_claim/readme/DESCRIPTION.rst
  mgmtsystem_claim/readme/USAGE.rst
  mgmtsystem_claim/security/ir.model.access.csv
  mgmtsystem_claim/security/mgmtsystem_claim_security.xml
  mgmtsystem_claim/static/description/icon.png
  mgmtsystem_claim/static/description/index.html
  mgmtsystem_claim/tests/__init__.py
  mgmtsystem_claim/tests/test_create_claim.py
  mgmtsystem_claim/views/menus.xml
  mgmtsystem_claim/views/mgmtsystem_claim.xml
  mgmtsystem_claim/views/mgmtsystem_claim_stage.xml
  mgmtsystem_claim/views/res_partner_views.xml
  setup/mgmtsystem_claim/odoo/addons/mgmtsystem_claim
  setup/mgmtsystem_claim/setup.py
Labels: bot is merging ⏳

#394 [MIG][14.0] mgmtsystem_quality
  mgmtsystem_quality/README.rst
  mgmtsystem_quality/__init__.py
  mgmtsystem_quality/__manifest__.py
  mgmtsystem_quality/data/mgmtsystem_system.xml
  mgmtsystem_quality/i18n/de.po
  mgmtsystem_quality/i18n/fr.po
  mgmtsystem_quality/i18n/mgmtsystem_quality.pot
  mgmtsystem_quality/i18n/nb.po
  mgmtsystem_quality/i18n/pt_BR.po
  mgmtsystem_quality/i18n/sv.po
  mgmtsystem_quality/i18n/vi.po
  mgmtsystem_quality/readme/CONFIGURE.rst
  mgmtsystem_quality/readme/CONTRIBUTORS.rst
  mgmtsystem_quality/readme/DESCRIPTION.rst
  mgmtsystem_quality/readme/ROADMAP.rst
  mgmtsystem_quality/readme/USAGE.rst
  mgmtsystem_quality/static/description/icon.png
  mgmtsystem_quality/static/description/index.html
  setup/mgmtsystem_quality/odoo/addons/mgmtsystem_quality
  setup/mgmtsystem_quality/setup.py
Labels: approved, bot is merging ⏳

#335 [12.0] [MIG] mgmtsystem_nonconformity_mrp
  mgmtsystem_nonconformity_mrp/README.rst
  mgmtsystem_nonconformity_mrp/__init__.py
  mgmtsystem_nonconformity_mrp/__manifest__.py
  mgmtsystem_nonconformity_mrp/i18n/it.po
  mgmtsystem_nonconformity_mrp/i18n/mgmtsystem_nonconformity_mrp.pot
  mgmtsystem_nonconformity_mrp/models/__init__.py
  mgmtsystem_nonconformity_mrp/models/mgmtsystem_nonconformity_mrp.py
  mgmtsystem_nonconformity_mrp/readme/CONFIGURE.rst
  mgmtsystem_nonconformity_mrp/readme/CONTRIBUTORS.rst
  mgmtsystem_nonconformity_mrp/readme/DESCRIPTION.rst
  mgmtsystem_nonconformity_mrp/readme/HISTORY.rst
  mgmtsystem_nonconformity_mrp/readme/USAGE.rst
  mgmtsystem_nonconformity_mrp/static/description/icon.png
  mgmtsystem_nonconformity_mrp/static/description/index.html
  mgmtsystem_nonconformity_mrp/views/mgmtsystem_nonconformity_views.xml
Labels: approved, bot is merging ⏳

#398 [MIG][14.0] document_page_environment_manual
  document_page_environment_manual/README.rst
  document_page_environment_manual/__init__.py
  document_page_environment_manual/__manifest__.py
  document_page_environment_manual/data/document_page_environment_manual.xml
  document_page_environment_manual/i18n/de.po
  document_page_environment_manual/i18n/document_page_environment_manual.pot
  document_page_environment_manual/i18n/fr.po
  document_page_environment_manual/i18n/nb.po
  document_page_environment_manual/i18n/pt_BR.po
  document_page_environment_manual/i18n/sl.po
  document_page_environment_manual/i18n/sv.po
  document_page_environment_manual/i18n/vi.po
  document_page_environment_manual/readme/CONTRIBUTORS.rst
  document_page_environment_manual/readme/DESCRIPTION.rst
  document_page_environment_manual/readme/USAGE.rst
  document_page_environment_manual/static/description/icon.png
  document_page_environment_manual/static/description/index.html
  setup/document_page_environment_manual/odoo/addons/document_page_environment_manual
  setup/document_page_environment_manual/setup.py
Labels: approved, bot is merging ⏳

#401 [13.0][IMP] mgmtsystem_nonconformity: Add button_box div to nonconformity form view to improve inheritance.
  mgmtsystem_nonconformity/views/mgmtsystem_nonconformity.xml
Labels: approved, bot is merging ⏳

#402 [14.0][IMP] mgmtsystem_nonconformity: Add button_box div to nonconformity form view to improve inheritance.
  mgmtsystem_nonconformity/views/mgmtsystem_nonconformity.xml
Labels: approved, bot is merging ⏳
