Repository OCA/management-system, pull requests merged in 2022-05, with the labels that each got.

#348 [12.0] [ADD] new module mgmtsystem_partner
  mgmtsystem_partner/README.rst
  mgmtsystem_partner/__init__.py
  mgmtsystem_partner/__manifest__.py
  mgmtsystem_partner/models/__init__.py
  mgmtsystem_partner/models/mgmtsystem_partner.py
  mgmtsystem_partner/readme/CONTRIBUTORS.rst
  mgmtsystem_partner/readme/DESCRIPTION.rst
  mgmtsystem_partner/readme/HISTORY.rst
  mgmtsystem_partner/readme/USAGE.rst
  mgmtsystem_partner/static/description/icon.png
  mgmtsystem_partner/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#284 [11.0] [ADD] new module mgmtsystem_nonconformity_type
  mgmtsystem_nonconformity_type/README.rst
  mgmtsystem_nonconformity_type/__init__.py
  mgmtsystem_nonconformity_type/__manifest__.py
  mgmtsystem_nonconformity_type/data/mgmtsystem_nonconformity_mail_data.xml
  mgmtsystem_nonconformity_type/i18n/it.po
  mgmtsystem_nonconformity_type/i18n/mgmtsystem_nonconformity_type.pot
  mgmtsystem_nonconformity_type/models/__init__.py
  mgmtsystem_nonconformity_type/models/mgmtsystem_nonconformity_type.py
  mgmtsystem_nonconformity_type/readme/CONTRIBUTORS.rst
  mgmtsystem_nonconformity_type/readme/DESCRIPTION.rst
  mgmtsystem_nonconformity_type/readme/HISTORY.rst
  mgmtsystem_nonconformity_type/readme/ROADMAP.rst
  mgmtsystem_nonconformity_type/readme/USAGE.rst
  mgmtsystem_nonconformity_type/static/description/icon.png
  mgmtsystem_nonconformity_type/static/description/index.html
  mgmtsystem_nonconformity_type/views/mgmtsystem_nonconformity_views.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#406 15.0 mig document page procedure
  document_page_procedure/README.rst
  document_page_procedure/__init__.py
  document_page_procedure/__manifest__.py
  document_page_procedure/data/document_page_procedure.xml
  document_page_procedure/demo/document_page_procedure.xml
  document_page_procedure/i18n/de.po
  document_page_procedure/i18n/document_page_procedure.pot
  document_page_procedure/i18n/es.po
  document_page_procedure/i18n/es_CO.po
  document_page_procedure/i18n/fr.po
  document_page_procedure/i18n/hr.po
  document_page_procedure/i18n/hr_HR.po
  document_page_procedure/i18n/hu.po
  document_page_procedure/i18n/it.po
  document_page_procedure/i18n/nb.po
  document_page_procedure/i18n/nl_NL.po
  document_page_procedure/i18n/pt.po
  document_page_procedure/i18n/pt_BR.po
  document_page_procedure/i18n/sl.po
  document_page_procedure/i18n/sv.po
  document_page_procedure/i18n/vi.po
  document_page_procedure/readme/CONFIGURE.rst
  document_page_procedure/readme/CONTRIBUTORS.rst
  document_page_procedure/readme/CREDITS.rst
  document_page_procedure/readme/DESCRIPTION.rst
  document_page_procedure/static/description/icon.png
  document_page_procedure/static/description/index.html
  document_page_procedure/views/document_page_procedure.xml
  setup/document_page_procedure/odoo/addons/document_page_procedure
  setup/document_page_procedure/setup.py
Labels: bot is merging ⏳

#407 15.0 mig mgmtsystem manual
  mgmtsystem_manual/README.rst
  mgmtsystem_manual/__init__.py
  mgmtsystem_manual/__manifest__.py
  mgmtsystem_manual/data/mgmtsystem_manual.xml
  mgmtsystem_manual/i18n/de.po
  mgmtsystem_manual/i18n/es.po
  mgmtsystem_manual/i18n/fr.po
  mgmtsystem_manual/i18n/hr_HR.po
  mgmtsystem_manual/i18n/it.po
  mgmtsystem_manual/i18n/lv.po
  mgmtsystem_manual/i18n/mgmtsystem_manual.pot
  mgmtsystem_manual/i18n/nb.po
  mgmtsystem_manual/i18n/nl_NL.po
  mgmtsystem_manual/i18n/nn.po
  mgmtsystem_manual/i18n/pt_BR.po
  mgmtsystem_manual/i18n/sl.po
  mgmtsystem_manual/i18n/sv.po
  mgmtsystem_manual/i18n/th.po
  mgmtsystem_manual/i18n/vi.po
  mgmtsystem_manual/models/__init__.py
  mgmtsystem_manual/models/mgmtsystem_manual.py
  mgmtsystem_manual/readme/CONFIGURE.rst
  mgmtsystem_manual/readme/CONTRIBUTORS.rst
  mgmtsystem_manual/readme/CREDITS.rst
  mgmtsystem_manual/readme/DESCRIPTION.rst
  mgmtsystem_manual/readme/HISTORY.rst
  mgmtsystem_manual/readme/INSTALL.rst
  mgmtsystem_manual/readme/USAGE.rst
  mgmtsystem_manual/static/description/icon.png
  mgmtsystem_manual/static/description/index.html
  mgmtsystem_manual/views/document_page.xml
  mgmtsystem_manual/views/mgmtsystem_manual.xml
  setup/mgmtsystem_manual/odoo/addons/mgmtsystem_manual
  setup/mgmtsystem_manual/setup.py
Labels: bot is merging ⏳

#412 15.0 mig document page environmental aspect
  document_page_environmental_aspect/README.rst
  document_page_environmental_aspect/__init__.py
  document_page_environmental_aspect/__manifest__.py
  document_page_environmental_aspect/data/document_page.xml
  document_page_environmental_aspect/i18n/de.po
  document_page_environmental_aspect/i18n/document_page_environmental_aspect.pot
  document_page_environmental_aspect/i18n/es_CL.po
  document_page_environmental_aspect/i18n/fr.po
  document_page_environmental_aspect/i18n/nb.po
  document_page_environmental_aspect/i18n/pt.po
  document_page_environmental_aspect/i18n/pt_BR.po
  document_page_environmental_aspect/i18n/sl.po
  document_page_environmental_aspect/i18n/sv.po
  document_page_environmental_aspect/i18n/vi.po
  document_page_environmental_aspect/readme/CONFIGURE.rst
  document_page_environmental_aspect/readme/CONTRIBUTORS.rst
  document_page_environmental_aspect/readme/DESCRIPTION.rst
  document_page_environmental_aspect/readme/USAGE.rst
  document_page_environmental_aspect/static/description/icon.png
  document_page_environmental_aspect/static/description/index.html
  document_page_environmental_aspect/views/document_page.xml
  setup/document_page_environmental_aspect/odoo/addons/document_page_environmental_aspect
  setup/document_page_environmental_aspect/setup.py
Labels: bot is merging ⏳

#413 15.0 mig mgmtsystem claim
  mgmtsystem_claim/README.rst
  mgmtsystem_claim/__init__.py
  mgmtsystem_claim/__manifest__.py
  mgmtsystem_claim/data/automated_reminder.xml
  mgmtsystem_claim/data/claim_sequence.xml
  mgmtsystem_claim/data/email_template.xml
  mgmtsystem_claim/data/mgmtsystem_claim_stage.xml
  mgmtsystem_claim/i18n/de.po
  mgmtsystem_claim/i18n/es.po
  mgmtsystem_claim/i18n/fr.po
  mgmtsystem_claim/i18n/mgmtsystem_claim.pot
  mgmtsystem_claim/i18n/nb.po
  mgmtsystem_claim/i18n/pt_BR.po
  mgmtsystem_claim/i18n/sl.po
  mgmtsystem_claim/i18n/sv.po
  mgmtsystem_claim/i18n/vi.po
  mgmtsystem_claim/models/__init__.py
  mgmtsystem_claim/models/mgmtsystem_claim.py
  mgmtsystem_claim/models/mgmtsystem_claim_stage.py
  mgmtsystem_claim/models/res_partner.py
  mgmtsystem_claim/readme/CONFIGURE.rst
  mgmtsystem_claim/readme/CONTRIBUTORS.rst
  mgmtsystem_claim/readme/DESCRIPTION.rst
  mgmtsystem_claim/readme/USAGE.rst
  mgmtsystem_claim/security/ir.model.access.csv
  mgmtsystem_claim/security/mgmtsystem_claim_security.xml
  mgmtsystem_claim/static/description/icon.png
  mgmtsystem_claim/static/description/index.html
  mgmtsystem_claim/tests/__init__.py
  mgmtsystem_claim/tests/test_create_claim.py
  mgmtsystem_claim/views/menus.xml
  mgmtsystem_claim/views/mgmtsystem_claim.xml
  mgmtsystem_claim/views/mgmtsystem_claim_stage.xml
  mgmtsystem_claim/views/res_partner_views.xml
  setup/mgmtsystem_claim/odoo/addons/mgmtsystem_claim
  setup/mgmtsystem_claim/setup.py
Labels: bot is merging ⏳

#416 15.0 mig document page environment manual
  document_page_environment_manual/README.rst
  document_page_environment_manual/__init__.py
  document_page_environment_manual/__manifest__.py
  document_page_environment_manual/data/document_page_environment_manual.xml
  document_page_environment_manual/i18n/de.po
  document_page_environment_manual/i18n/document_page_environment_manual.pot
  document_page_environment_manual/i18n/fr.po
  document_page_environment_manual/i18n/nb.po
  document_page_environment_manual/i18n/pt_BR.po
  document_page_environment_manual/i18n/sl.po
  document_page_environment_manual/i18n/sv.po
  document_page_environment_manual/i18n/vi.po
  document_page_environment_manual/readme/CONTRIBUTORS.rst
  document_page_environment_manual/readme/DESCRIPTION.rst
  document_page_environment_manual/readme/USAGE.rst
  document_page_environment_manual/static/description/icon.png
  document_page_environment_manual/static/description/index.html
  setup/document_page_environment_manual/odoo/addons/document_page_environment_manual
  setup/document_page_environment_manual/setup.py
Labels: bot is merging ⏳

#410 15.0 mig document page work instruction
  document_page_work_instruction/README.rst
  document_page_work_instruction/__init__.py
  document_page_work_instruction/__manifest__.py
  document_page_work_instruction/data/document_page.xml
  document_page_work_instruction/i18n/de.po
  document_page_work_instruction/i18n/document_page_work_instruction.pot
  document_page_work_instruction/i18n/es.po
  document_page_work_instruction/i18n/es_CO.po
  document_page_work_instruction/i18n/fr.po
  document_page_work_instruction/i18n/hr_HR.po
  document_page_work_instruction/i18n/it.po
  document_page_work_instruction/i18n/nb.po
  document_page_work_instruction/i18n/nl_NL.po
  document_page_work_instruction/i18n/nn.po
  document_page_work_instruction/i18n/no.po
  document_page_work_instruction/i18n/pt_BR.po
  document_page_work_instruction/i18n/sl.po
  document_page_work_instruction/i18n/vi.po
  document_page_work_instruction/readme/CONFIGURE.rst
  document_page_work_instruction/readme/CONTRIBUTORS.rst
  document_page_work_instruction/readme/CREDITS.rst
  document_page_work_instruction/readme/DESCRIPTION.rst
  document_page_work_instruction/static/description/icon.png
  document_page_work_instruction/static/description/index.html
  document_page_work_instruction/views/document_page_work_instructions.xml
  setup/document_page_work_instruction/odoo/addons/document_page_work_instruction
  setup/document_page_work_instruction/setup.py
Labels: bot is merging ⏳

#415 15.0 mig mgmtsystem survey
  mgmtsystem_survey/README.rst
  mgmtsystem_survey/__init__.py
  mgmtsystem_survey/__manifest__.py
  mgmtsystem_survey/i18n/de.po
  mgmtsystem_survey/i18n/es.po
  mgmtsystem_survey/i18n/es_CO.po
  mgmtsystem_survey/i18n/fi.po
  mgmtsystem_survey/i18n/fr.po
  mgmtsystem_survey/i18n/hr_HR.po
  mgmtsystem_survey/i18n/hu.po
  mgmtsystem_survey/i18n/it.po
  mgmtsystem_survey/i18n/lv.po
  mgmtsystem_survey/i18n/mgmtsystem_survey.pot
  mgmtsystem_survey/i18n/nb.po
  mgmtsystem_survey/i18n/nn.po
  mgmtsystem_survey/i18n/pt.po
  mgmtsystem_survey/i18n/pt_BR.po
  mgmtsystem_survey/i18n/sl.po
  mgmtsystem_survey/i18n/sv.po
  mgmtsystem_survey/i18n/th.po
  mgmtsystem_survey/i18n/tr.po
  mgmtsystem_survey/i18n/vi.po
  mgmtsystem_survey/models/__init__.py
  mgmtsystem_survey/readme/CONFIGURE.rst
  mgmtsystem_survey/readme/CONTRIBUTORS.rst
  mgmtsystem_survey/readme/CREDITS.rst
  mgmtsystem_survey/readme/DESCRIPTION.rst
  mgmtsystem_survey/readme/USAGE.rst
  mgmtsystem_survey/static/description/icon.png
  mgmtsystem_survey/static/description/index.html
  mgmtsystem_survey/views/survey_survey.xml
  setup/mgmtsystem_survey/odoo/addons/mgmtsystem_survey
  setup/mgmtsystem_survey/setup.py
Labels: bot is merging ⏳

#421 15.0 mig mgmtsystem review
  mgmtsystem_review/README.rst
  mgmtsystem_review/__init__.py
  mgmtsystem_review/__manifest__.py
  mgmtsystem_review/data/ir_sequence.xml
  mgmtsystem_review/i18n/am.po
  mgmtsystem_review/i18n/ca.po
  mgmtsystem_review/i18n/de.po
  mgmtsystem_review/i18n/el_GR.po
  mgmtsystem_review/i18n/es.po
  mgmtsystem_review/i18n/es_CO.po
  mgmtsystem_review/i18n/es_ES.po
  mgmtsystem_review/i18n/fi.po
  mgmtsystem_review/i18n/fr.po
  mgmtsystem_review/i18n/gl.po
  mgmtsystem_review/i18n/hr_HR.po
  mgmtsystem_review/i18n/hu.po
  mgmtsystem_review/i18n/it.po
  mgmtsystem_review/i18n/lv.po
  mgmtsystem_review/i18n/mgmtsystem_review.pot
  mgmtsystem_review/i18n/nb.po
  mgmtsystem_review/i18n/nl.po
  mgmtsystem_review/i18n/nl_NL.po
  mgmtsystem_review/i18n/nn.po
  mgmtsystem_review/i18n/pt.po
  mgmtsystem_review/i18n/pt_BR.po
  mgmtsystem_review/i18n/pt_PT.po
  mgmtsystem_review/i18n/sl.po
  mgmtsystem_review/i18n/sv.po
  mgmtsystem_review/i18n/th.po
  mgmtsystem_review/i18n/tr.po
  mgmtsystem_review/i18n/vi.po
  mgmtsystem_review/models/__init__.py
  mgmtsystem_review/models/mgmtsystem_review.py
  mgmtsystem_review/models/mgmtsystem_review_line.py
  mgmtsystem_review/readme/CONTRIBUTORS.rst
  mgmtsystem_review/readme/CREDITS.rst
  mgmtsystem_review/readme/DESCRIPTION.rst
  mgmtsystem_review/readme/USAGE.rst
  mgmtsystem_review/report/report.xml
  mgmtsystem_review/report/review.xml
  mgmtsystem_review/security/ir.model.access.csv
  mgmtsystem_review/security/mgmtsystem_review_security.xml
  mgmtsystem_review/static/description/icon.png
  mgmtsystem_review/static/description/index.html
  mgmtsystem_review/tests/__init__.py
  mgmtsystem_review/tests/test_create_review.py
  mgmtsystem_review/views/mgmtsystem_review.xml
  mgmtsystem_review/views/res_users.xml
  setup/mgmtsystem_review/odoo/addons/mgmtsystem_review
  setup/mgmtsystem_review/setup.py
Labels: bot is merging ⏳

#422 15.0 mig mgmtsystem hazard risk
  mgmtsystem_hazard_risk/README.rst
  mgmtsystem_hazard_risk/__init__.py
  mgmtsystem_hazard_risk/__manifest__.py
  mgmtsystem_hazard_risk/data/mgmtsystem_hazard_risk_computation.xml
  mgmtsystem_hazard_risk/data/mgmtsystem_hazard_risk_type.xml
  mgmtsystem_hazard_risk/i18n/de.po
  mgmtsystem_hazard_risk/i18n/es.po
  mgmtsystem_hazard_risk/i18n/fr.po
  mgmtsystem_hazard_risk/i18n/hr.po
  mgmtsystem_hazard_risk/i18n/id.po
  mgmtsystem_hazard_risk/i18n/mgmtsystem_hazard_risk.pot
  mgmtsystem_hazard_risk/i18n/nb.po
  mgmtsystem_hazard_risk/i18n/pt_BR.po
  mgmtsystem_hazard_risk/i18n/sl.po
  mgmtsystem_hazard_risk/i18n/vi.po
  mgmtsystem_hazard_risk/models/__init__.py
  mgmtsystem_hazard_risk/models/common.py
  mgmtsystem_hazard_risk/models/mgmtsystem_hazard.py
  mgmtsystem_hazard_risk/models/mgmtsystem_hazard_residual_risk.py
  mgmtsystem_hazard_risk/models/mgmtsystem_hazard_risk_computation.py
  mgmtsystem_hazard_risk/models/mgmtsystem_hazard_risk_type.py
  mgmtsystem_hazard_risk/models/res_company.py
  mgmtsystem_hazard_risk/models/res_config_settings.py
  mgmtsystem_hazard_risk/readme/CONFIGURE.rst
  mgmtsystem_hazard_risk/readme/CONTRIBUTORS.rst
  mgmtsystem_hazard_risk/readme/DESCRIPTION.rst
  mgmtsystem_hazard_risk/security/ir.model.access.csv
  mgmtsystem_hazard_risk/security/mgmtsystem_hazard_security.xml
  mgmtsystem_hazard_risk/static/description/icon.png
  mgmtsystem_hazard_risk/static/description/index.html
  mgmtsystem_hazard_risk/tests/__init__.py
  mgmtsystem_hazard_risk/tests/test_mgmtsystem_hazard.py
  mgmtsystem_hazard_risk/views/mgmtsystem_hazard.xml
  mgmtsystem_hazard_risk/views/mgmtsystem_hazard_residual_risk.xml
  mgmtsystem_hazard_risk/views/mgmtsystem_hazard_risk_computation.xml
  mgmtsystem_hazard_risk/views/mgmtsystem_hazard_risk_type.xml
  mgmtsystem_hazard_risk/views/res_config_settings_views.xml
  setup/mgmtsystem_hazard_risk/odoo/addons/mgmtsystem_hazard_risk
  setup/mgmtsystem_hazard_risk/setup.py
Labels: bot is merging ⏳

#423 15.0 mig mgmtsystem nonconformity hr
  mgmtsystem_nonconformity_hr/README.rst
  mgmtsystem_nonconformity_hr/__init__.py
  mgmtsystem_nonconformity_hr/__manifest__.py
  mgmtsystem_nonconformity_hr/i18n/it.po
  mgmtsystem_nonconformity_hr/i18n/mgmtsystem_extended_hr.pot
  mgmtsystem_nonconformity_hr/i18n/mgmtsystem_nonconformity_hr.pot
  mgmtsystem_nonconformity_hr/i18n/pt.po
  mgmtsystem_nonconformity_hr/models/__init__.py
  mgmtsystem_nonconformity_hr/models/mgmtsystem_nonconformity_hr.py
  mgmtsystem_nonconformity_hr/readme/CONTRIBUTORS.rst
  mgmtsystem_nonconformity_hr/readme/DESCRIPTION.rst
  mgmtsystem_nonconformity_hr/readme/HISTORY.rst
  mgmtsystem_nonconformity_hr/readme/USAGE.rst
  mgmtsystem_nonconformity_hr/static/description/icon.png
  mgmtsystem_nonconformity_hr/static/description/index.html
  mgmtsystem_nonconformity_hr/views/mgmtsystem_nonconformity_views.xml
  setup/mgmtsystem_nonconformity_hr/odoo/addons/mgmtsystem_nonconformity_hr
  setup/mgmtsystem_nonconformity_hr/setup.py
Labels: bot is merging ⏳

#399 [MIG][13.0] mgmtsystem_nonconformity_product
  mgmtsystem_nonconformity_product/README.rst
  mgmtsystem_nonconformity_product/__init__.py
  mgmtsystem_nonconformity_product/__manifest__.py
  mgmtsystem_nonconformity_product/i18n/it.po
  mgmtsystem_nonconformity_product/i18n/mgmtsystem_nonconformity_product.pot
  mgmtsystem_nonconformity_product/i18n/pt_BR.po
  mgmtsystem_nonconformity_product/models/__init__.py
  mgmtsystem_nonconformity_product/models/mgmtsystem_nonconformity_product.py
  mgmtsystem_nonconformity_product/readme/CONTRIBUTORS.rst
  mgmtsystem_nonconformity_product/readme/DESCRIPTION.rst
  mgmtsystem_nonconformity_product/readme/HISTORY.rst
  mgmtsystem_nonconformity_product/readme/USAGE.rst
  mgmtsystem_nonconformity_product/static/description/icon.png
  mgmtsystem_nonconformity_product/static/description/index.html
  mgmtsystem_nonconformity_product/views/mgmtsystem_nonconformity_views.xml
  setup/mgmtsystem_nonconformity_product/odoo/addons/mgmtsystem_nonconformity_product
  setup/mgmtsystem_nonconformity_product/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#349 [12.0] [ADD] new module mgmtsystem_nonconformity_type
  mgmtsystem_nonconformity_type/README.rst
  mgmtsystem_nonconformity_type/__init__.py
  mgmtsystem_nonconformity_type/__manifest__.py
  mgmtsystem_nonconformity_type/data/mgmtsystem_nonconformity_mail_data.xml
  mgmtsystem_nonconformity_type/i18n/it.po
  mgmtsystem_nonconformity_type/i18n/mgmtsystem_nonconformity_type.pot
  mgmtsystem_nonconformity_type/models/__init__.py
  mgmtsystem_nonconformity_type/models/mgmtsystem_nonconformity_type.py
  mgmtsystem_nonconformity_type/readme/CONTRIBUTORS.rst
  mgmtsystem_nonconformity_type/readme/DESCRIPTION.rst
  mgmtsystem_nonconformity_type/readme/HISTORY.rst
  mgmtsystem_nonconformity_type/readme/ROADMAP.rst
  mgmtsystem_nonconformity_type/readme/USAGE.rst
  mgmtsystem_nonconformity_type/static/description/icon.png
  mgmtsystem_nonconformity_type/static/description/index.html
  mgmtsystem_nonconformity_type/tests/__init__.py
  mgmtsystem_nonconformity_type/tests/test_nonconfrmity_type.py
  mgmtsystem_nonconformity_type/views/mgmtsystem_nonconformity_views.xml
  setup/mgmtsystem_nonconformity_type/odoo/addons/mgmtsystem_nonconformity_type
  setup/mgmtsystem_nonconformity_type/setup.py
Labels: approved, bot is merging ⏳

#400 [MIG][13.0] mgmtsystem_action_template
  mgmtsystem_action_template/README.rst
  mgmtsystem_action_template/__init__.py
  mgmtsystem_action_template/__manifest__.py
  mgmtsystem_action_template/i18n/it.po
  mgmtsystem_action_template/i18n/mgmtsystem_action_template.pot
  mgmtsystem_action_template/models/__init__.py
  mgmtsystem_action_template/models/mgmtsystem_action.py
  mgmtsystem_action_template/models/mgmtsystem_action_template.py
  mgmtsystem_action_template/readme/CONTRIBUTORS.rst
  mgmtsystem_action_template/readme/DESCRIPTION.rst
  mgmtsystem_action_template/readme/HISTORY.rst
  mgmtsystem_action_template/readme/USAGE.rst
  mgmtsystem_action_template/security/ir.model.access.csv
  mgmtsystem_action_template/static/description/icon.png
  mgmtsystem_action_template/static/description/index.html
  mgmtsystem_action_template/tests/__init__.py
  mgmtsystem_action_template/tests/test_action_template.py
  mgmtsystem_action_template/views/mgmtsystem_action_template.xml
  mgmtsystem_action_template/views/mgmtsystem_action_views.xml
  setup/mgmtsystem_action_template/odoo/addons/mgmtsystem_action_template
  setup/mgmtsystem_action_template/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#428 [14.0][MIG] mgmtsystem nonconformity mrp
  mgmtsystem_nonconformity_mrp/README.rst
  mgmtsystem_nonconformity_mrp/__init__.py
  mgmtsystem_nonconformity_mrp/__manifest__.py
  mgmtsystem_nonconformity_mrp/i18n/it.po
  mgmtsystem_nonconformity_mrp/i18n/mgmtsystem_extended_mrp.pot
  mgmtsystem_nonconformity_mrp/i18n/mgmtsystem_nonconformity_mrp.pot
  mgmtsystem_nonconformity_mrp/models/__init__.py
  mgmtsystem_nonconformity_mrp/models/mgmtsystem_nonconformity_mrp.py
  mgmtsystem_nonconformity_mrp/readme/CONFIGURE.rst
  mgmtsystem_nonconformity_mrp/readme/CONTRIBUTORS.rst
  mgmtsystem_nonconformity_mrp/readme/DESCRIPTION.rst
  mgmtsystem_nonconformity_mrp/readme/HISTORY.rst
  mgmtsystem_nonconformity_mrp/readme/INSTALL.rst
  mgmtsystem_nonconformity_mrp/readme/ROADMAP.rst
  mgmtsystem_nonconformity_mrp/readme/USAGE.rst
  mgmtsystem_nonconformity_mrp/static/description/icon.png
  mgmtsystem_nonconformity_mrp/static/description/index.html
  mgmtsystem_nonconformity_mrp/views/mgmtsystem_nonconformity_views.xml
  setup/mgmtsystem_nonconformity_mrp/odoo/addons/mgmtsystem_nonconformity_mrp
  setup/mgmtsystem_nonconformity_mrp/setup.py
Labels: bot is merging ⏳

#426 [13.0][MIG] mgmtsystem partner
  mgmtsystem_partner/README.rst
  mgmtsystem_partner/__init__.py
  mgmtsystem_partner/__manifest__.py
  mgmtsystem_partner/i18n/mgmtsystem_partner.pot
  mgmtsystem_partner/models/__init__.py
  mgmtsystem_partner/models/mgmtsystem_partner.py
  mgmtsystem_partner/readme/CONTRIBUTORS.rst
  mgmtsystem_partner/readme/DESCRIPTION.rst
  mgmtsystem_partner/readme/HISTORY.rst
  mgmtsystem_partner/readme/USAGE.rst
  mgmtsystem_partner/static/description/icon.png
  mgmtsystem_partner/static/description/index.html
  setup/mgmtsystem_partner/odoo/addons/mgmtsystem_partner
  setup/mgmtsystem_partner/setup.py
Labels: bot is merging ⏳
