Repository OCA/management-system, pull requests merged in 2022-11, with the labels that each got.

#444 [13.0][FIX] mgmtsystem_audit: Bad version number in path post-migration
  mgmtsystem_audit/migrations/13.0.1.0.0/post-migration.py
  mgmtsystem_audit/readme/CONTRIBUTORS.rst
Labels: bug, needs review, bot is merging ⏳

#446 [14.0][MIG] mgmtsystem action efficacy
  .github/workflows/pre-commit.yml
  mgmtsystem_action_efficacy/README.rst
  mgmtsystem_action_efficacy/__init__.py
  mgmtsystem_action_efficacy/__manifest__.py
  mgmtsystem_action_efficacy/i18n/it.po
  mgmtsystem_action_efficacy/i18n/mgmtsystem_action_efficacy.pot
  mgmtsystem_action_efficacy/models/__init__.py
  mgmtsystem_action_efficacy/models/mgmtsystem_action_efficacy.py
  mgmtsystem_action_efficacy/readme/CONTRIBUTORS.rst
  mgmtsystem_action_efficacy/readme/DESCRIPTION.rst
  mgmtsystem_action_efficacy/readme/HISTORY.rst
  mgmtsystem_action_efficacy/readme/USAGE.rst
  mgmtsystem_action_efficacy/static/description/icon.png
  mgmtsystem_action_efficacy/static/description/index.html
  mgmtsystem_action_efficacy/tests/__init__.py
  mgmtsystem_action_efficacy/tests/test_efficacy.py
  mgmtsystem_action_efficacy/views/mgmtsystem_action_views.xml
  setup/mgmtsystem_action_efficacy/odoo/addons/mgmtsystem_action_efficacy
  setup/mgmtsystem_action_efficacy/setup.py
Labels: needs fixing, migration, bot is merging ⏳

#445 [14.0][MIG] mgmtsystem partner
  mgmtsystem_partner/README.rst
  mgmtsystem_partner/__init__.py
  mgmtsystem_partner/__manifest__.py
  mgmtsystem_partner/i18n/mgmtsystem_partner.pot
  mgmtsystem_partner/models/__init__.py
  mgmtsystem_partner/models/res_partner.py
  mgmtsystem_partner/readme/CONTRIBUTORS.rst
  mgmtsystem_partner/readme/DESCRIPTION.rst
  mgmtsystem_partner/readme/HISTORY.rst
  mgmtsystem_partner/readme/USAGE.rst
  mgmtsystem_partner/static/description/icon.png
  mgmtsystem_partner/static/description/index.html
  setup/mgmtsystem_partner/odoo/addons/mgmtsystem_partner
  setup/mgmtsystem_partner/setup.py
Labels: needs review, migration, bot is merging ⏳

#449 [FIX] copier update
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
  README.md
Labels: bug, needs review

#447 [14.0][MIG] mgmtsystem_action_template
  mgmtsystem_action_template/README.rst
  mgmtsystem_action_template/__init__.py
  mgmtsystem_action_template/__manifest__.py
  mgmtsystem_action_template/i18n/it.po
  mgmtsystem_action_template/i18n/mgmtsystem_action_template.pot
  mgmtsystem_action_template/models/__init__.py
  mgmtsystem_action_template/models/mgmtsystem_action.py
  mgmtsystem_action_template/models/mgmtsystem_action_template.py
  mgmtsystem_action_template/readme/CONTRIBUTORS.rst
  mgmtsystem_action_template/readme/DESCRIPTION.rst
  mgmtsystem_action_template/readme/HISTORY.rst
  mgmtsystem_action_template/readme/USAGE.rst
  mgmtsystem_action_template/security/ir.model.access.csv
  mgmtsystem_action_template/static/description/icon.png
  mgmtsystem_action_template/static/description/index.html
  mgmtsystem_action_template/tests/__init__.py
  mgmtsystem_action_template/tests/test_action_template.py
  mgmtsystem_action_template/views/mgmtsystem_action_template.xml
  mgmtsystem_action_template/views/mgmtsystem_action_views.xml
  setup/mgmtsystem_action_template/odoo/addons/mgmtsystem_action_template
  setup/mgmtsystem_action_template/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#454 [15.0][FIX] Update copier template on pre-commit
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
Labels: bug

#448 [14.0][MIG] mgmtsystem nonconformity product
  mgmtsystem_nonconformity_product/README.rst
  mgmtsystem_nonconformity_product/__init__.py
  mgmtsystem_nonconformity_product/__manifest__.py
  mgmtsystem_nonconformity_product/i18n/it.po
  mgmtsystem_nonconformity_product/i18n/mgmtsystem_nonconformity_product.pot
  mgmtsystem_nonconformity_product/i18n/pt_BR.po
  mgmtsystem_nonconformity_product/models/__init__.py
  mgmtsystem_nonconformity_product/models/mgmtsystem_nonconformity.py
  mgmtsystem_nonconformity_product/readme/CONTRIBUTORS.rst
  mgmtsystem_nonconformity_product/readme/DESCRIPTION.rst
  mgmtsystem_nonconformity_product/readme/HISTORY.rst
  mgmtsystem_nonconformity_product/readme/USAGE.rst
  mgmtsystem_nonconformity_product/static/description/icon.png
  mgmtsystem_nonconformity_product/static/description/index.html
  mgmtsystem_nonconformity_product/views/mgmtsystem_nonconformity_views.xml
  setup/mgmtsystem_nonconformity_product/odoo/addons/mgmtsystem_nonconformity_product
  setup/mgmtsystem_nonconformity_product/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#457 [16.0][FIX] pre-commit config
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
Labels: bug, needs review

#450 [15.0][MIG] mgmtsystem_nonconformity_mrp: Migration to 15.0
  mgmtsystem_nonconformity_mrp/README.rst
  mgmtsystem_nonconformity_mrp/__init__.py
  mgmtsystem_nonconformity_mrp/__manifest__.py
  mgmtsystem_nonconformity_mrp/i18n/it.po
  mgmtsystem_nonconformity_mrp/i18n/mgmtsystem_extended_mrp.pot
  mgmtsystem_nonconformity_mrp/i18n/mgmtsystem_nonconformity_mrp.pot
  mgmtsystem_nonconformity_mrp/models/__init__.py
  mgmtsystem_nonconformity_mrp/models/mgmtsystem_nonconformity_mrp.py
  mgmtsystem_nonconformity_mrp/readme/CONFIGURE.rst
  mgmtsystem_nonconformity_mrp/readme/CONTRIBUTORS.rst
  mgmtsystem_nonconformity_mrp/readme/DESCRIPTION.rst
  mgmtsystem_nonconformity_mrp/readme/HISTORY.rst
  mgmtsystem_nonconformity_mrp/readme/INSTALL.rst
  mgmtsystem_nonconformity_mrp/readme/ROADMAP.rst
  mgmtsystem_nonconformity_mrp/readme/USAGE.rst
  mgmtsystem_nonconformity_mrp/static/description/icon.png
  mgmtsystem_nonconformity_mrp/static/description/index.html
  mgmtsystem_nonconformity_mrp/views/mgmtsystem_nonconformity_views.xml
  setup/mgmtsystem_nonconformity_mrp/odoo/addons/mgmtsystem_nonconformity_mrp
  setup/mgmtsystem_nonconformity_mrp/setup.py
Labels: needs review, migration, bot is merging ⏳

#451 [14.0][MIG] mgmtsystem_nonconformity_type: Migration to 14.0
  mgmtsystem_nonconformity_type/README.rst
  mgmtsystem_nonconformity_type/__init__.py
  mgmtsystem_nonconformity_type/__manifest__.py
  mgmtsystem_nonconformity_type/data/mgmtsystem_nonconformity_mail_data.xml
  mgmtsystem_nonconformity_type/i18n/it.po
  mgmtsystem_nonconformity_type/i18n/mgmtsystem_nonconformity_type.pot
  mgmtsystem_nonconformity_type/models/__init__.py
  mgmtsystem_nonconformity_type/models/mgmtsystem_nonconformity.py
  mgmtsystem_nonconformity_type/readme/CONTRIBUTORS.rst
  mgmtsystem_nonconformity_type/readme/DESCRIPTION.rst
  mgmtsystem_nonconformity_type/readme/HISTORY.rst
  mgmtsystem_nonconformity_type/readme/ROADMAP.rst
  mgmtsystem_nonconformity_type/readme/USAGE.rst
  mgmtsystem_nonconformity_type/static/description/icon.png
  mgmtsystem_nonconformity_type/static/description/index.html
  mgmtsystem_nonconformity_type/tests/__init__.py
  mgmtsystem_nonconformity_type/tests/test_nonconformity_type.py
  mgmtsystem_nonconformity_type/views/mgmtsystem_nonconformity_views.xml
  setup/mgmtsystem_nonconformity_type/odoo/addons/mgmtsystem_nonconformity_type
  setup/mgmtsystem_nonconformity_type/setup.py
Labels: needs review, migration, bot is merging ⏳

#452 [15.0][MIG] mgmtsystem_action_template: Migration to 15.0
  mgmtsystem_action_template/README.rst
  mgmtsystem_action_template/__init__.py
  mgmtsystem_action_template/__manifest__.py
  mgmtsystem_action_template/i18n/it.po
  mgmtsystem_action_template/i18n/mgmtsystem_action_template.pot
  mgmtsystem_action_template/models/__init__.py
  mgmtsystem_action_template/models/mgmtsystem_action.py
  mgmtsystem_action_template/models/mgmtsystem_action_template.py
  mgmtsystem_action_template/readme/CONTRIBUTORS.rst
  mgmtsystem_action_template/readme/DESCRIPTION.rst
  mgmtsystem_action_template/readme/HISTORY.rst
  mgmtsystem_action_template/readme/USAGE.rst
  mgmtsystem_action_template/security/ir.model.access.csv
  mgmtsystem_action_template/static/description/icon.png
  mgmtsystem_action_template/static/description/index.html
  mgmtsystem_action_template/tests/__init__.py
  mgmtsystem_action_template/tests/test_action_template.py
  mgmtsystem_action_template/views/mgmtsystem_action_template.xml
  mgmtsystem_action_template/views/mgmtsystem_action_views.xml
  setup/mgmtsystem_action_template/odoo/addons/mgmtsystem_action_template
  setup/mgmtsystem_action_template/setup.py
Labels: needs review, migration, bot is merging ⏳

#453 [15.0][MIG] mgmtsystem_partner: Migration to 15.0
  mgmtsystem_partner/README.rst
  mgmtsystem_partner/__init__.py
  mgmtsystem_partner/__manifest__.py
  mgmtsystem_partner/i18n/it.po
  mgmtsystem_partner/i18n/mgmtsystem_partner.pot
  mgmtsystem_partner/models/__init__.py
  mgmtsystem_partner/models/res_partner.py
  mgmtsystem_partner/readme/CONTRIBUTORS.rst
  mgmtsystem_partner/readme/DESCRIPTION.rst
  mgmtsystem_partner/readme/HISTORY.rst
  mgmtsystem_partner/readme/USAGE.rst
  mgmtsystem_partner/static/description/icon.png
  mgmtsystem_partner/static/description/index.html
  setup/mgmtsystem_partner/odoo/addons/mgmtsystem_partner
  setup/mgmtsystem_partner/setup.py
Labels: needs review, migration, bot is merging ⏳
