Repository OCA/management-system, pull requests merged in 2022-10, with the labels that each got.

#435 [12.0][FIX] mgmtsystem_nonconformity_stage : state field changed to non ReadOnly
  mgmtsystem_nonconformity/__manifest__.py
  mgmtsystem_nonconformity/models/mgmtsystem_nonconformity_stage.py
  mgmtsystem_nonconformity/views/mgmtsystem_nonconformity_stage.xml
Labels: bot is merging ⏳

#440 [14.0][ADD] mgmtsystem_nonconformity_quality_control_oca
  mgmtsystem_nonconformity_quality_control_oca/README.rst
  mgmtsystem_nonconformity_quality_control_oca/__init__.py
  mgmtsystem_nonconformity_quality_control_oca/__manifest__.py
  mgmtsystem_nonconformity_quality_control_oca/models/__init__.py
  mgmtsystem_nonconformity_quality_control_oca/models/mgmtsystem_nonconformity.py
  mgmtsystem_nonconformity_quality_control_oca/models/qc_inspection.py
  mgmtsystem_nonconformity_quality_control_oca/readme/CONTRIBUTORS.rst
  mgmtsystem_nonconformity_quality_control_oca/readme/DESCRIPTION.rst
  mgmtsystem_nonconformity_quality_control_oca/readme/USAGE.rst
  mgmtsystem_nonconformity_quality_control_oca/static/description/icon.png
  mgmtsystem_nonconformity_quality_control_oca/static/description/index.html
  mgmtsystem_nonconformity_quality_control_oca/views/mgmtsystem_nonconformity.xml
  mgmtsystem_nonconformity_quality_control_oca/views/qc_inspection.xml
  oca_dependencies.txt
  setup/mgmtsystem_nonconformity_quality_control_oca/odoo/addons/mgmtsystem_nonconformity_quality_control_oca
  setup/mgmtsystem_nonconformity_quality_control_oca/setup.py
Labels: approved

#443 [ADD] mgmtsystem_nonconformity_quality_control_oca
  mgmtsystem_nonconformity_quality_control_oca/README.rst
  mgmtsystem_nonconformity_quality_control_oca/__init__.py
  mgmtsystem_nonconformity_quality_control_oca/__manifest__.py
  mgmtsystem_nonconformity_quality_control_oca/models/__init__.py
  mgmtsystem_nonconformity_quality_control_oca/models/mgmtsystem_nonconformity.py
  mgmtsystem_nonconformity_quality_control_oca/models/qc_inspection.py
  mgmtsystem_nonconformity_quality_control_oca/readme/CONTRIBUTORS.rst
  mgmtsystem_nonconformity_quality_control_oca/readme/DESCRIPTION.rst
  mgmtsystem_nonconformity_quality_control_oca/readme/USAGE.rst
  mgmtsystem_nonconformity_quality_control_oca/static/description/icon.png
  mgmtsystem_nonconformity_quality_control_oca/static/description/index.html
  mgmtsystem_nonconformity_quality_control_oca/views/mgmtsystem_nonconformity.xml
  mgmtsystem_nonconformity_quality_control_oca/views/qc_inspection.xml
  oca_dependencies.txt
  setup/mgmtsystem_nonconformity_quality_control_oca/odoo/addons/mgmtsystem_nonconformity_quality_control_oca
  setup/mgmtsystem_nonconformity_quality_control_oca/setup.py
Labels: enhancement, bot is merging ⏳
