Repository OCA/management-system, pull requests merged in 2022-12, with the labels that each got.

#459 [16.0][MIG] mgmtsystem manual: Migration to 16.0
  mgmtsystem_manual/README.rst
  mgmtsystem_manual/__init__.py
  mgmtsystem_manual/__manifest__.py
  mgmtsystem_manual/data/mgmtsystem_manual.xml
  mgmtsystem_manual/i18n/de.po
  mgmtsystem_manual/i18n/es.po
  mgmtsystem_manual/i18n/fr.po
  mgmtsystem_manual/i18n/hr_HR.po
  mgmtsystem_manual/i18n/it.po
  mgmtsystem_manual/i18n/lv.po
  mgmtsystem_manual/i18n/mgmtsystem_manual.pot
  mgmtsystem_manual/i18n/nb.po
  mgmtsystem_manual/i18n/nl_NL.po
  mgmtsystem_manual/i18n/nn.po
  mgmtsystem_manual/i18n/pt_BR.po
  mgmtsystem_manual/i18n/sl.po
  mgmtsystem_manual/i18n/sv.po
  mgmtsystem_manual/i18n/th.po
  mgmtsystem_manual/i18n/vi.po
  mgmtsystem_manual/models/__init__.py
  mgmtsystem_manual/models/mgmtsystem_manual.py
  mgmtsystem_manual/readme/CONFIGURE.rst
  mgmtsystem_manual/readme/CONTRIBUTORS.rst
  mgmtsystem_manual/readme/CREDITS.rst
  mgmtsystem_manual/readme/DESCRIPTION.rst
  mgmtsystem_manual/readme/HISTORY.rst
  mgmtsystem_manual/readme/INSTALL.rst
  mgmtsystem_manual/readme/USAGE.rst
  mgmtsystem_manual/static/description/icon.png
  mgmtsystem_manual/static/description/index.html
  mgmtsystem_manual/views/document_page.xml
  mgmtsystem_manual/views/mgmtsystem_manual.xml
  setup/mgmtsystem_manual/odoo/addons/mgmtsystem_manual
  setup/mgmtsystem_manual/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#463 [16.0][MIG] document_page_environmental_aspect: Migration to 16.0
  document_page_environmental_aspect/README.rst
  document_page_environmental_aspect/__init__.py
  document_page_environmental_aspect/__manifest__.py
  document_page_environmental_aspect/data/document_page.xml
  document_page_environmental_aspect/i18n/de.po
  document_page_environmental_aspect/i18n/document_page_environmental_aspect.pot
  document_page_environmental_aspect/i18n/es_CL.po
  document_page_environmental_aspect/i18n/fr.po
  document_page_environmental_aspect/i18n/it.po
  document_page_environmental_aspect/i18n/nb.po
  document_page_environmental_aspect/i18n/pt.po
  document_page_environmental_aspect/i18n/pt_BR.po
  document_page_environmental_aspect/i18n/sl.po
  document_page_environmental_aspect/i18n/sv.po
  document_page_environmental_aspect/i18n/vi.po
  document_page_environmental_aspect/readme/CONFIGURE.rst
  document_page_environmental_aspect/readme/CONTRIBUTORS.rst
  document_page_environmental_aspect/readme/DESCRIPTION.rst
  document_page_environmental_aspect/readme/USAGE.rst
  document_page_environmental_aspect/static/description/icon.png
  document_page_environmental_aspect/static/description/index.html
  document_page_environmental_aspect/views/document_page.xml
  setup/document_page_environmental_aspect/odoo/addons/document_page_environmental_aspect
  setup/document_page_environmental_aspect/setup.py
Labels: bot is merging ⏳

#466 [16.0][MIG] document_page_work_instruction: Migration to 16.0
  document_page_work_instruction/README.rst
  document_page_work_instruction/__init__.py
  document_page_work_instruction/__manifest__.py
  document_page_work_instruction/data/document_page.xml
  document_page_work_instruction/i18n/de.po
  document_page_work_instruction/i18n/document_page_work_instruction.pot
  document_page_work_instruction/i18n/es.po
  document_page_work_instruction/i18n/es_CO.po
  document_page_work_instruction/i18n/fr.po
  document_page_work_instruction/i18n/hr_HR.po
  document_page_work_instruction/i18n/it.po
  document_page_work_instruction/i18n/nb.po
  document_page_work_instruction/i18n/nl_NL.po
  document_page_work_instruction/i18n/nn.po
  document_page_work_instruction/i18n/no.po
  document_page_work_instruction/i18n/pt_BR.po
  document_page_work_instruction/i18n/sl.po
  document_page_work_instruction/i18n/vi.po
  document_page_work_instruction/readme/CONFIGURE.rst
  document_page_work_instruction/readme/CONTRIBUTORS.rst
  document_page_work_instruction/readme/CREDITS.rst
  document_page_work_instruction/readme/DESCRIPTION.rst
  document_page_work_instruction/static/description/icon.png
  document_page_work_instruction/static/description/index.html
  document_page_work_instruction/views/document_page_work_instructions.xml
  setup/document_page_work_instruction/odoo/addons/document_page_work_instruction
  setup/document_page_work_instruction/setup.py
Labels: approved, bot is merging ⏳

#464 [16.0][MIG] document_page_procedure: Migration to 16.0
  document_page_procedure/README.rst
  document_page_procedure/__init__.py
  document_page_procedure/__manifest__.py
  document_page_procedure/data/document_page_procedure.xml
  document_page_procedure/demo/document_page_procedure.xml
  document_page_procedure/i18n/de.po
  document_page_procedure/i18n/document_page_procedure.pot
  document_page_procedure/i18n/es.po
  document_page_procedure/i18n/es_CO.po
  document_page_procedure/i18n/fr.po
  document_page_procedure/i18n/hr.po
  document_page_procedure/i18n/hr_HR.po
  document_page_procedure/i18n/hu.po
  document_page_procedure/i18n/it.po
  document_page_procedure/i18n/nb.po
  document_page_procedure/i18n/nl_NL.po
  document_page_procedure/i18n/pt.po
  document_page_procedure/i18n/pt_BR.po
  document_page_procedure/i18n/sl.po
  document_page_procedure/i18n/sv.po
  document_page_procedure/i18n/vi.po
  document_page_procedure/readme/CONFIGURE.rst
  document_page_procedure/readme/CONTRIBUTORS.rst
  document_page_procedure/readme/CREDITS.rst
  document_page_procedure/readme/DESCRIPTION.rst
  document_page_procedure/static/description/icon.png
  document_page_procedure/static/description/index.html
  document_page_procedure/views/document_page_procedure.xml
  setup/document_page_procedure/odoo/addons/document_page_procedure
  setup/document_page_procedure/setup.py
Labels: bot is merging ⏳

#465 [16.0][MIG] document_page_quality_manual: Migration to 16.0
  document_page_quality_manual/README.rst
  document_page_quality_manual/__init__.py
  document_page_quality_manual/__manifest__.py
  document_page_quality_manual/data/document_page.xml
  document_page_quality_manual/i18n/ar.po
  document_page_quality_manual/i18n/bg.po
  document_page_quality_manual/i18n/ca.po
  document_page_quality_manual/i18n/cs.po
  document_page_quality_manual/i18n/da.po
  document_page_quality_manual/i18n/de.po
  document_page_quality_manual/i18n/document_page_quality_manual.pot
  document_page_quality_manual/i18n/es.po
  document_page_quality_manual/i18n/es_CR.po
  document_page_quality_manual/i18n/es_MX.po
  document_page_quality_manual/i18n/es_VE.po
  document_page_quality_manual/i18n/fi.po
  document_page_quality_manual/i18n/fr.po
  document_page_quality_manual/i18n/gl.po
  document_page_quality_manual/i18n/hr.po
  document_page_quality_manual/i18n/hu.po
  document_page_quality_manual/i18n/it.po
  document_page_quality_manual/i18n/ja.po
  document_page_quality_manual/i18n/lv.po
  document_page_quality_manual/i18n/mn.po
  document_page_quality_manual/i18n/nb.po
  document_page_quality_manual/i18n/nl.po
  document_page_quality_manual/i18n/oc.po
  document_page_quality_manual/i18n/pt.po
  document_page_quality_manual/i18n/pt_BR.po
  document_page_quality_manual/i18n/ro.po
  document_page_quality_manual/i18n/ru.po
  document_page_quality_manual/i18n/sk.po
  document_page_quality_manual/i18n/sl.po
  document_page_quality_manual/i18n/sr@latin.po
  document_page_quality_manual/i18n/sv.po
  document_page_quality_manual/i18n/tr.po
  document_page_quality_manual/i18n/vi.po
  document_page_quality_manual/i18n/zh_CN.po
  document_page_quality_manual/images/wiki_pages_quality_manual.jpeg
  document_page_quality_manual/readme/CONFIGURE.rst
  document_page_quality_manual/readme/CONTRIBUTORS.rst
  document_page_quality_manual/readme/CREDITS.rst
  document_page_quality_manual/readme/DESCRIPTION.rst
  document_page_quality_manual/readme/USAGE.rst
  document_page_quality_manual/static/description/icon.png
  document_page_quality_manual/static/description/index.html
  setup/document_page_quality_manual/odoo/addons/document_page_quality_manual
  setup/document_page_quality_manual/setup.py
Labels: bot is merging ⏳

#460 [15.0[MIG] mgmtsystem_nonconformity_type: Migration to 15.0
  mgmtsystem_nonconformity_type/README.rst
  mgmtsystem_nonconformity_type/__init__.py
  mgmtsystem_nonconformity_type/__manifest__.py
  mgmtsystem_nonconformity_type/data/mgmtsystem_nonconformity_mail_data.xml
  mgmtsystem_nonconformity_type/i18n/it.po
  mgmtsystem_nonconformity_type/i18n/mgmtsystem_nonconformity_type.pot
  mgmtsystem_nonconformity_type/models/__init__.py
  mgmtsystem_nonconformity_type/models/mgmtsystem_nonconformity.py
  mgmtsystem_nonconformity_type/readme/CONTRIBUTORS.rst
  mgmtsystem_nonconformity_type/readme/DESCRIPTION.rst
  mgmtsystem_nonconformity_type/readme/HISTORY.rst
  mgmtsystem_nonconformity_type/readme/ROADMAP.rst
  mgmtsystem_nonconformity_type/readme/USAGE.rst
  mgmtsystem_nonconformity_type/static/description/icon.png
  mgmtsystem_nonconformity_type/static/description/index.html
  mgmtsystem_nonconformity_type/tests/__init__.py
  mgmtsystem_nonconformity_type/tests/test_nonconformity_type.py
  mgmtsystem_nonconformity_type/views/mgmtsystem_nonconformity_views.xml
  setup/mgmtsystem_nonconformity_type/odoo/addons/mgmtsystem_nonconformity_type
  setup/mgmtsystem_nonconformity_type/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#472 [16.0][MIG] mgmtsystem_survey: Migration to 16.0
  mgmtsystem_survey/README.rst
  mgmtsystem_survey/__init__.py
  mgmtsystem_survey/__manifest__.py
  mgmtsystem_survey/i18n/de.po
  mgmtsystem_survey/i18n/es.po
  mgmtsystem_survey/i18n/es_CO.po
  mgmtsystem_survey/i18n/fi.po
  mgmtsystem_survey/i18n/fr.po
  mgmtsystem_survey/i18n/hr_HR.po
  mgmtsystem_survey/i18n/hu.po
  mgmtsystem_survey/i18n/it.po
  mgmtsystem_survey/i18n/lv.po
  mgmtsystem_survey/i18n/mgmtsystem_survey.pot
  mgmtsystem_survey/i18n/nb.po
  mgmtsystem_survey/i18n/nn.po
  mgmtsystem_survey/i18n/pt.po
  mgmtsystem_survey/i18n/pt_BR.po
  mgmtsystem_survey/i18n/sl.po
  mgmtsystem_survey/i18n/sv.po
  mgmtsystem_survey/i18n/th.po
  mgmtsystem_survey/i18n/tr.po
  mgmtsystem_survey/i18n/vi.po
  mgmtsystem_survey/models/__init__.py
  mgmtsystem_survey/readme/CONFIGURE.rst
  mgmtsystem_survey/readme/CONTRIBUTORS.rst
  mgmtsystem_survey/readme/CREDITS.rst
  mgmtsystem_survey/readme/DESCRIPTION.rst
  mgmtsystem_survey/readme/USAGE.rst
  mgmtsystem_survey/static/description/icon.png
  mgmtsystem_survey/static/description/index.html
  mgmtsystem_survey/views/survey_survey.xml
  setup/mgmtsystem_survey/odoo/addons/mgmtsystem_survey
  setup/mgmtsystem_survey/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#468 [16.0][MIG] mgmtsystem_action_efficacy: Migration to 16.0
  mgmtsystem_action_efficacy/README.rst
  mgmtsystem_action_efficacy/__init__.py
  mgmtsystem_action_efficacy/__manifest__.py
  mgmtsystem_action_efficacy/i18n/it.po
  mgmtsystem_action_efficacy/i18n/mgmtsystem_action_efficacy.pot
  mgmtsystem_action_efficacy/models/__init__.py
  mgmtsystem_action_efficacy/models/mgmtsystem_action.py
  mgmtsystem_action_efficacy/readme/CONTRIBUTORS.rst
  mgmtsystem_action_efficacy/readme/DESCRIPTION.rst
  mgmtsystem_action_efficacy/readme/HISTORY.rst
  mgmtsystem_action_efficacy/readme/USAGE.rst
  mgmtsystem_action_efficacy/static/description/icon.png
  mgmtsystem_action_efficacy/static/description/index.html
  mgmtsystem_action_efficacy/tests/__init__.py
  mgmtsystem_action_efficacy/tests/test_efficacy.py
  mgmtsystem_action_efficacy/views/mgmtsystem_action_views.xml
  setup/mgmtsystem_action_efficacy/odoo/addons/mgmtsystem_action_efficacy
  setup/mgmtsystem_action_efficacy/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#470 [16.0][MIG] mgmtsystem_audit: Migration to 16.0
  mgmtsystem_audit/README.rst
  mgmtsystem_audit/__init__.py
  mgmtsystem_audit/__manifest__.py
  mgmtsystem_audit/data/audit_automated_actions.xml
  mgmtsystem_audit/data/audit_sequence.xml
  mgmtsystem_audit/demo/demo_audit.xml
  mgmtsystem_audit/i18n/am.po
  mgmtsystem_audit/i18n/ca.po
  mgmtsystem_audit/i18n/de.po
  mgmtsystem_audit/i18n/el_GR.po
  mgmtsystem_audit/i18n/es.po
  mgmtsystem_audit/i18n/es_CO.po
  mgmtsystem_audit/i18n/es_ES.po
  mgmtsystem_audit/i18n/fi.po
  mgmtsystem_audit/i18n/fr.po
  mgmtsystem_audit/i18n/gl.po
  mgmtsystem_audit/i18n/hr_HR.po
  mgmtsystem_audit/i18n/hu.po
  mgmtsystem_audit/i18n/it.po
  mgmtsystem_audit/i18n/lv.po
  mgmtsystem_audit/i18n/mgmtsystem_audit.pot
  mgmtsystem_audit/i18n/nb.po
  mgmtsystem_audit/i18n/nl.po
  mgmtsystem_audit/i18n/nl_NL.po
  mgmtsystem_audit/i18n/nn.po
  mgmtsystem_audit/i18n/pt.po
  mgmtsystem_audit/i18n/pt_BR.po
  mgmtsystem_audit/i18n/pt_PT.po
  mgmtsystem_audit/i18n/sl.po
  mgmtsystem_audit/i18n/sv.po
  mgmtsystem_audit/i18n/tr.po
  mgmtsystem_audit/i18n/vi.po
  mgmtsystem_audit/models/__init__.py
  mgmtsystem_audit/models/mgmtsystem_audit.py
  mgmtsystem_audit/models/mgmtsystem_nonconformity.py
  mgmtsystem_audit/models/mgmtsystem_verification_line.py
  mgmtsystem_audit/readme/CONFIGURE.rst
  mgmtsystem_audit/readme/CONTRIBUTORS.rst
  mgmtsystem_audit/readme/DESCRIPTION.rst
  mgmtsystem_audit/readme/USAGE.rst
  mgmtsystem_audit/report/audit.xml
  mgmtsystem_audit/report/mgmtsystem_audit_pivot.xml
  mgmtsystem_audit/report/report.xml
  mgmtsystem_audit/report/verification.xml
  mgmtsystem_audit/security/ir.model.access.csv
  mgmtsystem_audit/security/mgmtsystem_audit_security.xml
  mgmtsystem_audit/static/description/icon.png
  mgmtsystem_audit/static/description/index.html
  mgmtsystem_audit/tests/__init__.py
  mgmtsystem_audit/tests/test_audit.py
  mgmtsystem_audit/tests/test_copy_verification_lines.py
  mgmtsystem_audit/views/mgmtsystem_audit.xml
  mgmtsystem_audit/views/res_users.xml
  mgmtsystem_audit/wizard/__init__.py
  mgmtsystem_audit/wizard/copy_verification_lines.py
  mgmtsystem_audit/wizard/copy_verification_lines.xml
  setup/mgmtsystem_audit/odoo/addons/mgmtsystem_audit
  setup/mgmtsystem_audit/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#461 [15.0][MIG] mgmtsystem_nonconformity_quality_control_oca
  mgmtsystem_nonconformity_quality_control_oca/README.rst
  mgmtsystem_nonconformity_quality_control_oca/__init__.py
  mgmtsystem_nonconformity_quality_control_oca/__manifest__.py
  mgmtsystem_nonconformity_quality_control_oca/i18n/it.po
  mgmtsystem_nonconformity_quality_control_oca/i18n/mgmtsystem_nonconformity_quality_control_oca.pot
  mgmtsystem_nonconformity_quality_control_oca/models/__init__.py
  mgmtsystem_nonconformity_quality_control_oca/models/mgmtsystem_nonconformity.py
  mgmtsystem_nonconformity_quality_control_oca/models/qc_inspection.py
  mgmtsystem_nonconformity_quality_control_oca/readme/CONTRIBUTORS.rst
  mgmtsystem_nonconformity_quality_control_oca/readme/DESCRIPTION.rst
  mgmtsystem_nonconformity_quality_control_oca/readme/USAGE.rst
  mgmtsystem_nonconformity_quality_control_oca/static/description/icon.png
  mgmtsystem_nonconformity_quality_control_oca/static/description/index.html
  mgmtsystem_nonconformity_quality_control_oca/views/mgmtsystem_nonconformity.xml
  mgmtsystem_nonconformity_quality_control_oca/views/qc_inspection.xml
  setup/mgmtsystem_nonconformity_quality_control_oca/odoo/addons/mgmtsystem_nonconformity_quality_control_oca
  setup/mgmtsystem_nonconformity_quality_control_oca/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#475 [16.0][MIG] mgmtsystem_review: Migration to 16.0
  mgmtsystem_review/README.rst
  mgmtsystem_review/__init__.py
  mgmtsystem_review/__manifest__.py
  mgmtsystem_review/data/ir_sequence.xml
  mgmtsystem_review/i18n/am.po
  mgmtsystem_review/i18n/ca.po
  mgmtsystem_review/i18n/de.po
  mgmtsystem_review/i18n/el_GR.po
  mgmtsystem_review/i18n/es.po
  mgmtsystem_review/i18n/es_CO.po
  mgmtsystem_review/i18n/es_ES.po
  mgmtsystem_review/i18n/fi.po
  mgmtsystem_review/i18n/fr.po
  mgmtsystem_review/i18n/gl.po
  mgmtsystem_review/i18n/hr_HR.po
  mgmtsystem_review/i18n/hu.po
  mgmtsystem_review/i18n/it.po
  mgmtsystem_review/i18n/lv.po
  mgmtsystem_review/i18n/mgmtsystem_review.pot
  mgmtsystem_review/i18n/nb.po
  mgmtsystem_review/i18n/nl.po
  mgmtsystem_review/i18n/nl_NL.po
  mgmtsystem_review/i18n/nn.po
  mgmtsystem_review/i18n/pt.po
  mgmtsystem_review/i18n/pt_BR.po
  mgmtsystem_review/i18n/pt_PT.po
  mgmtsystem_review/i18n/sl.po
  mgmtsystem_review/i18n/sv.po
  mgmtsystem_review/i18n/th.po
  mgmtsystem_review/i18n/tr.po
  mgmtsystem_review/i18n/vi.po
  mgmtsystem_review/models/__init__.py
  mgmtsystem_review/models/mgmtsystem_review.py
  mgmtsystem_review/models/mgmtsystem_review_line.py
  mgmtsystem_review/readme/CONTRIBUTORS.rst
  mgmtsystem_review/readme/CREDITS.rst
  mgmtsystem_review/readme/DESCRIPTION.rst
  mgmtsystem_review/readme/USAGE.rst
  mgmtsystem_review/report/report.xml
  mgmtsystem_review/report/review.xml
  mgmtsystem_review/security/ir.model.access.csv
  mgmtsystem_review/security/mgmtsystem_review_security.xml
  mgmtsystem_review/static/description/icon.png
  mgmtsystem_review/static/description/index.html
  mgmtsystem_review/tests/__init__.py
  mgmtsystem_review/tests/test_create_review.py
  mgmtsystem_review/views/mgmtsystem_review.xml
  mgmtsystem_review/views/res_users.xml
  setup/mgmtsystem_review/odoo/addons/mgmtsystem_review
  setup/mgmtsystem_review/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#480 [14.0][MIG] document_page_health_safety_manual
  document_page_health_safety_manual/README.rst
  document_page_health_safety_manual/__init__.py
  document_page_health_safety_manual/__manifest__.py
  document_page_health_safety_manual/data/document_page.xml
  document_page_health_safety_manual/i18n/document_page_health_safety_manual.pot
  document_page_health_safety_manual/i18n/it.po
  document_page_health_safety_manual/readme/CONTRIBUTORS.rst
  document_page_health_safety_manual/readme/DESCRIPTION.rst
  document_page_health_safety_manual/readme/ROADMAP.rst
  document_page_health_safety_manual/readme/USAGE.rst
  document_page_health_safety_manual/static/description/icon.png
  document_page_health_safety_manual/static/description/index.html
  setup/document_page_health_safety_manual/odoo/addons/document_page_health_safety_manual
  setup/document_page_health_safety_manual/setup.py
Labels: needs review, migration, bot is merging ⏳

#476 [16.0][MIG] mgmtsystem_nonconformity_hr: Migration to 16.0
  mgmtsystem_nonconformity_hr/README.rst
  mgmtsystem_nonconformity_hr/__init__.py
  mgmtsystem_nonconformity_hr/__manifest__.py
  mgmtsystem_nonconformity_hr/i18n/it.po
  mgmtsystem_nonconformity_hr/i18n/mgmtsystem_nonconformity_hr.pot
  mgmtsystem_nonconformity_hr/i18n/pt.po
  mgmtsystem_nonconformity_hr/models/__init__.py
  mgmtsystem_nonconformity_hr/models/mgmtsystem_nonconformity_hr.py
  mgmtsystem_nonconformity_hr/readme/CONTRIBUTORS.rst
  mgmtsystem_nonconformity_hr/readme/DESCRIPTION.rst
  mgmtsystem_nonconformity_hr/readme/HISTORY.rst
  mgmtsystem_nonconformity_hr/readme/USAGE.rst
  mgmtsystem_nonconformity_hr/static/description/icon.png
  mgmtsystem_nonconformity_hr/static/description/index.html
  mgmtsystem_nonconformity_hr/views/mgmtsystem_nonconformity_views.xml
  setup/mgmtsystem_nonconformity_hr/odoo/addons/mgmtsystem_nonconformity_hr
  setup/mgmtsystem_nonconformity_hr/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#483 [15.0][MIG] mgmtsystem_environment
  mgmtsystem_environment/README.rst
  mgmtsystem_environment/__init__.py
  mgmtsystem_environment/__manifest__.py
  mgmtsystem_environment/data/environment.xml
  mgmtsystem_environment/i18n/de.po
  mgmtsystem_environment/i18n/fr.po
  mgmtsystem_environment/i18n/it.po
  mgmtsystem_environment/i18n/mgmtsystem_environment.pot
  mgmtsystem_environment/i18n/nb.po
  mgmtsystem_environment/i18n/pt_BR.po
  mgmtsystem_environment/i18n/sv.po
  mgmtsystem_environment/i18n/tr.po
  mgmtsystem_environment/i18n/vi.po
  mgmtsystem_environment/readme/CONFIGURE.rst
  mgmtsystem_environment/readme/CONTRIBUTORS.rst
  mgmtsystem_environment/readme/DESCRIPTION.rst
  mgmtsystem_environment/readme/USAGE.rst
  mgmtsystem_environment/static/description/icon.png
  mgmtsystem_environment/static/description/index.html
  mgmtsystem_environment/static/src/img/icon.png
  setup/mgmtsystem_environment/odoo/addons/mgmtsystem_environment
  setup/mgmtsystem_environment/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#478 [16.0][MIG] mgmtsystem_nonconformity_product: Migration to 16.0
  mgmtsystem_nonconformity_product/README.rst
  mgmtsystem_nonconformity_product/__init__.py
  mgmtsystem_nonconformity_product/__manifest__.py
  mgmtsystem_nonconformity_product/i18n/it.po
  mgmtsystem_nonconformity_product/i18n/mgmtsystem_nonconformity_product.pot
  mgmtsystem_nonconformity_product/i18n/pt_BR.po
  mgmtsystem_nonconformity_product/models/__init__.py
  mgmtsystem_nonconformity_product/models/mgmtsystem_nonconformity.py
  mgmtsystem_nonconformity_product/readme/CONTRIBUTORS.rst
  mgmtsystem_nonconformity_product/readme/DESCRIPTION.rst
  mgmtsystem_nonconformity_product/readme/HISTORY.rst
  mgmtsystem_nonconformity_product/readme/USAGE.rst
  mgmtsystem_nonconformity_product/static/description/icon.png
  mgmtsystem_nonconformity_product/static/description/index.html
  mgmtsystem_nonconformity_product/views/mgmtsystem_nonconformity_views.xml
  setup/mgmtsystem_nonconformity_product/odoo/addons/mgmtsystem_nonconformity_product
  setup/mgmtsystem_nonconformity_product/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#481 [15.0][MIG] document_page_health_safety_manual
  document_page_health_safety_manual/README.rst
  document_page_health_safety_manual/__init__.py
  document_page_health_safety_manual/__manifest__.py
  document_page_health_safety_manual/data/document_page.xml
  document_page_health_safety_manual/i18n/document_page_health_safety_manual.pot
  document_page_health_safety_manual/i18n/it.po
  document_page_health_safety_manual/readme/CONTRIBUTORS.rst
  document_page_health_safety_manual/readme/DESCRIPTION.rst
  document_page_health_safety_manual/readme/ROADMAP.rst
  document_page_health_safety_manual/readme/USAGE.rst
  document_page_health_safety_manual/static/description/icon.png
  document_page_health_safety_manual/static/description/index.html
  setup/document_page_health_safety_manual/odoo/addons/document_page_health_safety_manual
  setup/document_page_health_safety_manual/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#477 [16.0][MIG] mgmtsystem_nonconformity_mrp: Migration to 16.0
  mgmtsystem_nonconformity_mrp/README.rst
  mgmtsystem_nonconformity_mrp/__init__.py
  mgmtsystem_nonconformity_mrp/__manifest__.py
  mgmtsystem_nonconformity_mrp/i18n/it.po
  mgmtsystem_nonconformity_mrp/i18n/mgmtsystem_nonconformity_mrp.pot
  mgmtsystem_nonconformity_mrp/models/__init__.py
  mgmtsystem_nonconformity_mrp/models/mgmtsystem_nonconformity_mrp.py
  mgmtsystem_nonconformity_mrp/readme/CONFIGURE.rst
  mgmtsystem_nonconformity_mrp/readme/CONTRIBUTORS.rst
  mgmtsystem_nonconformity_mrp/readme/DESCRIPTION.rst
  mgmtsystem_nonconformity_mrp/readme/HISTORY.rst
  mgmtsystem_nonconformity_mrp/readme/INSTALL.rst
  mgmtsystem_nonconformity_mrp/readme/ROADMAP.rst
  mgmtsystem_nonconformity_mrp/readme/USAGE.rst
  mgmtsystem_nonconformity_mrp/static/description/icon.png
  mgmtsystem_nonconformity_mrp/static/description/index.html
  mgmtsystem_nonconformity_mrp/views/mgmtsystem_nonconformity_views.xml
  setup/mgmtsystem_nonconformity_mrp/odoo/addons/mgmtsystem_nonconformity_mrp
  setup/mgmtsystem_nonconformity_mrp/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#484 [14.0][MIG] mgmtsystem_info_security_manual
  mgmtsystem_info_security_manual/README.rst
  mgmtsystem_info_security_manual/__init__.py
  mgmtsystem_info_security_manual/__manifest__.py
  mgmtsystem_info_security_manual/data/information_security_manual.xml
  mgmtsystem_info_security_manual/i18n/it.po
  mgmtsystem_info_security_manual/i18n/mgmtsystem_info_security_manual.pot
  mgmtsystem_info_security_manual/readme/CONTRIBUTORS.rst
  mgmtsystem_info_security_manual/readme/DESCRIPTION.rst
  mgmtsystem_info_security_manual/readme/USAGE.rst
  mgmtsystem_info_security_manual/static/description/icon.png
  mgmtsystem_info_security_manual/static/description/index.html
  setup/mgmtsystem_info_security_manual/odoo/addons/mgmtsystem_info_security_manual
  setup/mgmtsystem_info_security_manual/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#485 [15.0][MIG] mgmtsystem_info_security_manual
   oca_dependencies.txt 
  mgmtsystem_info_security_manual/README.rst
  mgmtsystem_info_security_manual/__init__.py
  mgmtsystem_info_security_manual/__manifest__.py
  mgmtsystem_info_security_manual/data/information_security_manual.xml
  mgmtsystem_info_security_manual/i18n/it.po
  mgmtsystem_info_security_manual/i18n/mgmtsystem_info_security_manual.pot
  mgmtsystem_info_security_manual/readme/CONTRIBUTORS.rst
  mgmtsystem_info_security_manual/readme/DESCRIPTION.rst
  mgmtsystem_info_security_manual/readme/USAGE.rst
  mgmtsystem_info_security_manual/static/description/icon.png
  mgmtsystem_info_security_manual/static/description/index.html
  setup/mgmtsystem_info_security_manual/odoo/addons/mgmtsystem_info_security_manual
  setup/mgmtsystem_info_security_manual/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#486 [16.0][MIG] mgmtsystem_quality: Migration to 16.0
  mgmtsystem_quality/README.rst
  mgmtsystem_quality/__init__.py
  mgmtsystem_quality/__manifest__.py
  mgmtsystem_quality/data/mgmtsystem_system.xml
  mgmtsystem_quality/i18n/de.po
  mgmtsystem_quality/i18n/fr.po
  mgmtsystem_quality/i18n/it.po
  mgmtsystem_quality/i18n/mgmtsystem_quality.pot
  mgmtsystem_quality/i18n/nb.po
  mgmtsystem_quality/i18n/pt_BR.po
  mgmtsystem_quality/i18n/sv.po
  mgmtsystem_quality/i18n/vi.po
  mgmtsystem_quality/readme/CONFIGURE.rst
  mgmtsystem_quality/readme/CONTRIBUTORS.rst
  mgmtsystem_quality/readme/DESCRIPTION.rst
  mgmtsystem_quality/readme/ROADMAP.rst
  mgmtsystem_quality/readme/USAGE.rst
  mgmtsystem_quality/static/description/icon.png
  mgmtsystem_quality/static/description/index.html
  setup/mgmtsystem_quality/odoo/addons/mgmtsystem_quality
  setup/mgmtsystem_quality/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#479 [15.0][ADD] test mgmtsystem_nonconformity_quality_control_oca
  mgmtsystem_nonconformity_quality_control_oca/tests/__init__.py
  mgmtsystem_nonconformity_quality_control_oca/tests/test_inspection.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#487 [14.0][MIG] mgmtsystem_health_safety
  mgmtsystem_health_safety/README.rst
  mgmtsystem_health_safety/__init__.py
  mgmtsystem_health_safety/__manifest__.py
  mgmtsystem_health_safety/data/health_safety.xml
  mgmtsystem_health_safety/i18n/de.po
  mgmtsystem_health_safety/i18n/fr.po
  mgmtsystem_health_safety/i18n/it.po
  mgmtsystem_health_safety/i18n/mgmtsystem_health_safety.pot
  mgmtsystem_health_safety/i18n/nb.po
  mgmtsystem_health_safety/i18n/pt_BR.po
  mgmtsystem_health_safety/i18n/sv.po
  mgmtsystem_health_safety/i18n/vi.po
  mgmtsystem_health_safety/readme/CONTRIBUTORS.rst
  mgmtsystem_health_safety/readme/DESCRIPTION.rst
  mgmtsystem_health_safety/readme/ROADMAP.rst
  mgmtsystem_health_safety/readme/USAGE.rst
  mgmtsystem_health_safety/static/description/icon.png
  mgmtsystem_health_safety/static/description/index.html
  mgmtsystem_health_safety/static/src/img/icon.png
  setup/mgmtsystem_health_safety/odoo/addons/mgmtsystem_health_safety
  setup/mgmtsystem_health_safety/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#488 [15.0][MIG] mgmtsystem_health_safety
  mgmtsystem_health_safety/README.rst
  mgmtsystem_health_safety/__init__.py
  mgmtsystem_health_safety/__manifest__.py
  mgmtsystem_health_safety/data/health_safety.xml
  mgmtsystem_health_safety/i18n/de.po
  mgmtsystem_health_safety/i18n/fr.po
  mgmtsystem_health_safety/i18n/it.po
  mgmtsystem_health_safety/i18n/mgmtsystem_health_safety.pot
  mgmtsystem_health_safety/i18n/nb.po
  mgmtsystem_health_safety/i18n/pt_BR.po
  mgmtsystem_health_safety/i18n/sv.po
  mgmtsystem_health_safety/i18n/vi.po
  mgmtsystem_health_safety/readme/CONTRIBUTORS.rst
  mgmtsystem_health_safety/readme/DESCRIPTION.rst
  mgmtsystem_health_safety/readme/ROADMAP.rst
  mgmtsystem_health_safety/readme/USAGE.rst
  mgmtsystem_health_safety/static/description/icon.png
  mgmtsystem_health_safety/static/description/index.html
  mgmtsystem_health_safety/static/src/img/icon.png
  setup/mgmtsystem_health_safety/odoo/addons/mgmtsystem_health_safety
  setup/mgmtsystem_health_safety/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#491 [16.0][MIG] mgmtsystem_hazard_risk
  mgmtsystem_hazard_risk/README.rst
  mgmtsystem_hazard_risk/__init__.py
  mgmtsystem_hazard_risk/__manifest__.py
  mgmtsystem_hazard_risk/data/mgmtsystem_hazard_risk_computation.xml
  mgmtsystem_hazard_risk/data/mgmtsystem_hazard_risk_type.xml
  mgmtsystem_hazard_risk/i18n/de.po
  mgmtsystem_hazard_risk/i18n/es.po
  mgmtsystem_hazard_risk/i18n/fr.po
  mgmtsystem_hazard_risk/i18n/hr.po
  mgmtsystem_hazard_risk/i18n/id.po
  mgmtsystem_hazard_risk/i18n/it.po
  mgmtsystem_hazard_risk/i18n/mgmtsystem_hazard_risk.pot
  mgmtsystem_hazard_risk/i18n/nb.po
  mgmtsystem_hazard_risk/i18n/pt_BR.po
  mgmtsystem_hazard_risk/i18n/sl.po
  mgmtsystem_hazard_risk/i18n/vi.po
  mgmtsystem_hazard_risk/models/__init__.py
  mgmtsystem_hazard_risk/models/common.py
  mgmtsystem_hazard_risk/models/mgmtsystem_hazard.py
  mgmtsystem_hazard_risk/models/mgmtsystem_hazard_residual_risk.py
  mgmtsystem_hazard_risk/models/mgmtsystem_hazard_risk_computation.py
  mgmtsystem_hazard_risk/models/mgmtsystem_hazard_risk_type.py
  mgmtsystem_hazard_risk/models/res_company.py
  mgmtsystem_hazard_risk/models/res_config_settings.py
  mgmtsystem_hazard_risk/readme/CONFIGURE.rst
  mgmtsystem_hazard_risk/readme/CONTRIBUTORS.rst
  mgmtsystem_hazard_risk/readme/DESCRIPTION.rst
  mgmtsystem_hazard_risk/security/ir.model.access.csv
  mgmtsystem_hazard_risk/security/mgmtsystem_hazard_security.xml
  mgmtsystem_hazard_risk/static/description/icon.png
  mgmtsystem_hazard_risk/static/description/index.html
  mgmtsystem_hazard_risk/tests/__init__.py
  mgmtsystem_hazard_risk/tests/test_mgmtsystem_hazard.py
  mgmtsystem_hazard_risk/views/mgmtsystem_hazard.xml
  mgmtsystem_hazard_risk/views/mgmtsystem_hazard_residual_risk.xml
  mgmtsystem_hazard_risk/views/mgmtsystem_hazard_risk_computation.xml
  mgmtsystem_hazard_risk/views/mgmtsystem_hazard_risk_type.xml
  mgmtsystem_hazard_risk/views/res_config_settings_views.xml
  setup/mgmtsystem_hazard_risk/odoo/addons/mgmtsystem_hazard_risk
  setup/mgmtsystem_hazard_risk/setup.py
Labels: needs review, needs fixing, approved, migration, bot is merging ⏳

#490 [16.0][MIG] mgmtsystem_environment
  mgmtsystem_environment/README.rst
  mgmtsystem_environment/__init__.py
  mgmtsystem_environment/__manifest__.py
  mgmtsystem_environment/data/environment.xml
  mgmtsystem_environment/i18n/de.po
  mgmtsystem_environment/i18n/fr.po
  mgmtsystem_environment/i18n/it.po
  mgmtsystem_environment/i18n/mgmtsystem_environment.pot
  mgmtsystem_environment/i18n/nb.po
  mgmtsystem_environment/i18n/pt_BR.po
  mgmtsystem_environment/i18n/sv.po
  mgmtsystem_environment/i18n/tr.po
  mgmtsystem_environment/i18n/vi.po
  mgmtsystem_environment/readme/CONFIGURE.rst
  mgmtsystem_environment/readme/CONTRIBUTORS.rst
  mgmtsystem_environment/readme/DESCRIPTION.rst
  mgmtsystem_environment/readme/USAGE.rst
  mgmtsystem_environment/static/description/icon.png
  mgmtsystem_environment/static/description/index.html
  mgmtsystem_environment/static/src/img/icon.png
  setup/mgmtsystem_environment/odoo/addons/mgmtsystem_environment
  setup/mgmtsystem_environment/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#489 [16.0][MIG] document_page_health_safety_manual
  document_page_health_safety_manual/README.rst
  document_page_health_safety_manual/__init__.py
  document_page_health_safety_manual/__manifest__.py
  document_page_health_safety_manual/data/document_page.xml
  document_page_health_safety_manual/i18n/document_page_health_safety_manual.pot
  document_page_health_safety_manual/i18n/it.po
  document_page_health_safety_manual/readme/CONTRIBUTORS.rst
  document_page_health_safety_manual/readme/DESCRIPTION.rst
  document_page_health_safety_manual/readme/ROADMAP.rst
  document_page_health_safety_manual/readme/USAGE.rst
  document_page_health_safety_manual/static/description/icon.png
  document_page_health_safety_manual/static/description/index.html
  setup/document_page_health_safety_manual/odoo/addons/document_page_health_safety_manual
  setup/document_page_health_safety_manual/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#492 [16.0][MIG] mgmtsystem_info_security_manual
  mgmtsystem_info_security_manual/README.rst
  mgmtsystem_info_security_manual/__init__.py
  mgmtsystem_info_security_manual/__manifest__.py
  mgmtsystem_info_security_manual/data/information_security_manual.xml
  mgmtsystem_info_security_manual/i18n/it.po
  mgmtsystem_info_security_manual/i18n/mgmtsystem_info_security_manual.pot
  mgmtsystem_info_security_manual/readme/CONTRIBUTORS.rst
  mgmtsystem_info_security_manual/readme/DESCRIPTION.rst
  mgmtsystem_info_security_manual/readme/USAGE.rst
  mgmtsystem_info_security_manual/static/description/icon.png
  mgmtsystem_info_security_manual/static/description/index.html
  setup/mgmtsystem_info_security_manual/odoo/addons/mgmtsystem_info_security_manual
  setup/mgmtsystem_info_security_manual/setup.py
Labels: approved, migration, ready to merge, bot is merging ⏳

#493 [16.0][MIG] mgmtsystem_nonconformity_type
  mgmtsystem_nonconformity_type/README.rst
  mgmtsystem_nonconformity_type/__init__.py
  mgmtsystem_nonconformity_type/__manifest__.py
  mgmtsystem_nonconformity_type/data/mgmtsystem_nonconformity_mail_data.xml
  mgmtsystem_nonconformity_type/i18n/it.po
  mgmtsystem_nonconformity_type/i18n/mgmtsystem_nonconformity_type.pot
  mgmtsystem_nonconformity_type/models/__init__.py
  mgmtsystem_nonconformity_type/models/mgmtsystem_nonconformity.py
  mgmtsystem_nonconformity_type/readme/CONTRIBUTORS.rst
  mgmtsystem_nonconformity_type/readme/DESCRIPTION.rst
  mgmtsystem_nonconformity_type/readme/HISTORY.rst
  mgmtsystem_nonconformity_type/readme/ROADMAP.rst
  mgmtsystem_nonconformity_type/readme/USAGE.rst
  mgmtsystem_nonconformity_type/static/description/icon.png
  mgmtsystem_nonconformity_type/static/description/index.html
  mgmtsystem_nonconformity_type/tests/__init__.py
  mgmtsystem_nonconformity_type/tests/test_nonconformity_type.py
  mgmtsystem_nonconformity_type/views/mgmtsystem_nonconformity_views.xml
  setup/mgmtsystem_nonconformity_type/odoo/addons/mgmtsystem_nonconformity_type
  setup/mgmtsystem_nonconformity_type/setup.py
Labels: approved, migration, bot is merging ⏳

#497 [16.0][MIG] mgmtsystem_health_safety
  mgmtsystem_health_safety/README.rst
  mgmtsystem_health_safety/__init__.py
  mgmtsystem_health_safety/__manifest__.py
  mgmtsystem_health_safety/data/health_safety.xml
  mgmtsystem_health_safety/i18n/de.po
  mgmtsystem_health_safety/i18n/fr.po
  mgmtsystem_health_safety/i18n/it.po
  mgmtsystem_health_safety/i18n/mgmtsystem_health_safety.pot
  mgmtsystem_health_safety/i18n/nb.po
  mgmtsystem_health_safety/i18n/pt_BR.po
  mgmtsystem_health_safety/i18n/sv.po
  mgmtsystem_health_safety/i18n/vi.po
  mgmtsystem_health_safety/readme/CONTRIBUTORS.rst
  mgmtsystem_health_safety/readme/DESCRIPTION.rst
  mgmtsystem_health_safety/readme/ROADMAP.rst
  mgmtsystem_health_safety/readme/USAGE.rst
  mgmtsystem_health_safety/static/description/icon.png
  mgmtsystem_health_safety/static/description/index.html
  mgmtsystem_health_safety/static/src/img/icon.png
  setup/mgmtsystem_health_safety/odoo/addons/mgmtsystem_health_safety
  setup/mgmtsystem_health_safety/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#500 [13.0][FIX] pre-commit-config.yaml gitlab reference
  .pre-commit-config.yaml
Labels: bot is merging ⏳
