Repository OCA/management-system, pull requests merged in 2023-11, with the labels that each got.

#553 [FIX] pre-commit issues
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  document_page_work_instruction/data/document_page.xml
  mgmtsystem/views/mgmtsystem_system.xml
  mgmtsystem_action/data/action_sequence.xml
  mgmtsystem_action/data/automated_reminder.xml
  mgmtsystem_action/demo/mgmtsystem_action.xml
  mgmtsystem_action/security/mgmtsystem_action_security.xml
  mgmtsystem_action/views/mgmtsystem_action.xml
  mgmtsystem_action/views/mgmtsystem_action_stage.xml
  mgmtsystem_audit/data/audit_automated_actions.xml
  mgmtsystem_audit/data/audit_sequence.xml
  mgmtsystem_audit/demo/demo_audit.xml
  mgmtsystem_audit/security/mgmtsystem_audit_security.xml
  mgmtsystem_audit/views/mgmtsystem_audit.xml
  mgmtsystem_claim/data/automated_reminder.xml
  mgmtsystem_claim/data/claim_sequence.xml
  mgmtsystem_claim/data/email_template.xml
  mgmtsystem_claim/data/mgmtsystem_claim_stage.xml
  mgmtsystem_claim/security/mgmtsystem_claim_security.xml
  mgmtsystem_claim/views/menus.xml
  mgmtsystem_claim/views/mgmtsystem_claim.xml
  mgmtsystem_claim/views/mgmtsystem_claim_stage.xml
  mgmtsystem_environment/data/environment.xml
  mgmtsystem_hazard/views/mgmtsystem_hazard.xml
  mgmtsystem_hazard/views/mgmtsystem_hazard_control_measure.xml
  mgmtsystem_hazard/views/mgmtsystem_hazard_origin.xml
  mgmtsystem_hazard/views/mgmtsystem_hazard_probability.xml
  mgmtsystem_hazard/views/mgmtsystem_hazard_severity.xml
  mgmtsystem_hazard/views/mgmtsystem_hazard_test.xml
  mgmtsystem_hazard/views/mgmtsystem_hazard_type.xml
  mgmtsystem_hazard/views/mgmtsystem_hazard_usage.xml
  mgmtsystem_health_safety/data/health_safety.xml
  mgmtsystem_nonconformity/data/mail_message_subtype.xml
  mgmtsystem_nonconformity/data/mgmtsystem_nonconformity_cause.xml
  mgmtsystem_nonconformity/data/mgmtsystem_nonconformity_origin.xml
  mgmtsystem_nonconformity/data/mgmtsystem_nonconformity_severity.xml
  mgmtsystem_nonconformity/data/mgmtsystem_nonconformity_stage.xml
  mgmtsystem_nonconformity/data/sequence.xml
  mgmtsystem_nonconformity/demo/mgmtsystem_nonconformity_cause.xml
  mgmtsystem_nonconformity/demo/mgmtsystem_nonconformity_origin.xml
  mgmtsystem_nonconformity/security/mgmtsystem_nonconformity_security.xml
  mgmtsystem_nonconformity/views/mgmtsystem_nonconformity.xml
  mgmtsystem_nonconformity/views/mgmtsystem_nonconformity_stage.xml
  mgmtsystem_review/views/mgmtsystem_review.xml
Labels: bug, needs review, approved

#552 [15.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  mgmtsystem_action/i18n/mgmtsystem_action.pot
  mgmtsystem_audit/i18n/mgmtsystem_audit.pot
  mgmtsystem_claim/i18n/mgmtsystem_claim.pot
  mgmtsystem_hazard/i18n/mgmtsystem_hazard.pot
  mgmtsystem_nonconformity/i18n/mgmtsystem_nonconformity.pot
  mgmtsystem_review/i18n/mgmtsystem_review.pot
Labels: help wanted, needs review, bot is merging ⏳

#557 [IMP] mgmtsystem_quality: Update CONTRIBUTORS.rst
  mgmtsystem_quality/readme/CONTRIBUTORS.rst
Labels: enhancement, bot is merging ⏳
