Repository OCA/management-system, pull requests merged in 2023-09, with the labels that each got.

#529 Update mgmtsystem_nonconformity_origin.py
  mgmtsystem_nonconformity/models/mgmtsystem_nonconformity_origin.py
Labels: bot is merging ⏳

#524 [FIX] mgmtsystem_review: Wrong mig script data version
  mgmtsystem_review/migrations/13.0.1.0.0/post-migration.py
Labels: bug, needs review, bot is merging ⏳

#498 [16.0][MIG] mgmtsystem_nonconformity_quality_control_oca
  mgmtsystem_nonconformity_quality_control_oca/README.rst
  mgmtsystem_nonconformity_quality_control_oca/__init__.py
  mgmtsystem_nonconformity_quality_control_oca/__manifest__.py
  mgmtsystem_nonconformity_quality_control_oca/i18n/it.po
  mgmtsystem_nonconformity_quality_control_oca/i18n/mgmtsystem_nonconformity_quality_control_oca.pot
  mgmtsystem_nonconformity_quality_control_oca/models/__init__.py
  mgmtsystem_nonconformity_quality_control_oca/models/mgmtsystem_nonconformity.py
  mgmtsystem_nonconformity_quality_control_oca/models/qc_inspection.py
  mgmtsystem_nonconformity_quality_control_oca/readme/CONTRIBUTORS.rst
  mgmtsystem_nonconformity_quality_control_oca/readme/DESCRIPTION.rst
  mgmtsystem_nonconformity_quality_control_oca/readme/USAGE.rst
  mgmtsystem_nonconformity_quality_control_oca/static/description/icon.png
  mgmtsystem_nonconformity_quality_control_oca/static/description/index.html
  mgmtsystem_nonconformity_quality_control_oca/tests/__init__.py
  mgmtsystem_nonconformity_quality_control_oca/tests/test_inspection.py
  mgmtsystem_nonconformity_quality_control_oca/views/mgmtsystem_nonconformity.xml
  mgmtsystem_nonconformity_quality_control_oca/views/qc_inspection.xml
  setup/mgmtsystem_nonconformity_quality_control_oca/odoo/addons/mgmtsystem_nonconformity_quality_control_oca
  setup/mgmtsystem_nonconformity_quality_control_oca/setup.py
Labels: needs review, migration, bot is merging ⏳

#523 [IMP] mgmtsystem_health_safety: __manifest__.py
  mgmtsystem_health_safety/__manifest__.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#536 [ADD] mgmtsystem_evaluation_hr
  mgmtsystem_evaluation_hr/README.rst
  mgmtsystem_evaluation_hr/__init__.py
  mgmtsystem_evaluation_hr/__manifest__.py
  mgmtsystem_evaluation_hr/models/__init__.py
  mgmtsystem_evaluation_hr/models/hr_employee.py
  mgmtsystem_evaluation_hr/readme/CONTRIBUTORS.rst
  mgmtsystem_evaluation_hr/readme/DESCRIPTION.rst
  mgmtsystem_evaluation_hr/static/description/icon.png
  mgmtsystem_evaluation_hr/static/description/index.html
  mgmtsystem_evaluation_hr/views/hr_employee.xml
  setup/mgmtsystem_evaluation_hr/odoo/addons/mgmtsystem_evaluation_hr
  setup/mgmtsystem_evaluation_hr/setup.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#535 [FIX] mgmtsystem_claim: Claim form view
  mgmtsystem_claim/views/mgmtsystem_claim.xml
Labels: bug, needs review, bot is merging ⏳
