Repository OCA/management-system, pull requests merged in 2023-10, with the labels that each got.

#538 [IMP] mgmtsystem_audit: Model create multi
  mgmtsystem_audit/models/mgmtsystem_audit.py
Labels: enhancement, needs review, bot is merging ⏳

#539 [IMP] mgmtsystem_nonconformity: Model create multi
  mgmtsystem_nonconformity/models/mgmtsystem_nonconformity.py
Labels: enhancement, needs review, bot is merging ⏳

#541 [FW][13.0] nonconformity_stage : state field changed to non ReadOnly
  mgmtsystem_nonconformity/models/mgmtsystem_nonconformity_stage.py
  mgmtsystem_nonconformity/views/mgmtsystem_nonconformity_stage.xml
Labels: bot is merging ⏳

#544 [FW][16.0] mgmtsystem_nonconformity: State field changed to non readonly on stage
  mgmtsystem_nonconformity/models/mgmtsystem_nonconformity_stage.py
  mgmtsystem_nonconformity/views/mgmtsystem_nonconformity_stage.xml
Labels: bug, needs review, approved, bot is merging ⏳

#543 [FW][15.0] mgmtsystem_nonconformity: State field changed to non readonly on stage
  mgmtsystem_nonconformity/models/mgmtsystem_nonconformity_stage.py
  mgmtsystem_nonconformity/views/mgmtsystem_nonconformity_stage.xml
Labels: bug, needs review, approved, bot is merging ⏳

#542 [FIX][14.0] mgmtsystem_nonconformity : State field changed to non readonly on stage
  mgmtsystem_nonconformity/models/mgmtsystem_nonconformity_stage.py
  mgmtsystem_nonconformity/views/mgmtsystem_nonconformity_stage.xml
Labels: bug, needs review, approved, bot is merging ⏳

#548 [14.0] Add missing noupdate flag on nonconformity stages
  mgmtsystem_nonconformity/data/mgmtsystem_nonconformity_stage.xml
  mgmtsystem_nonconformity/migrations/14.0.2.1.0/pre-migrate.py
Labels: approved, bot is merging ⏳

#550 [FW][16.0] Add missing noupdate flag on nonconformity stages
  mgmtsystem_nonconformity/data/mgmtsystem_nonconformity_stage.xml
  mgmtsystem_nonconformity/migrations/16.0.1.1.0/pre-migrate.py
Labels: approved, bot is merging ⏳
