Repository OCA/management-system, pull requests merged in 2024-04, with the labels that each got.

#577 [16.0][ADD] mgmtsystem_hazard_maintenance_equipment: add new module
  mgmtsystem_hazard_maintenance_equipment/README.rst
  mgmtsystem_hazard_maintenance_equipment/__init__.py
  mgmtsystem_hazard_maintenance_equipment/__manifest__.py
  mgmtsystem_hazard_maintenance_equipment/models/__init__.py
  mgmtsystem_hazard_maintenance_equipment/models/mgmtsystem_hazard.py
  mgmtsystem_hazard_maintenance_equipment/readme/CONTRIBUTORS.rst
  mgmtsystem_hazard_maintenance_equipment/readme/DESCRIPTION.rst
  mgmtsystem_hazard_maintenance_equipment/readme/USAGE.rst
  mgmtsystem_hazard_maintenance_equipment/static/description/icon.png
  mgmtsystem_hazard_maintenance_equipment/static/description/index.html
  mgmtsystem_hazard_maintenance_equipment/views/mgmtsystem_hazard.xml
  setup/mgmtsystem_hazard_maintenance_equipment/odoo/addons/mgmtsystem_hazard_maintenance_equipment
  setup/mgmtsystem_hazard_maintenance_equipment/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#563 [17.0][MIG] document_page_procedure: Migration to 17.0
  document_page_procedure/README.rst
  document_page_procedure/__init__.py
  document_page_procedure/__manifest__.py
  document_page_procedure/data/document_page_procedure.xml
  document_page_procedure/demo/document_page_procedure.xml
  document_page_procedure/i18n/de.po
  document_page_procedure/i18n/document_page_procedure.pot
  document_page_procedure/i18n/es.po
  document_page_procedure/i18n/es_CO.po
  document_page_procedure/i18n/fr.po
  document_page_procedure/i18n/hr.po
  document_page_procedure/i18n/hr_HR.po
  document_page_procedure/i18n/hu.po
  document_page_procedure/i18n/it.po
  document_page_procedure/i18n/nb.po
  document_page_procedure/i18n/nl_NL.po
  document_page_procedure/i18n/pt.po
  document_page_procedure/i18n/pt_BR.po
  document_page_procedure/i18n/sl.po
  document_page_procedure/i18n/sv.po
  document_page_procedure/i18n/vi.po
  document_page_procedure/pyproject.toml
  document_page_procedure/readme/CONFIGURE.md
  document_page_procedure/readme/CONTRIBUTORS.md
  document_page_procedure/readme/CREDITS.md
  document_page_procedure/readme/DESCRIPTION.md
  document_page_procedure/static/description/icon.png
  document_page_procedure/static/description/index.html
  document_page_procedure/views/document_page_procedure.xml
Labels: bot is merging ⏳, stale

#578 [FIX] mgmtsystem_action_efficacy track_visibility no more exists
  mgmtsystem_action_efficacy/models/mgmtsystem_action_efficacy.py
Labels: bot is merging ⏳
