Repository OCA/management-system, pull requests merged in 2024-09, with the labels that each got.

#583 [17.0] [MIG] mgmtsystem_survey
  mgmtsystem_survey/README.rst
  mgmtsystem_survey/__init__.py
  mgmtsystem_survey/__manifest__.py
  mgmtsystem_survey/i18n/de.po
  mgmtsystem_survey/i18n/es.po
  mgmtsystem_survey/i18n/es_CO.po
  mgmtsystem_survey/i18n/fi.po
  mgmtsystem_survey/i18n/fr.po
  mgmtsystem_survey/i18n/hr_HR.po
  mgmtsystem_survey/i18n/hu.po
  mgmtsystem_survey/i18n/it.po
  mgmtsystem_survey/i18n/lv.po
  mgmtsystem_survey/i18n/mgmtsystem_survey.pot
  mgmtsystem_survey/i18n/nb.po
  mgmtsystem_survey/i18n/nn.po
  mgmtsystem_survey/i18n/pt.po
  mgmtsystem_survey/i18n/pt_BR.po
  mgmtsystem_survey/i18n/sl.po
  mgmtsystem_survey/i18n/sv.po
  mgmtsystem_survey/i18n/th.po
  mgmtsystem_survey/i18n/tr.po
  mgmtsystem_survey/i18n/vi.po
  mgmtsystem_survey/models/__init__.py
  mgmtsystem_survey/pyproject.toml
  mgmtsystem_survey/readme/CONFIGURE.md
  mgmtsystem_survey/readme/CONTRIBUTORS.md
  mgmtsystem_survey/readme/CREDITS.md
  mgmtsystem_survey/readme/DESCRIPTION.md
  mgmtsystem_survey/readme/USAGE.md
  mgmtsystem_survey/static/description/icon.png
  mgmtsystem_survey/static/description/index.html
  mgmtsystem_survey/views/survey_survey.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#589 [17.0] [MIG] mgmtsystem_action
  mgmtsystem_action/README.rst
  mgmtsystem_action/__init__.py
  mgmtsystem_action/__manifest__.py
  mgmtsystem_action/data/action_sequence.xml
  mgmtsystem_action/data/automated_reminder.xml
  mgmtsystem_action/data/email_template.xml
  mgmtsystem_action/data/mgmtsystem_action_stage.xml
  mgmtsystem_action/demo/mgmtsystem_action.xml
  mgmtsystem_action/i18n/am.po
  mgmtsystem_action/i18n/ca.po
  mgmtsystem_action/i18n/de.po
  mgmtsystem_action/i18n/el_GR.po
  mgmtsystem_action/i18n/es.po
  mgmtsystem_action/i18n/es_CO.po
  mgmtsystem_action/i18n/es_ES.po
  mgmtsystem_action/i18n/fi.po
  mgmtsystem_action/i18n/fr.po
  mgmtsystem_action/i18n/gl.po
  mgmtsystem_action/i18n/hr_HR.po
  mgmtsystem_action/i18n/hu.po
  mgmtsystem_action/i18n/it.po
  mgmtsystem_action/i18n/lv.po
  mgmtsystem_action/i18n/mgmtsystem_action.pot
  mgmtsystem_action/i18n/nb.po
  mgmtsystem_action/i18n/nl.po
  mgmtsystem_action/i18n/nl_NL.po
  mgmtsystem_action/i18n/nn.po
  mgmtsystem_action/i18n/pt.po
  mgmtsystem_action/i18n/pt_BR.po
  mgmtsystem_action/i18n/pt_PT.po
  mgmtsystem_action/i18n/sl.po
  mgmtsystem_action/i18n/sv.po
  mgmtsystem_action/i18n/th.po
  mgmtsystem_action/i18n/tr.po
  mgmtsystem_action/i18n/vi.po
  mgmtsystem_action/models/__init__.py
  mgmtsystem_action/models/mgmtsystem_action.py
  mgmtsystem_action/models/mgmtsystem_action_stage.py
  mgmtsystem_action/models/mgmtsystem_action_tag.py
  mgmtsystem_action/pyproject.toml
  mgmtsystem_action/readme/CONFIGURE.md
  mgmtsystem_action/readme/CONTRIBUTORS.md
  mgmtsystem_action/readme/CREDITS.md
  mgmtsystem_action/readme/DESCRIPTION.md
  mgmtsystem_action/readme/INSTALL.md
  mgmtsystem_action/readme/USAGE.md
  mgmtsystem_action/reports/__init__.py
  mgmtsystem_action/reports/mgmtsystem_action_report.py
  mgmtsystem_action/reports/mgmtsystem_action_report.xml
  mgmtsystem_action/security/ir.model.access.csv
  mgmtsystem_action/security/mgmtsystem_action_security.xml
  mgmtsystem_action/static/description/icon.png
  mgmtsystem_action/static/description/index.html
  mgmtsystem_action/tests/__init__.py
  mgmtsystem_action/tests/test_create_action.py
  mgmtsystem_action/views/menus.xml
  mgmtsystem_action/views/mgmtsystem_action.xml
  mgmtsystem_action/views/mgmtsystem_action_stage.xml
  mgmtsystem_action/views/mgmtsystem_action_tag.xml
Labels: needs review, approved, migration, bot is merging ⏳

#582 [17.0] [MIG] document_page_health_safety_manual
  document_page_health_safety_manual/README.rst
  document_page_health_safety_manual/__init__.py
  document_page_health_safety_manual/__manifest__.py
  document_page_health_safety_manual/data/document_page.xml
  document_page_health_safety_manual/i18n/document_page_health_safety_manual.pot
  document_page_health_safety_manual/i18n/it.po
  document_page_health_safety_manual/pyproject.toml
  document_page_health_safety_manual/readme/CONTRIBUTORS.md
  document_page_health_safety_manual/readme/DESCRIPTION.md
  document_page_health_safety_manual/readme/ROADMAP.md
  document_page_health_safety_manual/readme/USAGE.md
  document_page_health_safety_manual/static/description/icon.png
  document_page_health_safety_manual/static/description/index.html
Labels: needs review, migration, bot is merging ⏳

#580 [17.0] [MIG] document_page_environment_manual
  document_page_environment_manual/README.rst
  document_page_environment_manual/__init__.py
  document_page_environment_manual/__manifest__.py
  document_page_environment_manual/data/document_page_environment_manual.xml
  document_page_environment_manual/i18n/de.po
  document_page_environment_manual/i18n/document_page_environment_manual.pot
  document_page_environment_manual/i18n/fr.po
  document_page_environment_manual/i18n/it.po
  document_page_environment_manual/i18n/nb.po
  document_page_environment_manual/i18n/pt_BR.po
  document_page_environment_manual/i18n/sl.po
  document_page_environment_manual/i18n/sv.po
  document_page_environment_manual/i18n/vi.po
  document_page_environment_manual/pyproject.toml
  document_page_environment_manual/readme/CONTRIBUTORS.md
  document_page_environment_manual/readme/DESCRIPTION.md
  document_page_environment_manual/readme/USAGE.md
  document_page_environment_manual/static/description/icon.png
  document_page_environment_manual/static/description/index.html
Labels: needs review, migration, bot is merging ⏳

#598 [IMP] mgmtsystem: Documentation
  mgmtsystem/readme/DESCRIPTION.md
Labels: needs review, approved, bot is merging ⏳
