Repository OCA/management-system, pull requests merged in 2024-12, with the labels that each got.

#606 [18.0][MIG] mgmtsystem_manual: Migration to 18.0
  mgmtsystem_manual/README.rst
  mgmtsystem_manual/__init__.py
  mgmtsystem_manual/__manifest__.py
  mgmtsystem_manual/data/mgmtsystem_manual.xml
  mgmtsystem_manual/i18n/de.po
  mgmtsystem_manual/i18n/es.po
  mgmtsystem_manual/i18n/fr.po
  mgmtsystem_manual/i18n/hr_HR.po
  mgmtsystem_manual/i18n/it.po
  mgmtsystem_manual/i18n/lv.po
  mgmtsystem_manual/i18n/mgmtsystem_manual.pot
  mgmtsystem_manual/i18n/nb.po
  mgmtsystem_manual/i18n/nl_NL.po
  mgmtsystem_manual/i18n/nn.po
  mgmtsystem_manual/i18n/pt_BR.po
  mgmtsystem_manual/i18n/sl.po
  mgmtsystem_manual/i18n/sv.po
  mgmtsystem_manual/i18n/th.po
  mgmtsystem_manual/i18n/vi.po
  mgmtsystem_manual/models/__init__.py
  mgmtsystem_manual/models/mgmtsystem_manual.py
  mgmtsystem_manual/pyproject.toml
  mgmtsystem_manual/readme/CONFIGURE.md
  mgmtsystem_manual/readme/CONTRIBUTORS.md
  mgmtsystem_manual/readme/CREDITS.md
  mgmtsystem_manual/readme/DESCRIPTION.md
  mgmtsystem_manual/readme/HISTORY.md
  mgmtsystem_manual/readme/INSTALL.md
  mgmtsystem_manual/readme/USAGE.md
  mgmtsystem_manual/static/description/icon.png
  mgmtsystem_manual/static/description/index.html
  mgmtsystem_manual/views/document_page.xml
  mgmtsystem_manual/views/mgmtsystem_manual.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#608 [18.0][MIG] document_page_quality_manual: Migration to 18.0
  document_page_quality_manual/README.rst
  document_page_quality_manual/__init__.py
  document_page_quality_manual/__manifest__.py
  document_page_quality_manual/data/document_page.xml
  document_page_quality_manual/i18n/ar.po
  document_page_quality_manual/i18n/bg.po
  document_page_quality_manual/i18n/ca.po
  document_page_quality_manual/i18n/cs.po
  document_page_quality_manual/i18n/da.po
  document_page_quality_manual/i18n/de.po
  document_page_quality_manual/i18n/document_page_quality_manual.pot
  document_page_quality_manual/i18n/es.po
  document_page_quality_manual/i18n/es_CR.po
  document_page_quality_manual/i18n/es_MX.po
  document_page_quality_manual/i18n/es_VE.po
  document_page_quality_manual/i18n/fa.po
  document_page_quality_manual/i18n/fi.po
  document_page_quality_manual/i18n/fr.po
  document_page_quality_manual/i18n/gl.po
  document_page_quality_manual/i18n/hr.po
  document_page_quality_manual/i18n/hu.po
  document_page_quality_manual/i18n/it.po
  document_page_quality_manual/i18n/ja.po
  document_page_quality_manual/i18n/lv.po
  document_page_quality_manual/i18n/mn.po
  document_page_quality_manual/i18n/nb.po
  document_page_quality_manual/i18n/nl.po
  document_page_quality_manual/i18n/oc.po
  document_page_quality_manual/i18n/pt.po
  document_page_quality_manual/i18n/pt_BR.po
  document_page_quality_manual/i18n/ro.po
  document_page_quality_manual/i18n/ru.po
  document_page_quality_manual/i18n/sk.po
  document_page_quality_manual/i18n/sl.po
  document_page_quality_manual/i18n/sr@latin.po
  document_page_quality_manual/i18n/sv.po
  document_page_quality_manual/i18n/tr.po
  document_page_quality_manual/i18n/vi.po
  document_page_quality_manual/i18n/zh_CN.po
  document_page_quality_manual/pyproject.toml
  document_page_quality_manual/readme/CONFIGURE.md
  document_page_quality_manual/readme/CONTRIBUTORS.md
  document_page_quality_manual/readme/CREDITS.md
  document_page_quality_manual/readme/DESCRIPTION.md
  document_page_quality_manual/readme/USAGE.md
  document_page_quality_manual/static/description/icon.png
  document_page_quality_manual/static/description/index.html
  document_page_quality_manual/static/description/quality_manual_form.png
Labels: needs review, migration, bot is merging ⏳

#607 [18.0][MIG] document_page_work_instruction: Migration to 18.0
  checklog-odoo.cfg
  document_page_work_instruction/README.rst
  document_page_work_instruction/__init__.py
  document_page_work_instruction/__manifest__.py
  document_page_work_instruction/data/document_page.xml
  document_page_work_instruction/i18n/de.po
  document_page_work_instruction/i18n/document_page_work_instruction.pot
  document_page_work_instruction/i18n/es.po
  document_page_work_instruction/i18n/es_CO.po
  document_page_work_instruction/i18n/fa.po
  document_page_work_instruction/i18n/fr.po
  document_page_work_instruction/i18n/hr_HR.po
  document_page_work_instruction/i18n/it.po
  document_page_work_instruction/i18n/nb.po
  document_page_work_instruction/i18n/nl_NL.po
  document_page_work_instruction/i18n/nn.po
  document_page_work_instruction/i18n/no.po
  document_page_work_instruction/i18n/pt_BR.po
  document_page_work_instruction/i18n/sl.po
  document_page_work_instruction/i18n/sv.po
  document_page_work_instruction/i18n/vi.po
  document_page_work_instruction/pyproject.toml
  document_page_work_instruction/readme/CONFIGURE.md
  document_page_work_instruction/readme/CONTRIBUTORS.md
  document_page_work_instruction/readme/CREDITS.md
  document_page_work_instruction/readme/DESCRIPTION.md
  document_page_work_instruction/static/description/icon.png
  document_page_work_instruction/static/description/index.html
  document_page_work_instruction/views/document_page_work_instructions.xml
Labels: needs review, approved, migration, bot is merging ⏳

#617 [14.0][FIX] mgmtsystem_evaluation: import cron
  mgmtsystem_evaluation/__manifest__.py
  mgmtsystem_evaluation/data/cron.xml
Labels: enhancement, needs review, approved, bot is merging ⏳
