Repository OCA/management-system, pull requests merged in 2024-10, with the labels that each got.

#601 [IMP] mgmtsystem: Add video recording of 2024 OCA Days
  mgmtsystem/readme/DESCRIPTION.md
Labels: enhancement, needs review, approved, bot is merging ⏳

#597 [MIG][17.0] mgmtsystem_review
  mgmtsystem_review/README.rst
  mgmtsystem_review/__init__.py
  mgmtsystem_review/__manifest__.py
  mgmtsystem_review/data/ir_sequence.xml
  mgmtsystem_review/i18n/am.po
  mgmtsystem_review/i18n/ca.po
  mgmtsystem_review/i18n/de.po
  mgmtsystem_review/i18n/el_GR.po
  mgmtsystem_review/i18n/es.po
  mgmtsystem_review/i18n/es_CO.po
  mgmtsystem_review/i18n/es_ES.po
  mgmtsystem_review/i18n/fi.po
  mgmtsystem_review/i18n/fr.po
  mgmtsystem_review/i18n/gl.po
  mgmtsystem_review/i18n/hr_HR.po
  mgmtsystem_review/i18n/hu.po
  mgmtsystem_review/i18n/it.po
  mgmtsystem_review/i18n/lv.po
  mgmtsystem_review/i18n/mgmtsystem_review.pot
  mgmtsystem_review/i18n/nb.po
  mgmtsystem_review/i18n/nl.po
  mgmtsystem_review/i18n/nl_NL.po
  mgmtsystem_review/i18n/nn.po
  mgmtsystem_review/i18n/pt.po
  mgmtsystem_review/i18n/pt_BR.po
  mgmtsystem_review/i18n/pt_PT.po
  mgmtsystem_review/i18n/sl.po
  mgmtsystem_review/i18n/sv.po
  mgmtsystem_review/i18n/th.po
  mgmtsystem_review/i18n/tr.po
  mgmtsystem_review/i18n/vi.po
  mgmtsystem_review/models/__init__.py
  mgmtsystem_review/models/mgmtsystem_review.py
  mgmtsystem_review/models/mgmtsystem_review_line.py
  mgmtsystem_review/pyproject.toml
  mgmtsystem_review/readme/CONTRIBUTORS.md
  mgmtsystem_review/readme/CREDITS.md
  mgmtsystem_review/readme/DESCRIPTION.md
  mgmtsystem_review/readme/USAGE.md
  mgmtsystem_review/report/report.xml
  mgmtsystem_review/report/review.xml
  mgmtsystem_review/security/ir.model.access.csv
  mgmtsystem_review/security/mgmtsystem_review_security.xml
  mgmtsystem_review/static/description/icon.png
  mgmtsystem_review/static/description/index.html
  mgmtsystem_review/tests/__init__.py
  mgmtsystem_review/tests/test_create_review.py
  mgmtsystem_review/views/mgmtsystem_review.xml
  mgmtsystem_review/views/res_users.xml
Labels: needs review, migration, bot is merging ⏳

#590 [17.0] [MIG] mgmtsystem_audit
  mgmtsystem_audit/README.rst
  mgmtsystem_audit/__init__.py
  mgmtsystem_audit/__manifest__.py
  mgmtsystem_audit/data/audit_automated_actions.xml
  mgmtsystem_audit/data/audit_sequence.xml
  mgmtsystem_audit/demo/demo_audit.xml
  mgmtsystem_audit/i18n/am.po
  mgmtsystem_audit/i18n/ca.po
  mgmtsystem_audit/i18n/de.po
  mgmtsystem_audit/i18n/el_GR.po
  mgmtsystem_audit/i18n/es.po
  mgmtsystem_audit/i18n/es_CO.po
  mgmtsystem_audit/i18n/es_ES.po
  mgmtsystem_audit/i18n/fi.po
  mgmtsystem_audit/i18n/fr.po
  mgmtsystem_audit/i18n/gl.po
  mgmtsystem_audit/i18n/hr_HR.po
  mgmtsystem_audit/i18n/hu.po
  mgmtsystem_audit/i18n/it.po
  mgmtsystem_audit/i18n/lv.po
  mgmtsystem_audit/i18n/mgmtsystem_audit.pot
  mgmtsystem_audit/i18n/nb.po
  mgmtsystem_audit/i18n/nl.po
  mgmtsystem_audit/i18n/nl_NL.po
  mgmtsystem_audit/i18n/nn.po
  mgmtsystem_audit/i18n/pt.po
  mgmtsystem_audit/i18n/pt_BR.po
  mgmtsystem_audit/i18n/pt_PT.po
  mgmtsystem_audit/i18n/sl.po
  mgmtsystem_audit/i18n/sv.po
  mgmtsystem_audit/i18n/tr.po
  mgmtsystem_audit/i18n/vi.po
  mgmtsystem_audit/models/__init__.py
  mgmtsystem_audit/models/mgmtsystem_audit.py
  mgmtsystem_audit/models/mgmtsystem_nonconformity.py
  mgmtsystem_audit/models/mgmtsystem_verification_line.py
  mgmtsystem_audit/pyproject.toml
  mgmtsystem_audit/readme/CONFIGURE.md
  mgmtsystem_audit/readme/CONTRIBUTORS.md
  mgmtsystem_audit/readme/DESCRIPTION.md
  mgmtsystem_audit/readme/USAGE.md
  mgmtsystem_audit/report/audit.xml
  mgmtsystem_audit/report/mgmtsystem_audit_pivot.xml
  mgmtsystem_audit/report/report.xml
  mgmtsystem_audit/report/verification.xml
  mgmtsystem_audit/security/ir.model.access.csv
  mgmtsystem_audit/security/mgmtsystem_audit_security.xml
  mgmtsystem_audit/static/description/icon.png
  mgmtsystem_audit/static/description/index.html
  mgmtsystem_audit/tests/__init__.py
  mgmtsystem_audit/tests/test_audit.py
  mgmtsystem_audit/tests/test_copy_verification_lines.py
  mgmtsystem_audit/views/mgmtsystem_audit.xml
  mgmtsystem_audit/views/res_users.xml
  mgmtsystem_audit/wizard/__init__.py
  mgmtsystem_audit/wizard/copy_verification_lines.py
  mgmtsystem_audit/wizard/copy_verification_lines.xml
Labels: needs review, needs fixing, migration, bot is merging ⏳
