Repository OCA/management-system, pull requests merged in 2025-04, with the labels that each got.

#655 [16.0][MIG] mgmtsystem_evaluation_hr: migration to 16.0
  mgmtsystem_evaluation_hr/README.rst
  mgmtsystem_evaluation_hr/__init__.py
  mgmtsystem_evaluation_hr/__manifest__.py
  mgmtsystem_evaluation_hr/i18n/es.po
  mgmtsystem_evaluation_hr/i18n/it.po
  mgmtsystem_evaluation_hr/i18n/mgmtsystem_evaluation_hr.pot
  mgmtsystem_evaluation_hr/models/__init__.py
  mgmtsystem_evaluation_hr/models/hr_employee.py
  mgmtsystem_evaluation_hr/readme/CONTRIBUTORS.rst
  mgmtsystem_evaluation_hr/readme/DESCRIPTION.rst
  mgmtsystem_evaluation_hr/static/description/icon.png
  mgmtsystem_evaluation_hr/static/description/index.html
  mgmtsystem_evaluation_hr/views/hr_employee.xml
  setup/mgmtsystem_evaluation_hr/odoo/addons/mgmtsystem_evaluation_hr
  setup/mgmtsystem_evaluation_hr/setup.py
Labels: needs fixing, approved, bot is merging ⏳

#615 [10.0][FIX] mgmtsystem_audit: Improve Expected singleton error
  mgmtsystem_audit/models/mgmtsystem_audit.py
Labels: bug, needs review, approved, bot is merging ⏳

#616 [9.0][FIX] mgmtsystem_audit: Improve Expected singleton error
  mgmtsystem_audit/models/mgmtsystem_audit.py
Labels: bug, needs review, approved, bot is merging ⏳

#672 [17.0][MIG] mgmtsystem_nonconformity_hr
  mgmtsystem_nonconformity_hr/README.rst
  mgmtsystem_nonconformity_hr/__init__.py
  mgmtsystem_nonconformity_hr/__manifest__.py
  mgmtsystem_nonconformity_hr/i18n/es.po
  mgmtsystem_nonconformity_hr/i18n/fa.po
  mgmtsystem_nonconformity_hr/i18n/fr.po
  mgmtsystem_nonconformity_hr/i18n/it.po
  mgmtsystem_nonconformity_hr/i18n/mgmtsystem_nonconformity_hr.pot
  mgmtsystem_nonconformity_hr/i18n/pt.po
  mgmtsystem_nonconformity_hr/models/__init__.py
  mgmtsystem_nonconformity_hr/models/mgmtsystem_nonconformity_hr.py
  mgmtsystem_nonconformity_hr/pyproject.toml
  mgmtsystem_nonconformity_hr/readme/CONTRIBUTORS.md
  mgmtsystem_nonconformity_hr/readme/DESCRIPTION.md
  mgmtsystem_nonconformity_hr/readme/HISTORY.md
  mgmtsystem_nonconformity_hr/readme/USAGE.md
  mgmtsystem_nonconformity_hr/static/description/icon.png
  mgmtsystem_nonconformity_hr/static/description/index.html
  mgmtsystem_nonconformity_hr/views/mgmtsystem_nonconformity_views.xml
  oca-dependencies.txt
Labels: bot is merging ⏳

#657 [18.0][MIG] mgmtsystem_quality: Migration to 18.0
  mgmtsystem_quality/README.rst
  mgmtsystem_quality/__init__.py
  mgmtsystem_quality/__manifest__.py
  mgmtsystem_quality/data/mgmtsystem_system.xml
  mgmtsystem_quality/i18n/de.po
  mgmtsystem_quality/i18n/fr.po
  mgmtsystem_quality/i18n/it.po
  mgmtsystem_quality/i18n/mgmtsystem_quality.pot
  mgmtsystem_quality/i18n/nb.po
  mgmtsystem_quality/i18n/pt_BR.po
  mgmtsystem_quality/i18n/sv.po
  mgmtsystem_quality/i18n/vi.po
  mgmtsystem_quality/pyproject.toml
  mgmtsystem_quality/readme/CONFIGURE.md
  mgmtsystem_quality/readme/CONTRIBUTORS.md
  mgmtsystem_quality/readme/DESCRIPTION.md
  mgmtsystem_quality/readme/ROADMAP.md
  mgmtsystem_quality/readme/USAGE.md
  mgmtsystem_quality/static/description/icon.png
  mgmtsystem_quality/static/description/index.html
Labels: needs review, migration, bot is merging ⏳
