Repository OCA/management-system, pull requests merged in 2025-03, with the labels that each got.

#656 [18.0][REF] dotfiles fix
  checklog-odoo.cfg
Labels: needs review, bot is merging ⏳

#666 [FIX] mgmtsystem_review: Line tree view
  mgmtsystem_review/views/mgmtsystem_review.xml
Labels: bug, needs review, approved, bot is merging ⏳

#665 [FIX] mgmtsystem: Settings show up in General Settings
  mgmtsystem/views/res_config.xml
  mgmtsystem_hazard_risk/views/res_config_settings_views.xml
Labels: bug, needs review, bot is merging ⏳

#671 [FIX] mgmtsystem_evaluation: Model must be searched with sudo
  mgmtsystem_evaluation/models/mgmtsystem_evaluation.py
Labels: approved, bot is merging ⏳
