Repository OCA/management-system, pull requests merged in 2025-01, with the labels that each got.

#612 [18.0][MIG] mgmtsystem_review: Migration to 18.0
  mgmtsystem_review/README.rst
  mgmtsystem_review/__init__.py
  mgmtsystem_review/__manifest__.py
  mgmtsystem_review/data/ir_sequence.xml
  mgmtsystem_review/i18n/am.po
  mgmtsystem_review/i18n/ca.po
  mgmtsystem_review/i18n/de.po
  mgmtsystem_review/i18n/el_GR.po
  mgmtsystem_review/i18n/es.po
  mgmtsystem_review/i18n/es_CO.po
  mgmtsystem_review/i18n/es_ES.po
  mgmtsystem_review/i18n/fi.po
  mgmtsystem_review/i18n/fr.po
  mgmtsystem_review/i18n/gl.po
  mgmtsystem_review/i18n/hr_HR.po
  mgmtsystem_review/i18n/hu.po
  mgmtsystem_review/i18n/it.po
  mgmtsystem_review/i18n/lv.po
  mgmtsystem_review/i18n/mgmtsystem_review.pot
  mgmtsystem_review/i18n/nb.po
  mgmtsystem_review/i18n/nl.po
  mgmtsystem_review/i18n/nl_NL.po
  mgmtsystem_review/i18n/nn.po
  mgmtsystem_review/i18n/pt.po
  mgmtsystem_review/i18n/pt_BR.po
  mgmtsystem_review/i18n/pt_PT.po
  mgmtsystem_review/i18n/sl.po
  mgmtsystem_review/i18n/sv.po
  mgmtsystem_review/i18n/th.po
  mgmtsystem_review/i18n/tr.po
  mgmtsystem_review/i18n/vi.po
  mgmtsystem_review/models/__init__.py
  mgmtsystem_review/models/mgmtsystem_review.py
  mgmtsystem_review/models/mgmtsystem_review_line.py
  mgmtsystem_review/pyproject.toml
  mgmtsystem_review/readme/CONTRIBUTORS.md
  mgmtsystem_review/readme/CREDITS.md
  mgmtsystem_review/readme/DESCRIPTION.md
  mgmtsystem_review/readme/USAGE.md
  mgmtsystem_review/report/report.xml
  mgmtsystem_review/report/review.xml
  mgmtsystem_review/security/ir.model.access.csv
  mgmtsystem_review/security/mgmtsystem_review_security.xml
  mgmtsystem_review/static/description/icon.png
  mgmtsystem_review/static/description/index.html
  mgmtsystem_review/tests/__init__.py
  mgmtsystem_review/tests/test_create_review.py
  mgmtsystem_review/views/mgmtsystem_review.xml
  mgmtsystem_review/views/res_users.xml
Labels: needs review, approved, migration, bot is merging ⏳, blocked by dependency

#621 [17.0][FIX] mgmtsystem: Settings views
  mgmtsystem/views/res_config.xml
Labels: bug, approved, ready to merge, bot is merging ⏳

#633 [18.0][MIG] mgmtsystem_partner: Migration to 18.0
  mgmtsystem_partner/README.rst
  mgmtsystem_partner/__init__.py
  mgmtsystem_partner/__manifest__.py
  mgmtsystem_partner/i18n/es.po
  mgmtsystem_partner/i18n/fa.po
  mgmtsystem_partner/i18n/it.po
  mgmtsystem_partner/i18n/mgmtsystem_partner.pot
  mgmtsystem_partner/models/__init__.py
  mgmtsystem_partner/models/res_partner.py
  mgmtsystem_partner/pyproject.toml
  mgmtsystem_partner/readme/CONTRIBUTORS.md
  mgmtsystem_partner/readme/DESCRIPTION.md
  mgmtsystem_partner/readme/HISTORY.md
  mgmtsystem_partner/readme/USAGE.md
  mgmtsystem_partner/static/description/icon.png
  mgmtsystem_partner/static/description/index.html
Labels: approved, bot is merging ⏳

#640 [17.0][MIG] mgmtsystem_partner: Migration to 17.0
  mgmtsystem_partner/README.rst
  mgmtsystem_partner/__init__.py
  mgmtsystem_partner/__manifest__.py
  mgmtsystem_partner/i18n/es.po
  mgmtsystem_partner/i18n/fa.po
  mgmtsystem_partner/i18n/it.po
  mgmtsystem_partner/i18n/mgmtsystem_partner.pot
  mgmtsystem_partner/models/__init__.py
  mgmtsystem_partner/models/res_partner.py
  mgmtsystem_partner/pyproject.toml
  mgmtsystem_partner/readme/CONTRIBUTORS.md
  mgmtsystem_partner/readme/DESCRIPTION.md
  mgmtsystem_partner/readme/HISTORY.md
  mgmtsystem_partner/readme/USAGE.md
  mgmtsystem_partner/static/description/icon.png
  mgmtsystem_partner/static/description/index.html
Labels: approved, bot is merging ⏳

#635 [17.0][MIG] mgmtsystem_nonconformity_maintenance_equipment: Migration to 17.0
  mgmtsystem_nonconformity_maintenance_equipment/README.rst
  mgmtsystem_nonconformity_maintenance_equipment/__init__.py
  mgmtsystem_nonconformity_maintenance_equipment/__manifest__.py
  mgmtsystem_nonconformity_maintenance_equipment/i18n/it.po
  mgmtsystem_nonconformity_maintenance_equipment/i18n/mgmtsystem_nonconformity_maintenance_equipment.pot
  mgmtsystem_nonconformity_maintenance_equipment/models/__init__.py
  mgmtsystem_nonconformity_maintenance_equipment/models/mgmtsystem_nonconformity.py
  mgmtsystem_nonconformity_maintenance_equipment/pyproject.toml
  mgmtsystem_nonconformity_maintenance_equipment/readme/CONTRIBUTORS.md
  mgmtsystem_nonconformity_maintenance_equipment/readme/DESCRIPTION.md
  mgmtsystem_nonconformity_maintenance_equipment/readme/USAGE.md
  mgmtsystem_nonconformity_maintenance_equipment/static/description/icon.png
  mgmtsystem_nonconformity_maintenance_equipment/static/description/index.html
  mgmtsystem_nonconformity_maintenance_equipment/views/mgmtsystem_nonconformity.xml
Labels: approved, bot is merging ⏳

#632 [18.0][MIG] mgmtsystem_nonconformity_repair: Migration to 18.0
  mgmtsystem_nonconformity_repair/README.rst
  mgmtsystem_nonconformity_repair/__init__.py
  mgmtsystem_nonconformity_repair/__manifest__.py
  mgmtsystem_nonconformity_repair/i18n/es.po
  mgmtsystem_nonconformity_repair/i18n/it.po
  mgmtsystem_nonconformity_repair/i18n/mgmtsystem_nonconformity_repair.pot
  mgmtsystem_nonconformity_repair/i18n/pt_BR.po
  mgmtsystem_nonconformity_repair/models/__init__.py
  mgmtsystem_nonconformity_repair/models/mgmtsystem_nonconformity.py
  mgmtsystem_nonconformity_repair/models/repair_order.py
  mgmtsystem_nonconformity_repair/pyproject.toml
  mgmtsystem_nonconformity_repair/readme/CONTRIBUTORS.md
  mgmtsystem_nonconformity_repair/readme/DESCRIPTION.md
  mgmtsystem_nonconformity_repair/readme/USAGE.md
  mgmtsystem_nonconformity_repair/static/description/icon.png
  mgmtsystem_nonconformity_repair/static/description/index.html
  mgmtsystem_nonconformity_repair/tests/__init__.py
  mgmtsystem_nonconformity_repair/tests/test_nonconformity_repair.py
  mgmtsystem_nonconformity_repair/views/mgmtsystem_nonconformity.xml
Labels: approved, bot is merging ⏳

#637 [17.0][MIG] mgmtsystem_nonconformity_product: Migration to 17.0
  mgmtsystem_nonconformity_product/README.rst
  mgmtsystem_nonconformity_product/__init__.py
  mgmtsystem_nonconformity_product/__manifest__.py
  mgmtsystem_nonconformity_product/i18n/es.po
  mgmtsystem_nonconformity_product/i18n/fa.po
  mgmtsystem_nonconformity_product/i18n/it.po
  mgmtsystem_nonconformity_product/i18n/mgmtsystem_nonconformity_product.pot
  mgmtsystem_nonconformity_product/i18n/pt_BR.po
  mgmtsystem_nonconformity_product/models/__init__.py
  mgmtsystem_nonconformity_product/models/mgmtsystem_nonconformity.py
  mgmtsystem_nonconformity_product/pyproject.toml
  mgmtsystem_nonconformity_product/readme/CONTRIBUTORS.md
  mgmtsystem_nonconformity_product/readme/DESCRIPTION.md
  mgmtsystem_nonconformity_product/readme/HISTORY.md
  mgmtsystem_nonconformity_product/readme/USAGE.md
  mgmtsystem_nonconformity_product/static/description/icon.png
  mgmtsystem_nonconformity_product/static/description/index.html
  mgmtsystem_nonconformity_product/views/mgmtsystem_nonconformity_views.xml
Labels: approved, bot is merging ⏳

#636 [17.0][MIG] mgmtsystem_nonconformity_mrp: Migration to 17.0
  mgmtsystem_nonconformity_mrp/README.rst
  mgmtsystem_nonconformity_mrp/__init__.py
  mgmtsystem_nonconformity_mrp/__manifest__.py
  mgmtsystem_nonconformity_mrp/i18n/es.po
  mgmtsystem_nonconformity_mrp/i18n/fr.po
  mgmtsystem_nonconformity_mrp/i18n/it.po
  mgmtsystem_nonconformity_mrp/i18n/mgmtsystem_nonconformity_mrp.pot
  mgmtsystem_nonconformity_mrp/models/__init__.py
  mgmtsystem_nonconformity_mrp/models/mgmtsystem_nonconformity_mrp.py
  mgmtsystem_nonconformity_mrp/pyproject.toml
  mgmtsystem_nonconformity_mrp/readme/CONFIGURE.md
  mgmtsystem_nonconformity_mrp/readme/CONTRIBUTORS.md
  mgmtsystem_nonconformity_mrp/readme/DESCRIPTION.md
  mgmtsystem_nonconformity_mrp/readme/HISTORY.md
  mgmtsystem_nonconformity_mrp/readme/INSTALL.md
  mgmtsystem_nonconformity_mrp/readme/ROADMAP.md
  mgmtsystem_nonconformity_mrp/readme/USAGE.md
  mgmtsystem_nonconformity_mrp/static/description/icon.png
  mgmtsystem_nonconformity_mrp/static/description/index.html
  mgmtsystem_nonconformity_mrp/views/mgmtsystem_nonconformity_views.xml
Labels: approved, bot is merging ⏳

#630 [18.0][MIG] mgmtsystem_nonconformity_product: Migration to 18.0
  mgmtsystem_nonconformity_product/README.rst
  mgmtsystem_nonconformity_product/__init__.py
  mgmtsystem_nonconformity_product/__manifest__.py
  mgmtsystem_nonconformity_product/i18n/es.po
  mgmtsystem_nonconformity_product/i18n/fa.po
  mgmtsystem_nonconformity_product/i18n/it.po
  mgmtsystem_nonconformity_product/i18n/mgmtsystem_nonconformity_product.pot
  mgmtsystem_nonconformity_product/i18n/pt_BR.po
  mgmtsystem_nonconformity_product/models/__init__.py
  mgmtsystem_nonconformity_product/models/mgmtsystem_nonconformity.py
  mgmtsystem_nonconformity_product/pyproject.toml
  mgmtsystem_nonconformity_product/readme/CONTRIBUTORS.md
  mgmtsystem_nonconformity_product/readme/DESCRIPTION.md
  mgmtsystem_nonconformity_product/readme/HISTORY.md
  mgmtsystem_nonconformity_product/readme/USAGE.md
  mgmtsystem_nonconformity_product/static/description/icon.png
  mgmtsystem_nonconformity_product/static/description/index.html
  mgmtsystem_nonconformity_product/views/mgmtsystem_nonconformity_views.xml
Labels: bot is merging ⏳

#622 [18.0][MIG] document_page_environmental_aspect: Migration to 18.0
  document_page_environmental_aspect/README.rst
  document_page_environmental_aspect/__init__.py
  document_page_environmental_aspect/__manifest__.py
  document_page_environmental_aspect/data/document_page.xml
  document_page_environmental_aspect/i18n/de.po
  document_page_environmental_aspect/i18n/document_page_environmental_aspect.pot
  document_page_environmental_aspect/i18n/es.po
  document_page_environmental_aspect/i18n/es_CL.po
  document_page_environmental_aspect/i18n/fa.po
  document_page_environmental_aspect/i18n/fr.po
  document_page_environmental_aspect/i18n/it.po
  document_page_environmental_aspect/i18n/nb.po
  document_page_environmental_aspect/i18n/pt.po
  document_page_environmental_aspect/i18n/pt_BR.po
  document_page_environmental_aspect/i18n/sl.po
  document_page_environmental_aspect/i18n/sv.po
  document_page_environmental_aspect/i18n/vi.po
  document_page_environmental_aspect/pyproject.toml
  document_page_environmental_aspect/readme/CONFIGURE.md
  document_page_environmental_aspect/readme/CONTRIBUTORS.md
  document_page_environmental_aspect/readme/DESCRIPTION.md
  document_page_environmental_aspect/readme/USAGE.md
  document_page_environmental_aspect/static/description/icon.png
  document_page_environmental_aspect/static/description/index.html
  document_page_environmental_aspect/views/document_page.xml
Labels: approved, bot is merging ⏳

#627 [18.0][MIG] mgmtsystem_nonconformity_hr: Migration to 18.0
  mgmtsystem_nonconformity_hr/README.rst
  mgmtsystem_nonconformity_hr/__init__.py
  mgmtsystem_nonconformity_hr/__manifest__.py
  mgmtsystem_nonconformity_hr/i18n/es.po
  mgmtsystem_nonconformity_hr/i18n/fa.po
  mgmtsystem_nonconformity_hr/i18n/fr.po
  mgmtsystem_nonconformity_hr/i18n/it.po
  mgmtsystem_nonconformity_hr/i18n/mgmtsystem_nonconformity_hr.pot
  mgmtsystem_nonconformity_hr/i18n/pt.po
  mgmtsystem_nonconformity_hr/models/__init__.py
  mgmtsystem_nonconformity_hr/models/mgmtsystem_nonconformity_hr.py
  mgmtsystem_nonconformity_hr/pyproject.toml
  mgmtsystem_nonconformity_hr/readme/CONTRIBUTORS.md
  mgmtsystem_nonconformity_hr/readme/DESCRIPTION.md
  mgmtsystem_nonconformity_hr/readme/HISTORY.md
  mgmtsystem_nonconformity_hr/readme/USAGE.md
  mgmtsystem_nonconformity_hr/static/description/icon.png
  mgmtsystem_nonconformity_hr/static/description/index.html
  mgmtsystem_nonconformity_hr/views/mgmtsystem_nonconformity_views.xml
Labels: approved, bot is merging ⏳

#625 [18.0][MIG] mgmtsystem_info_security_manual: Migration to 18.0
  mgmtsystem_info_security_manual/README.rst
  mgmtsystem_info_security_manual/__init__.py
  mgmtsystem_info_security_manual/__manifest__.py
  mgmtsystem_info_security_manual/data/information_security_manual.xml
  mgmtsystem_info_security_manual/i18n/it.po
  mgmtsystem_info_security_manual/i18n/mgmtsystem_info_security_manual.pot
  mgmtsystem_info_security_manual/i18n/sv.po
  mgmtsystem_info_security_manual/pyproject.toml
  mgmtsystem_info_security_manual/readme/CONTRIBUTORS.md
  mgmtsystem_info_security_manual/readme/DESCRIPTION.md
  mgmtsystem_info_security_manual/readme/USAGE.md
  mgmtsystem_info_security_manual/static/description/icon.png
  mgmtsystem_info_security_manual/static/description/index.html
Labels: approved, bot is merging ⏳

#628 [18.0][MIG] mgmtsystem_nonconformity_maintenance_equipment: Migration to 18.0
  mgmtsystem_nonconformity_maintenance_equipment/README.rst
  mgmtsystem_nonconformity_maintenance_equipment/__init__.py
  mgmtsystem_nonconformity_maintenance_equipment/__manifest__.py
  mgmtsystem_nonconformity_maintenance_equipment/i18n/it.po
  mgmtsystem_nonconformity_maintenance_equipment/i18n/mgmtsystem_nonconformity_maintenance_equipment.pot
  mgmtsystem_nonconformity_maintenance_equipment/models/__init__.py
  mgmtsystem_nonconformity_maintenance_equipment/models/mgmtsystem_nonconformity.py
  mgmtsystem_nonconformity_maintenance_equipment/pyproject.toml
  mgmtsystem_nonconformity_maintenance_equipment/readme/CONTRIBUTORS.md
  mgmtsystem_nonconformity_maintenance_equipment/readme/DESCRIPTION.md
  mgmtsystem_nonconformity_maintenance_equipment/readme/USAGE.md
  mgmtsystem_nonconformity_maintenance_equipment/static/description/icon.png
  mgmtsystem_nonconformity_maintenance_equipment/static/description/index.html
  mgmtsystem_nonconformity_maintenance_equipment/views/mgmtsystem_nonconformity.xml
Labels: approved, bot is merging ⏳

#638 [17.0][MIG] mgmtsystem_nonconformity_quality_control_oca: Migration to 17.0
  mgmtsystem_nonconformity_quality_control_oca/README.rst
  mgmtsystem_nonconformity_quality_control_oca/__init__.py
  mgmtsystem_nonconformity_quality_control_oca/__manifest__.py
  mgmtsystem_nonconformity_quality_control_oca/i18n/es.po
  mgmtsystem_nonconformity_quality_control_oca/i18n/it.po
  mgmtsystem_nonconformity_quality_control_oca/i18n/mgmtsystem_nonconformity_quality_control_oca.pot
  mgmtsystem_nonconformity_quality_control_oca/models/__init__.py
  mgmtsystem_nonconformity_quality_control_oca/models/mgmtsystem_nonconformity.py
  mgmtsystem_nonconformity_quality_control_oca/models/qc_inspection.py
  mgmtsystem_nonconformity_quality_control_oca/pyproject.toml
  mgmtsystem_nonconformity_quality_control_oca/readme/CONTRIBUTORS.md
  mgmtsystem_nonconformity_quality_control_oca/readme/DESCRIPTION.md
  mgmtsystem_nonconformity_quality_control_oca/readme/USAGE.md
  mgmtsystem_nonconformity_quality_control_oca/static/description/icon.png
  mgmtsystem_nonconformity_quality_control_oca/static/description/index.html
  mgmtsystem_nonconformity_quality_control_oca/tests/__init__.py
  mgmtsystem_nonconformity_quality_control_oca/tests/test_inspection.py
  mgmtsystem_nonconformity_quality_control_oca/views/mgmtsystem_nonconformity.xml
  mgmtsystem_nonconformity_quality_control_oca/views/qc_inspection.xml
Labels: approved, bot is merging ⏳

#649 [18.0][MIG] mgmtsystem_nonconformity_type: Migration to 18.0
  mgmtsystem_nonconformity_type/README.rst
  mgmtsystem_nonconformity_type/__init__.py
  mgmtsystem_nonconformity_type/__manifest__.py
  mgmtsystem_nonconformity_type/data/mgmtsystem_nonconformity_mail_data.xml
  mgmtsystem_nonconformity_type/i18n/es.po
  mgmtsystem_nonconformity_type/i18n/fr.po
  mgmtsystem_nonconformity_type/i18n/it.po
  mgmtsystem_nonconformity_type/i18n/mgmtsystem_nonconformity_type.pot
  mgmtsystem_nonconformity_type/models/__init__.py
  mgmtsystem_nonconformity_type/models/mgmtsystem_nonconformity.py
  mgmtsystem_nonconformity_type/pyproject.toml
  mgmtsystem_nonconformity_type/readme/CONTRIBUTORS.md
  mgmtsystem_nonconformity_type/readme/DESCRIPTION.md
  mgmtsystem_nonconformity_type/readme/HISTORY.md
  mgmtsystem_nonconformity_type/readme/ROADMAP.md
  mgmtsystem_nonconformity_type/readme/USAGE.md
  mgmtsystem_nonconformity_type/static/description/icon.png
  mgmtsystem_nonconformity_type/static/description/index.html
  mgmtsystem_nonconformity_type/tests/__init__.py
  mgmtsystem_nonconformity_type/tests/test_nonconformity_type.py
  mgmtsystem_nonconformity_type/views/mgmtsystem_nonconformity_views.xml
Labels: approved, bot is merging ⏳

#642 [17.0][MIG] mgmtsystem_action_efficacy: Migration to 17.0
  mgmtsystem_action_efficacy/README.rst
  mgmtsystem_action_efficacy/__init__.py
  mgmtsystem_action_efficacy/__manifest__.py
  mgmtsystem_action_efficacy/i18n/es.po
  mgmtsystem_action_efficacy/i18n/fa.po
  mgmtsystem_action_efficacy/i18n/it.po
  mgmtsystem_action_efficacy/i18n/mgmtsystem_action_efficacy.pot
  mgmtsystem_action_efficacy/models/__init__.py
  mgmtsystem_action_efficacy/models/mgmtsystem_action.py
  mgmtsystem_action_efficacy/pyproject.toml
  mgmtsystem_action_efficacy/readme/CONTRIBUTORS.md
  mgmtsystem_action_efficacy/readme/DESCRIPTION.md
  mgmtsystem_action_efficacy/readme/HISTORY.md
  mgmtsystem_action_efficacy/readme/USAGE.md
  mgmtsystem_action_efficacy/static/description/icon.png
  mgmtsystem_action_efficacy/static/description/index.html
  mgmtsystem_action_efficacy/tests/__init__.py
  mgmtsystem_action_efficacy/tests/test_efficacy.py
  mgmtsystem_action_efficacy/views/mgmtsystem_action_views.xml
Labels: approved, bot is merging ⏳

#643 [17.0][MIG] mgmtsystem_action_template: Migration to 17.0
  mgmtsystem_action_template/README.rst
  mgmtsystem_action_template/__init__.py
  mgmtsystem_action_template/__manifest__.py
  mgmtsystem_action_template/i18n/es.po
  mgmtsystem_action_template/i18n/it.po
  mgmtsystem_action_template/i18n/mgmtsystem_action_template.pot
  mgmtsystem_action_template/models/__init__.py
  mgmtsystem_action_template/models/mgmtsystem_action.py
  mgmtsystem_action_template/models/mgmtsystem_action_template.py
  mgmtsystem_action_template/pyproject.toml
  mgmtsystem_action_template/readme/CONTRIBUTORS.md
  mgmtsystem_action_template/readme/DESCRIPTION.md
  mgmtsystem_action_template/readme/HISTORY.md
  mgmtsystem_action_template/readme/USAGE.md
  mgmtsystem_action_template/security/ir.model.access.csv
  mgmtsystem_action_template/static/description/icon.png
  mgmtsystem_action_template/static/description/index.html
  mgmtsystem_action_template/tests/__init__.py
  mgmtsystem_action_template/tests/test_action_template.py
  mgmtsystem_action_template/views/mgmtsystem_action_template.xml
  mgmtsystem_action_template/views/mgmtsystem_action_views.xml
Labels: bot is merging ⏳

#645 [18.0][MIG] document_page_health_safety_manual: Migration to 18.0
  document_page_health_safety_manual/README.rst
  document_page_health_safety_manual/__init__.py
  document_page_health_safety_manual/__manifest__.py
  document_page_health_safety_manual/data/document_page.xml
  document_page_health_safety_manual/i18n/document_page_health_safety_manual.pot
  document_page_health_safety_manual/i18n/it.po
  document_page_health_safety_manual/pyproject.toml
  document_page_health_safety_manual/readme/CONTRIBUTORS.md
  document_page_health_safety_manual/readme/DESCRIPTION.md
  document_page_health_safety_manual/readme/ROADMAP.md
  document_page_health_safety_manual/readme/USAGE.md
  document_page_health_safety_manual/static/description/icon.png
  document_page_health_safety_manual/static/description/index.html
Labels: bot is merging ⏳

#644 [17.0][MIG] mgmtsystem_nonconformity_type: Migration to 17.0
  mgmtsystem_nonconformity_type/README.rst
  mgmtsystem_nonconformity_type/__init__.py
  mgmtsystem_nonconformity_type/__manifest__.py
  mgmtsystem_nonconformity_type/data/mgmtsystem_nonconformity_mail_data.xml
  mgmtsystem_nonconformity_type/i18n/es.po
  mgmtsystem_nonconformity_type/i18n/fr.po
  mgmtsystem_nonconformity_type/i18n/it.po
  mgmtsystem_nonconformity_type/i18n/mgmtsystem_nonconformity_type.pot
  mgmtsystem_nonconformity_type/models/__init__.py
  mgmtsystem_nonconformity_type/models/mgmtsystem_nonconformity.py
  mgmtsystem_nonconformity_type/pyproject.toml
  mgmtsystem_nonconformity_type/readme/CONTRIBUTORS.md
  mgmtsystem_nonconformity_type/readme/DESCRIPTION.md
  mgmtsystem_nonconformity_type/readme/HISTORY.md
  mgmtsystem_nonconformity_type/readme/ROADMAP.md
  mgmtsystem_nonconformity_type/readme/USAGE.md
  mgmtsystem_nonconformity_type/static/description/icon.png
  mgmtsystem_nonconformity_type/static/description/index.html
  mgmtsystem_nonconformity_type/tests/__init__.py
  mgmtsystem_nonconformity_type/tests/test_nonconformity_type.py
  mgmtsystem_nonconformity_type/views/mgmtsystem_nonconformity_views.xml
Labels: bot is merging ⏳

#626 [18.0][MIG] mgmtsystem_nonconformity_hazard: Migration to 18.0
  mgmtsystem_nonconformity_hazard/README.rst
  mgmtsystem_nonconformity_hazard/__init__.py
  mgmtsystem_nonconformity_hazard/__manifest__.py
  mgmtsystem_nonconformity_hazard/i18n/it.po
  mgmtsystem_nonconformity_hazard/i18n/mgmtsystem_nonconformity_hazard.pot
  mgmtsystem_nonconformity_hazard/models/__init__.py
  mgmtsystem_nonconformity_hazard/models/mgmtsystem_hazard.py
  mgmtsystem_nonconformity_hazard/models/mgmtsystem_nonconformity.py
  mgmtsystem_nonconformity_hazard/pyproject.toml
  mgmtsystem_nonconformity_hazard/readme/CONTRIBUTORS.md
  mgmtsystem_nonconformity_hazard/readme/DESCRIPTION.md
  mgmtsystem_nonconformity_hazard/readme/USAGE.md
  mgmtsystem_nonconformity_hazard/static/description/icon.png
  mgmtsystem_nonconformity_hazard/static/description/index.html
  mgmtsystem_nonconformity_hazard/views/mgmtsystem_hazard.xml
  mgmtsystem_nonconformity_hazard/views/mgmtsystem_nonconformity.xml
Labels: bot is merging ⏳

#650 [17.0][MIG] mgmtsystem_nonconformity_hazard: Migration to 17.0
  mgmtsystem_nonconformity_hazard/README.rst
  mgmtsystem_nonconformity_hazard/__init__.py
  mgmtsystem_nonconformity_hazard/__manifest__.py
  mgmtsystem_nonconformity_hazard/i18n/it.po
  mgmtsystem_nonconformity_hazard/i18n/mgmtsystem_nonconformity_hazard.pot
  mgmtsystem_nonconformity_hazard/models/__init__.py
  mgmtsystem_nonconformity_hazard/models/mgmtsystem_hazard.py
  mgmtsystem_nonconformity_hazard/models/mgmtsystem_nonconformity.py
  mgmtsystem_nonconformity_hazard/pyproject.toml
  mgmtsystem_nonconformity_hazard/readme/CONTRIBUTORS.md
  mgmtsystem_nonconformity_hazard/readme/DESCRIPTION.md
  mgmtsystem_nonconformity_hazard/readme/USAGE.md
  mgmtsystem_nonconformity_hazard/static/description/icon.png
  mgmtsystem_nonconformity_hazard/static/description/index.html
  mgmtsystem_nonconformity_hazard/views/mgmtsystem_hazard.xml
  mgmtsystem_nonconformity_hazard/views/mgmtsystem_nonconformity.xml
Labels: approved, bot is merging ⏳

#651 [18.0][MIG] mgmtsystem_hazard_risk: Migration to 18.0
  mgmtsystem_hazard_risk/README.rst
  mgmtsystem_hazard_risk/__init__.py
  mgmtsystem_hazard_risk/__manifest__.py
  mgmtsystem_hazard_risk/data/mgmtsystem_hazard_risk_computation.xml
  mgmtsystem_hazard_risk/data/mgmtsystem_hazard_risk_type.xml
  mgmtsystem_hazard_risk/i18n/de.po
  mgmtsystem_hazard_risk/i18n/es.po
  mgmtsystem_hazard_risk/i18n/fr.po
  mgmtsystem_hazard_risk/i18n/hr.po
  mgmtsystem_hazard_risk/i18n/id.po
  mgmtsystem_hazard_risk/i18n/it.po
  mgmtsystem_hazard_risk/i18n/mgmtsystem_hazard_risk.pot
  mgmtsystem_hazard_risk/i18n/nb.po
  mgmtsystem_hazard_risk/i18n/pt_BR.po
  mgmtsystem_hazard_risk/i18n/sl.po
  mgmtsystem_hazard_risk/i18n/vi.po
  mgmtsystem_hazard_risk/models/__init__.py
  mgmtsystem_hazard_risk/models/common.py
  mgmtsystem_hazard_risk/models/mgmtsystem_hazard.py
  mgmtsystem_hazard_risk/models/mgmtsystem_hazard_residual_risk.py
  mgmtsystem_hazard_risk/models/mgmtsystem_hazard_risk_computation.py
  mgmtsystem_hazard_risk/models/mgmtsystem_hazard_risk_type.py
  mgmtsystem_hazard_risk/models/res_company.py
  mgmtsystem_hazard_risk/models/res_config_settings.py
  mgmtsystem_hazard_risk/pyproject.toml
  mgmtsystem_hazard_risk/readme/CONFIGURE.md
  mgmtsystem_hazard_risk/readme/CONTRIBUTORS.md
  mgmtsystem_hazard_risk/readme/DESCRIPTION.md
  mgmtsystem_hazard_risk/security/ir.model.access.csv
  mgmtsystem_hazard_risk/security/mgmtsystem_hazard_security.xml
  mgmtsystem_hazard_risk/static/description/icon.png
  mgmtsystem_hazard_risk/static/description/index.html
  mgmtsystem_hazard_risk/tests/__init__.py
  mgmtsystem_hazard_risk/tests/test_mgmtsystem_hazard.py
  mgmtsystem_hazard_risk/views/mgmtsystem_hazard.xml
  mgmtsystem_hazard_risk/views/mgmtsystem_hazard_residual_risk.xml
  mgmtsystem_hazard_risk/views/mgmtsystem_hazard_risk_computation.xml
  mgmtsystem_hazard_risk/views/mgmtsystem_hazard_risk_type.xml
  mgmtsystem_hazard_risk/views/res_config_settings_views.xml
Labels: approved, bot is merging ⏳

#623 [18.0][MIG] document_page_environment_manual: Migration to 18.0
  document_page_environment_manual/README.rst
  document_page_environment_manual/__init__.py
  document_page_environment_manual/__manifest__.py
  document_page_environment_manual/data/document_page_environment_manual.xml
  document_page_environment_manual/i18n/de.po
  document_page_environment_manual/i18n/document_page_environment_manual.pot
  document_page_environment_manual/i18n/fr.po
  document_page_environment_manual/i18n/it.po
  document_page_environment_manual/i18n/nb.po
  document_page_environment_manual/i18n/pt_BR.po
  document_page_environment_manual/i18n/sl.po
  document_page_environment_manual/i18n/sv.po
  document_page_environment_manual/i18n/vi.po
  document_page_environment_manual/pyproject.toml
  document_page_environment_manual/readme/CONTRIBUTORS.md
  document_page_environment_manual/readme/DESCRIPTION.md
  document_page_environment_manual/readme/USAGE.md
  document_page_environment_manual/static/description/icon.png
  document_page_environment_manual/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳
