Repository OCA/management-system, pull requests merged in 2025-06, with the labels that each got.

#677 [16.0][FIX] mgmtsystem_nonconformity: fix form and kanban views of non conformities
  mgmtsystem_nonconformity/views/mgmtsystem_nonconformity.xml
Labels: approved, ready to merge, bot is merging ⏳

#681 [18.0] mgmtsystem_nonconformity: forward port #677
  mgmtsystem_nonconformity/views/mgmtsystem_nonconformity.xml
Labels: approved, bot is merging ⏳

#684 [FIX] mgmtsystem_nonconformity: Fix JS
  mgmtsystem_nonconformity/README.rst
  mgmtsystem_nonconformity/__manifest__.py
  mgmtsystem_nonconformity/static/description/index.html
  mgmtsystem_nonconformity/static/src/components/chatter_topbar/chatter_topbar.esm.js
  mgmtsystem_nonconformity/static/src/components/chatter_topbar/chatter_topbar.xml
Labels: approved, bot is merging ⏳

#679 [16.0] [IMP] mgmtsystem_hazard: Views and menu entry for mgmtsystem.hazard.hazard
  mgmtsystem_hazard/README.rst
  mgmtsystem_hazard/__manifest__.py
  mgmtsystem_hazard/models/mgmtsystem_hazard_hazard.py
  mgmtsystem_hazard/readme/ROADMAP.rst
  mgmtsystem_hazard/static/description/index.html
  mgmtsystem_hazard/views/mgmtsystem_hazard_hazard.xml
Labels: enhancement, needs review, approved, bot is merging ⏳
